### ISSUE TITLE
[BUG] 文章页面 刷新网页图片会变小

### ISSUE THREAD

**Issue by Meilinhost** [HEIGE-PCloud/DoIt#1005]
### Describe the bug 描述你遇到的错误

还是loveit遗留问题，在doit还是存在
这是当时的详细信息
https://github.com/dillonzq/LoveIt/issues/311

### Expected behavior 期待的行为

等大佬修复

### Screenshots 屏幕截图
先看正常的
![wt1](https://github.com/HEIGE-PCloud/DoIt/assets/3524108/e85d088e-13a4-45d9-b72d-7acf5b8c2ae1)

然后刷新页面图片变小
![wt2](https://github.com/HEIGE-PCloud/DoIt/assets/3524108/8f3280ea-3c81-4cdd-8a21-88535203f0d3)

### Build Environment 构建环境

debian11
hugo v0.115.0

### Preview Environment 预览环境

演示站查看 ovh3.xidcn.com

### Additional Information 补充信息

如果按教程给它 强制width: 100%; 会导致其他链接失效的空白图片也跟着放大100%
我看https://hugodoit.pages.dev/zh-cn/ 没有这类问题 刷新页面图片不会变小
为了复现故障 可以到我这个演示站查看 ovh3.xidcn.com

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
<img width="1512" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/70063177/663d21a6-f7af-4787-9f08-c7cbaf8c0b22">

无法复现，可能是网络问题？

**Comment by Meilinhost** [comment]
> <img alt="图像" width="1512" src="https://user-images.githubusercontent.com/70063177/251028480-663d21a6-f7af-4787-9f08-c7cbaf8c0b22.png">
> 无法复现，可能是网络问题？

您的截图页面能看出来文章图片尺寸已经变小了，应该不是网络问题，之前loveit也有这个问题，不少人遇到过，首次打开文章照片大小正常，如果您F5刷新就会发现图片明显变小了

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
loveit的issue我看了下，主要是和lazysizes.js有关系，但是doit已经采用了原生懒加载了

如果能找到更多的类似情况的话我会进一步看下

**Comment by Meilinhost** [comment]
好的，我先这样对付着用并等待后续

**Comment by HEIGE-PCloud** [comment]
macOS 上的 Chrome, Safari 和 Firefox 都没有复现。。。

**Comment by Meilinhost** [comment]
> macOS 上的 Chrome、Safari 和 Firefox 都没有复现。。。

我测试了下面两个常用的系统环境，都会出现问题。
windows7---chrome 
windows10---chrome
windows10 ---Edge

为了排除是windows7的问题，我在windows10 系统下也测试了，刷新也会让图片变小，不是Windows7的问题，并且继续刷新也无法将变小的图片变回初始那种大小，但是测试一直重复ctrl+f5 有几率变回原本大小，也可能会一个大一个小
试着把图片强制 width: 100% 就不会刷新变小，但是看起来很怪，大图还好，小图被强制100%就直接模糊的一塌糊涂。 明天再看看是不是中文文件夹的缘故

![22](https://github.com/HEIGE-PCloud/DoIt/assets/3524108/5b3cae7d-c70d-498f-8308-888230c06723)

**Comment by Meilinhost** [comment]
换了一台机器全新安装试了下，问题挺明显的 难道就我一个人有这情况？

![1111](https://github.com/HEIGE-PCloud/DoIt/assets/3524108/98a5b89b-52f1-46be-a33d-5da030e59389)

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
我觉得是网络问题吧。。。

**Comment by Meilinhost** [comment]
> 我觉得是网络问题吧。。。

真不是网络问题。。。
说话的空档，我换了一个主题测试 选用了hugo-fixit 
没有出现刷新 图片变小的问题

建议新标签页打开这个GIF图片观看 可以直观的全频观看图片大小与缩小后的百分比

![2222](https://github.com/HEIGE-PCloud/DoIt/assets/3524108/7df54dc4-11f0-441f-ad2d-bbacfc3c779b)

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
你的图片本来就应该是那么小的，无论是doit还是fixit都只限制了过大的图片，小图片按原大小显示

如果不能提供可靠的复现步骤或者一开始所谓变大时的图片元素信息，不会继续调查

<img width="1335" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/70063177/19e269f5-4218-4ab2-a658-28bdd7de1786">

**Comment by eallion** [comment]
我也很早就发现这个问题了，我以为是一个 Feature ！
Win + Chrome。
Devtools 禁用缓存时，没有此问题，可能跟缓存或者 pwa 有关。

**Comment by eallion** [comment]
我的博客已无法复现，今天换了灯箱插件，那更大的可能是跟 `lightGallery.js` 相关。

**Comment by Meilinhost** [comment]
> 你的图片本来就应该是那么小的，无论是doit还是fixit都只限制了过大的图片，小图片按原大小显示
> 
> 如果不能提供可靠的复现步骤或者一开始所谓变大时的图片元素信息，不会继续调查
> 

正常图片截图 此时宽度是 523x385
![1111111111](https://github.com/HEIGE-PCloud/DoIt/assets/3524108/52808105-70d2-4c38-82de-68fb889d3c95)
刷新网页图片不正常时候尺寸是  261x193
![xiao](https://github.com/HEIGE-PCloud/DoIt/assets/3524108/512f42d9-ee55-44e7-86d0-545434e54520)

复现方式就是windows环境 前面提到过
图片在当初截图时候就以原始图片不放大能看到图中文字，bug发生时就让大图不放大，小图反而缩小，让目视都无法看清图中文字的地步 
故障就像原版的loveit 故障一样，我也讲不上来哪里导致的问题 贴几个之前相关问题的的讨论 您参考下

https://github.com/dillonzq/LoveIt/issues/452

https://github.com/dillonzq/LoveIt/issues/311?tdsourcetag=s_pctim_aiomsg

https://github.com/aFarkas/lazysizes/issues/508

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
我给你的img手动加了height和width就没事了

你的配置有问题，本地图片的这些尺寸是自动获取的

> 文件结构参考 https://github.com/HEIGE-PCloud/DoIt/tree/main/exampleSite/content/posts/theme-documentation-basics

<img width="1512" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/70063177/1a25d86b-5cf8-4266-8fc1-b0713609d5c7">

**Comment by Meilinhost** [comment]
获取本地图片尺寸在刷新前是正常的，刷新后就丢失尺寸。
您的意思是在写文章的时候给图片指定width="" height=""  这样是不是有点重复造轮子，我在想，它获取本地图片尺寸是正常的，问题是不是应该在刷新后获取图片尺寸错误的问题上。
因为在doit和fixit 我都是用 ![](images/图片) 并没有指定尺寸，doit刷新获取尺寸会出错，fixit没有出错，fixit也有lightgallery.js  却没有出现bug

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
> 获取本地图片尺寸在刷新前是正常的，刷新后就丢失尺寸。
> 您的意思是在写文章的时候给图片指定width="" height="" 这样是不是有点重复造轮子，我在想，它获取本地图片尺寸是正常的，问题是不是应该在刷新后获取图片尺寸错误的问题上。
> 因为在doit和fixit 我都是用 ![](images/%E5%9B%BE%E7%89%87) 并没有指定尺寸，doit刷新获取尺寸会出错，fixit没有出错，fixit也有lightgallery.js 却没有出现bug

呃我给你加是为了测试。。。

这些东西DoIt会[自动获取](https://github.com/HEIGE-PCloud/DoIt/blob/fe2e800f0690ee38e7926c68d223f92d98ac29d3/layouts/partials/plugin/image.html#L12-L13)的，不是什么造不造轮子，因为你配置有问题，DoIt没有给你自动获取，浏览器就替你做了决定，所以才会这样。。。

**Comment by Meilinhost** [comment]
> 这些东西DoIt会[自动获取](https://github.com/HEIGE-PCloud/DoIt/blob/fe2e800f0690ee38e7926c68d223f92d98ac29d3/layhttps://github.com/HEIGE-PCloud/DoIt/blob/fe2e800f0690ee38e7926c68d223f92d98ac29d3/layouts/partials/plugin/image.html#L12-L13outs/partials/plugin/image.html#L12-L13)的，不是什么造不造轮子，因为你配置有问题，DoIt没有给你自动获取，浏览器就替你做了决定，所以才会这样。。。

了解！ 问题出在layouts 没有复制到根目录下？ 
我该怎么修复下它 完全没头绪

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
试试相对目录，就像feature image一样？

feature image和image走的是一个pipeline

我自己是用了本地缓存远程图床的选项，本地图片那些的没试过

**Comment by Meilinhost** [comment]
feature image 确实是获取到了尺寸 刷新它也不会变
image 感觉有点难办，丢给它的就是绝对路径
一直是这么写的
```
![](images/Screenshot_20230108-512x1024.jpg)

```
就是想不通到底哪里问题。。。

看着像是懒加载问题啊
 正常图片的
![IMG_20230707_215558_294](https://github.com/HEIGE-PCloud/DoIt/assets/3524108/02015f7d-427b-4b1c-abe3-1f6e96c5c93f)

图片变小的
![IMG_20230707_215601_866](https://github.com/HEIGE-PCloud/DoIt/assets/3524108/dd96679e-f87a-431f-9769-103872109bd8)

**Comment by HEIGE-PCloud** [comment]
@Meilinhost 也许把 lightgallery 关了试试？

**Comment by Meilinhost** [comment]
> 也许把 lightgallery 关了试试？

@HEIGE-PCloud 
```
lightgallery = false
```
关闭 lightgallery 问题依旧。。。2333

**Comment by Meilinhost** [comment]
fixit [演示站](http://ovh1.xidcn.com)  搭起来了，两个对比了下，发现文章页的image尺寸是获取到的。 doit是没有获取到
其他倒是没发现什么太明显区别。
image 获取不到本地图片尺寸，是个例还是bug？

**Comment by eallion** [comment]
另外我还修改了 [`layouts/partials/plugin/image.html`](https://github.com/eallion/eallion.com/blob/e1947eeedae648258f2214b1294be8464bf8c868/layouts/partials/plugin/image.html#L38-L60)

```diff
- <!-- {{- if .Linked -}}
-     <a class="lightgallery" href="{{ $large | safeURL }}" title="{{ .Title | default $alt }}" data-thumbnail="{{ $small | safeURL }}"{{ with .Caption }} data-sub-html="<h2>{{ . }}</h2>{{ with $.Title }}<p>{{ . }}</p>{{ end }}"{{ end }}{{ with .Rel }} rel="{{ . }}"{{ end }}>
-         <img
-             {{ with .Class }}class="{{ . }}"{{ end }}
-             loading="{{ $loading }}"
-             src="{{ $src | safeURL }}"
-             srcset="{{ $small | safeURL }}, {{ $src | safeURL }} 1.5x, {{ $large | safeURL }} 2x"
-             sizes="auto"
-             alt="{{ $alt }}"{{ with $height }} height="{{ . }}" {{ end }}{{ with $width }} width="{{ . }}" {{ end }}>
-     </a>
- {{- else -}}
-     <img
-         {{ with .Class }}class="{{ . }}"{{ end }}
-         loading="{{ $loading }}"
-         src="{{ $src | safeURL }}"
-         srcset="{{ $small | safeURL }}, {{ $src | safeURL }} 1.5x, {{ $large | safeURL }} 2x"
-         sizes="auto"
-         alt="{{ $alt }}"
-         title="{{ .Title | default $alt }}"{{ with $height }} height="{{ . }}" {{ end }} {{ with $width }} width="{{ . }}" {{ end }}>
- {{- end -}} -->

+ <!-- 新方法，把全站图片灯箱从 lightgallery.js 换成了 zoom-vanilla.js -->
+ <img src="{{ $src | safeURL }}" alt="{{ $alt }}" data-action="zoom">
```
不知道有没有关系。

**Comment by Meilinhost** [comment]
@eallion 感觉不全是lightgallery.js问题，
fixit我测了开启lightgallery灯箱，本地图片尺寸也是能正常获取到。

又活捉一只大佬站点，也是没有获取到尺寸 也在刷新变大变小

![123](https://github.com/HEIGE-PCloud/DoIt/assets/3524108/da0c1f74-ce0c-46a8-9608-d656e10e2ac9)

**Comment by eallion** [comment]
我以前认为这是一个 Feature，所以没有理它。现在看来是一个 Bug 了。我现在也没空复现，只有提供了一些思路。具体是哪里的问题还得找找。

**Comment by Sped0n** [comment]
https://discourse.gohugo.io/t/the-base-path-for-resource-get/12823/4

不能说是bug，hugo本身就没有获取这些的能力，除非你愿意去用存assets里的方式

fixit怎么做到的我不是很关心，代码基本都是loveit那一套，只能说hugo更新这项功能的时候我会跟进

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
发现是我之前留下的一个typo，尴尬了。。。

**Comment by eallion** [comment]
没事！加油！

**Comment by Meilinhost** [comment]
nice! 困扰许久的问题似乎又看到了曙光

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
@Meilinhost 

我这边本地试了一下，用的是之前测试的时候从你网站下的图片，大小是正常的

如果您那边方便而且还在用doit的话可以试试？更改已经merge到主分支了

**Comment by Meilinhost** [comment]
@Sped0n 
我将错误的函数进行了修改，并生成静态网页 不再出现刷新变小的情况！图片正常获取到height和width
此BUG无法再复现，已经彻底解决。
