### ISSUE TITLE
[BUG] Author Avatar not updating

### ISSUE THREAD

**Issue by LV-6502** [HEIGE-PCloud/DoIt#1015]
### Describe the bug 描述你遇到的错误

Sincere apologies upfront as I am new to Hugo and this is likely user error. I'm trying to update the following icon to reflect the Authors profile:
![image](https://github.com/HEIGE-PCloud/DoIt/assets/66678775/88f20a89-6472-4310-9795-5f2feadbb01b)

I have created a new toml under data/authors "authX.toml"
Which contains:
`avatar = "https://hugodoit.pages.dev/images/avatar.webp"`

I then call this in my post with:
`authors: ["authX"]`

However nothing updates. 
I have also tried the following direct in the config.toml with no luck:
```
[author]
  name = "authX"
  email = ""
  link = ""
  avatar = "https://hugodoit.pages.dev/images/avatar.webp"
  gravatarEmail = ""
```
Am I missing something?
Thanks in advance,
L

### Build Environment 构建环境

hugo v0.92.2+extended
DoIt: version = "0.3.X"

**Comment by HEIGE-PCloud** [comment]
Yeah that icon is not designed to be customised, it's too small to put a picture there so what you have seen is expected behaviour. That said, do you have any better design in mind to display authors' avatars?

**Comment by LV-6502** [comment]
Roger, understood!

Good question and without getting too philosophical on design elements: In its current state my first impression was 'they just didn't bother setting a picture for the demo site, let me dig around for the config..'

But knowing its not customisable really makes it redundant? If the authors cannot add a touch of personality next to their names, what purpose does the icon serve?

The only thing that comes to mind is perhaps the option to set an emoji or FontAwesome icon.

For any other noobs like me:
Setting up for configurable FontAwesome icons is relatively straight forward:

**Note** It can only handle one author. You will get errors if you list two authors in a post.. Only good if you're the sole author on the site.

Under ./data/authors/ create your author_X.toml
```
name = "AuthX"
authorIcon = 'fas fa-solid fa-rocket fa-fw'
```
Under ./themes/DoIt/layouts/partials/meta/author.html
Add to the top:
```
{{- $author := index $.Site.Data.authors .Params.authors -}}
{{- $icon := dict "Class" $author.authorIcon }}
```
Ensure "fontawesome: true" in your post.md
Now when you call your author in your post:
authors: ["author_X"]

It will display the chosen icon:
![image](https://github.com/HEIGE-PCloud/DoIt/assets/66678775/1834bba5-915f-4906-bf2e-2c5dbbbd26c2)
