### ISSUE TITLE
[BUG] can not override global font

### ISSUE THREAD

**Issue by youngxhui** [HEIGE-PCloud/DoIt#1016]
### Describe the bug 描述你遇到的错误

在 override 文件中添加新的字体

<img width="1276" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/16971804/da426dd5-d4b4-439a-baea-573b4f674172">

在网页上无法正常生效，没有添加的新字体，但是会从 cdn 上加载字体文件，同时字体的大小的变量是生效的

<img width="665" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/16971804/cebc1c07-f56c-4f42-8dd3-1a08ca3a7415">

https://youngxhui.top/2023/07/neovim-%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97-%E4%B8%80/

### Expected behavior 期待的行为

<img width="610" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/16971804/15056aee-0212-4c85-ab58-2e2e0806cba7">
应该会出现新的字体才对

### Build Environment 构建环境

hugo v0.115.3+extended linux/amd64

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
可以复现，这个其实是scss这个覆盖优先级的问题，具体你可以自己去查资料，[tldr](https://stackoverflow.com/questions/17089717/how-to-overwrite-scss-variables-when-compiling-to-css)的话就是如果后面有其他变量使用了你想要覆盖的变量，你就没法覆盖了，这个import覆盖的机制挺复杂的，我自己尝试了一下，在import之后写了一段一样的代码，结果import不生效，代码生效了

<img width="1512" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/70063177/cf0b4211-b0a2-405b-b42d-a454cf2d9e06">

暂时没什么好的解决方法，规范就是如此，要的话你就直接改`_variable.scss`吧

**Comment by HEIGE-PCloud** [comment]
<img width="1512" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/52968553/62fbd1cb-475d-4c2f-826e-f77d3f8be726">
<img width="1624" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/52968553/0dce2512-22ff-4c92-8787-d7da5a1248e0">

为啥我没复现。。。

https://github.com/HEIGE-PCloud/DoIt/blob/7f052579e4dec5d29e78a446b34dc5d33004e99d/assets/css/style.scss#L3-L4

照理说也不应该啊，override 是紧跟 variables 后面的。

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
噢我注意到了，你是在`exampleSite`下面操作的，我俩应该都是在`assets`下面操作的

**Comment by HEIGE-PCloud** [comment]
直接在 DoIt/assets/css/_override.scss 里改，且运行 exampleSite 的话应该会被 exampleSite 里空的 override.scss 给覆盖的吧。试试改 your_site/assets/css/_override.scss？还会出这个问题吗？

**Comment by youngxhui** [comment]
> 直接在 DoIt/assets/css/_override.scss 里改，且运行 exampleSite 的话应该会被 exampleSite 里空的 override.scss 给覆盖的吧。试试改 your_site/assets/css/_override.scss？还会出这个问题吗？

上面的例子就是在 your_site/assets/css/_override.scss 修改的

**Comment by youngxhui** [comment]
在 override 中添加 `!important` 解决了。

```scss
@import url('https://cdn.bootcdn.net/ajax/libs/lxgw-wenkai-webfont/1.7.0/lxgwwenkai-light.min.css');
$global-font-family: 'LXGW WenKai', system-ui, -apple-system, BlinkMacSystemFont, PingFang SC, Microsoft YaHei UI, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, Helvetica, Arial, sans-serif !important;
```

<img width="1353" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/16971804/1a59d994-bc6e-4448-ab48-14190c7aae89">


https://youngxhui.top/2023/07/neovim-%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97-%E4%B8%80/
