### ISSUE TITLE
[BUG] Dark theme overrides cosmetic settings from custom shortocde

### ISSUE THREAD

**Issue by LV-6502** [HEIGE-PCloud/DoIt#1019]
### Describe the bug 描述你遇到的错误

I created a shortcode to help embed an iframe from Steam:
```

<div class="spec_div" test style="background-color: rgb(197, 32, 32);">
    <iframe src="{{ .Get 0 }}" width="{{ .Get 1 }}" height="{{ .Get 2 }}" frameborder="0"></iframe>
</div>
```
To illustrate the point, I'm setting the background of it red - Ideally I will want it to match the background so it looks seamless.

While in light mode, the colour comes through as intended:
![image](https://github.com/HEIGE-PCloud/DoIt/assets/66678775/f6b2642b-0b0c-4457-8a1a-f2c534b23e57)

When I switch to dark mode, it reverts to the colour white:
![image](https://github.com/HEIGE-PCloud/DoIt/assets/66678775/4c43fb49-c3f7-4871-a6a0-9228467a13d9)

How can I get the shortcode to persist the set background colour?

**Comment by HEIGE-PCloud** [comment]
background-color: rgb(197, 32, 32) !important;
