### ISSUE TITLE
[FEATURE] Adding [optional] summary in the article

### ISSUE THREAD

**Issue by yewentao256** [HEIGE-PCloud/DoIt#1029]
### Describe the feature you want 描述你的功能需求

We have summary in our posts, like

```md
---
title: "How Pytorch 2.0 Call Ops(1)"
date: 2023-03-11T09:53:09+08:00
categories: ["pytorch"]
summary: "This article introduces the process of pytorch 2.0 calling ops, using `contiguous` as an example."
---
```

We can see it in the home page:

<img width="689" alt="企业微信截图_cc1bbc22-a830-4d5d-8113-c1b918611f8f" src="https://github.com/HEIGE-PCloud/DoIt/assets/44945378/61363ecc-a355-4814-bb2b-2bd94fdc30e5">

Could it be automatically added into the article's head? (maybe optional?)

Eg:

<img width="673" alt="企业微信截图_91415f73-1d19-44a4-83b5-1b277407d5f6" src="https://github.com/HEIGE-PCloud/DoIt/assets/44945378/eea1eeb2-aafa-4b1b-98ce-0940dbf5ba6b">

**Comment by renzhamin** [comment]
Instead of adding summary in the front-matter, you could write the summary in the head and end it with `<!--more-->`. In this way, it will be included in the article and also be used as the summary 

```

---
title: "How Pytorch 2.0 Call Ops(1)"
date: 2023-03-11T09:53:09+08:00
categories: ["pytorch"]
---

This article introduces the implementation details of pytorch autograd mechanism.

<!--more-->
```

**Comment by yewentao256** [comment]
Yes, it works! Thank you very much
