### ISSUE TITLE
[FEATURE] Add the author avatar to the post meta

### ISSUE THREAD

**Issue by mafendi** [HEIGE-PCloud/DoIt#1030]
### Describe the feature you want 描述你的功能需求

Here is how you can add this functionality: 

in partials/meta/author.html 

comment: 
        `<!-- {{- partial "plugin/icon.html" $icon -}} -->`

add avatars to the author's link: 

```
<a href='{{ .link | absURL }}'>
  {{- if .avatar -}}
    <img src="{{ .avatar }}" title="{{ .name }}" alt="{{ .name }}" class="svg icon" style="height: 1.25rem; margin-right: 0.25rem; border-radius: 50%;">
  {{- end -}}
{{- .name -}}</a>
```

Don't forget to name your file in data/authors the same way as you specify it in the post. 

Screenshot is attached
![brave_screenshot_localhost](https://github.com/HEIGE-PCloud/DoIt/assets/76495108/e7570d63-4825-4acc-90a0-4388ec037065)

**Comment by mafendi** [comment]
Here is the [link](https://leipapa.com/blog/jurisdictional-surcharge-update-for-egypt-eg-lei-codes/ "LEIpapa Blog")

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
My thoughts was do it with gravatar, need to specify a local file each time is kinda annoying

**Comment by mafendi** [comment]
If there is a gravatar email specified in the author's TOML file, $avatar variable assigns the gravatar image instead of the local file. So, there is no need to specify the local file manually.

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
Oh I see, haven't noticed it before. Might move the path config to author.toml if I gonna implement this feature.

Btw another thing I'm not sure about is the design for multi-author avatars display, do you have any ideas?

**Comment by mafendi** [comment]
Currently, it looks like that... 

![brave_screenshot_localhost](https://github.com/HEIGE-PCloud/DoIt/assets/76495108/bf5fd97d-c5a4-4823-8a9e-543210f4128f)

not ugly but can be improved
