### ISSUE TITLE
[BUG] 代码框无法正常渲染，无复制按钮、无折叠按钮  Code box not rendering properly, no copy button, no collapse button

### ISSUE THREAD

**Issue by IHKYoung** [HEIGE-PCloud/DoIt#1037]
### Describe the bug 描述你遇到的错误

代码相关的区域无法被渲染，**没有复制按钮、没有折叠效果：**
如图所示，可以复现在Ubuntu和MacOS系统上，有遇到相同情况的吗？
The code related area cannot be rendered, **there is no copy button, no collapsing effect:**
As shown, it can be reproduced on Ubuntu and macOS systems, have you encountered the same situation?

<img width="647" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/100593787/32fe6785-bad9-4f40-8b9f-b5621ba0bcec">

### Expected behavior 期待的行为

<img width="648" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/100593787/1e3f96c9-076c-4063-9cb0-76737fc84fe8">

### Screenshots 屏幕截图

我遇到的情况：
I encountered a situation:
<img width="647" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/100593787/0c1a7797-37f6-4f18-81c3-f83d3126924b">

官方网址的情况：
The case of the official Web site:
<img width="648" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/100593787/1e3f96c9-076c-4063-9cb0-76737fc84fe8">

### Build Environment 构建环境

macOS和Ubuntu系统同时有该问题：
Both macOS and Ubuntu systems have the problem:

- macOS、Ubuntu22.04
- Safari、Chrome
- Hugo v0.117.0(MacOS)、v0.92.2(Ubuntu)

### Preview Environment 预览环境

macOS和Ubuntu系统同时有该问题：
Both macOS and Ubuntu systems have the problem:

- macOS、Ubuntu22.04
- Safari、Chrome
- Hugo v0.117.0(MacOS)、v0.92.2(Ubuntu)

### Additional Information 补充信息

配置中已经默认开启：
It is already enabled by default in the configuration:

# 代码配置
    [params.page.code]
      # whether to show the copy button of the code block
      # 是否显示代码块的复制按钮
      copy = true
      # the maximum number of lines of displayed code by default
      # 默认展开显示的代码行数
      maxShownLines = 50

**Comment by HEIGE-PCloud** [comment]
Can you provide a minimal reproducible example? Are there any errors in the DevTool Console?

**Comment by IHKYoung** [comment]
It can be reproduced using the example in "exampleSite";
At first I thought it was the Hugo version, the latest version is 0.117, I tried to return to 0.100, 0.80, 0.60, all have the same problem, then I wondered if it was a problem with the compilation platform, so I switched from macOS to Linux, and At the same time, I tried both Intel and M1 MacOS, and the same code box could not be rendered;
Use Chrome development mode to view, there is indeed no call to "chroma" in the code box area
💔It is very painful that my front-end knowledge is not deep enough. I can’t solve this bug for the time being.

**Comment by IHKYoung** [comment]
> Can you provide a minimal reproducible example? Are there any errors in the DevTool Console?

It can be reproduced using the example in "exampleSite";
At first I thought it was the Hugo version, the latest version is 0.117, I tried to return to 0.100, 0.80, 0.60, all have the same problem, then I wondered if it was a problem with the compilation platform, so I switched from macOS to Linux, and At the same time, I tried both Intel and M1 MacOS, and the same code box could not be rendered;
Use Chrome development mode to view, there is indeed no call to "chroma" in the code box area
💔It is very painful that my front-end knowledge is not deep enough. I can’t solve this bug for the time being.

**Comment by IHKYoung** [comment]
I found the reason! 😄
It's that you need to configure it according to the latest hugo, for example using hugo.toml
