### ISSUE TITLE
[BUG] 标题的打字效果有BUG

### ISSUE THREAD

**Issue by VanLiuZhi** [HEIGE-PCloud/DoIt#107]
### Describe the bug 描述你遇到的错误

BUG如图所示

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/22883555/122326448-e3c2c500-cf5e-11eb-8881-e1c518140da3.png)

### Build Environment 构建环境

- OS: [e.g. macOS]
- Theme version master最新
- Hugo Static Site Generator v0.80.0/extended darwin/amd64 BuildDate: unknown

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/122371234-9d1d9c80-cf57-11eb-8f9b-f04ce76ea03f.png)

没有能够复现，能否提供更详细的信息？也可以提供网站源文件以便调试。

**Comment by VanLiuZhi** [comment]
> ![image](https://user-images.githubusercontent.com/52968553/122371234-9d1d9c80-cf57-11eb-8f9b-f04ce76ea03f.png)
> 
> 没有能够复现，能否提供更详细的信息？也可以提供网站源文件以便调试。

没有复现吗？我好好看了文档，安装了最新版本的hugo，直接hugo new site 一个新项目，然后把我的content目录拷贝，
配置文件就使用 https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/ 给出的，然后把菜单加上

开启标题的打字机效果 typeit = true

```
[params.header.title]
      # LOGO 的 URL
      logo = ""
      # 标题名称
      name = ""
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # DoIt 新增 | 0.2.5 是否为标题显示打字机动画
      typeit = true
```

此时标题打字机效果是有了的，点击菜单切换，比如点击 文章，标签切换菜单
标题的打字机效果就会打印到第二行，并且开始循环，如下图所示

![1](https://user-images.githubusercontent.com/22883555/122495599-e552c280-d01c-11eb-9d83-b8e9fd1b1c7a.gif)

**Comment by HEIGE-PCloud** [comment]
我在文档主页也开启了 TypeIt，能否前往 https://hugodoit.pages.dev 查看该问题是否存在。
![Animation](https://user-images.githubusercontent.com/52968553/122530472-69557c00-d016-11eb-888c-f0188e00b11a.gif)
我在 Windows 10 + Chrome 下没有能复现相关问题，怀疑是否是由兼容性问题导致。请问控制台（F12）中是否有报错？

**Comment by VanLiuZhi** [comment]
> 我在文档主页也开启了 TypeIt，能否前往 https://hugodoit.pages.dev 查看该问题是否存在。
> ![Animation](https://user-images.githubusercontent.com/52968553/122530472-69557c00-d016-11eb-888c-f0188e00b11a.gif)
> 我在 Windows 10 + Chrome 下没有能复现相关问题，怀疑是否是由兼容性问题导致。请问控制台（F12）中是否有报错？

我是 mac ，你的demo打开没有问题，我自己的打开控制台有报错

![image](https://user-images.githubusercontent.com/22883555/122534860-89f0f680-d055-11eb-9be3-ea66fb7537a9.png)

讲道理我是一个新的站点，这么还会出现这种问题

**Comment by HEIGE-PCloud** [comment]
可以将网站中的文章删除，然后将整个站点打包发给我吗？我重新创建了一个新的站点，但还是没有能复现这个问题。🤔

**Comment by VanLiuZhi** [comment]
[my.zip](https://github.com/HEIGE-PCloud/DoIt/files/6679797/my.zip)
文件在这了

**Comment by HEIGE-PCloud** [comment]
破案了，你使用了 `dev/pjax` 的分支上正在开发的版本。试着[切换回 `main` 分支](https://stackoverflow.com/questions/1777854/how-can-i-specify-a-branch-tag-when-adding-a-git-submodule)，或者使用 https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/ 上的指南重新创建你的站点。

**Comment by HEIGE-PCloud** [comment]
无论是哪个命令
```
git clone https://github.com/HEIGE-PCloud/DoIt.git themes/DoIt
```
```
git init
git submodule add https://github.com/HEIGE-PCloud/DoIt.git themes/DoIt
```
都会保证主题处于默认的 `main` 分支上，不知道你是否做过手动切换才导致这一问题。

**Comment by VanLiuZhi** [comment]
> 无论是哪个命令
> 
> ```
> git clone https://github.com/HEIGE-PCloud/DoIt.git themes/DoIt
> ```
> 
> ```
> git init
> git submodule add https://github.com/HEIGE-PCloud/DoIt.git themes/DoIt
> ```
> 
> 都会保证主题处于默认的 `main` 分支上，不知道你是否做过手动切换才导致这一问题。

我就是用这个命令下载的主题，你对比过代码发现我打包给你的不是master分支的，是这样吧

**Comment by VanLiuZhi** [comment]
好吧，我是用的码云的仓库，GitHub很慢，就用码云导入了一下，没注意分支怎么就切到 dev/pjax。感谢作者这么费心👍
