### ISSUE TITLE
[FEATURE] Admonition for Code

### ISSUE THREAD

**Issue by unklnik** [HEIGE-PCloud/DoIt#1074]
### Describe the feature you want 描述你的功能需求

Maybe this is existing however I am trying to workout how to recreate the code snippets that are used in the DoIt documentation (as in image). Basically I want to also have the grey boxes with the COPY CODE icon in the right corner. Is there a way to do this with short codes? I have tried using the ``` method however this does not seem to produce the same result. If it is not a feature yet then it would be great to have.

![image](https://github.com/HEIGE-PCloud/DoIt/assets/146096950/f970f1e9-0968-4a50-8291-c1697e4dc4cc)

**Comment by HEIGE-PCloud** [comment]
I don't quite understand your question, this is the source code for your screenshot. Can you show me an example where ``` method does not work?

````md
```markdown
{{</* admonition type=tip title="This is a tip" open=false */>}}
A **tip** banner
{{</* /admonition */>}}
Or
{{</* admonition tip "This is a tip" false */>}}
A **tip** banner
{{</* /admonition */>}}
```
````

**Comment by unklnik** [comment]
Apologies, haven't used this theme before and I am probably doing something wrong however if you view this page  https://unklnik.com/posts/2d-vector2-border-collisions/

You will see that when I copy and paste that code exactly as you typed above into the markdown file I get what you see in the image , which looks completely wrong. Black background, no header or copy icon. I have added this in the TOML file so not really sure what is going on. I have not altered or added any custom CSS it is default Hugo Extended & DoIt install.

```
  [params.page.code]
  # whether to show the copy button of the code block
  copy = true
  # the maximum number of lines of displayed code by default
  maxShownLines = 10
```
**THIS IS WHAT DISPLAYS USING THE CODE YOU SUPPLIED?**
![image](https://github.com/HEIGE-PCloud/DoIt/assets/146096950/d55e1b26-3778-454b-86ae-4406105741d2)

**Comment by HEIGE-PCloud** [comment]
Remove `pygmentsUseClassic=true` in your config file.

**Comment by unklnik** [comment]
Config file? It is not in hugo.toml so where should I look?

**Comment by unklnik** [comment]
OK, so this was my mistake a newbie. So, basically I had copied the code below:

    [markup]
      [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        noHl = false
        style = 'monokai'
        tabWidth = 4

over the code below:

    # Markup related configuration in Hugo
    [markup]
      # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
      [markup.highlight]
        # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
        noClasses = false

Once I had replaced the Basic Configuration  code it suddenly works. Thanks
