### ISSUE TITLE
[BUG] strange display summary in home page

### ISSUE THREAD

**Issue by wu0407** [HEIGE-PCloud/DoIt#1077]
### Describe the bug 描述你遇到的错误

If a manual summary with `more` tag and contains the title it displays as HTML, not plaintext.

### Expected behavior 期待的行为

Show only text regardless of whether it contains more tag or not.

### Screenshots 屏幕截图

![image](https://github.com/HEIGE-PCloud/DoIt/assets/7602218/62db114e-c401-4a64-92bc-15f86be6c843)

### Build Environment 构建环境

Hugo 0.117.0

### Preview Environment 预览环境

chrome

### Additional Information 补充信息

relate issue: https://github.com/gohugoio/hugo/issues/8910

**Comment by wu0407** [comment]
https://github.com/gohugoio/hugo/issues/8562

**Comment by HEIGE-PCloud** [comment]
Actually many people want this behaviour. In your case, it makes more sense to hand craft a description in the front matter if you need precise control of it. i.e. 

```markdown
---
description: "This is my custom plain text description."
---
```

**Comment by wu0407** [comment]
change like this:
```
diff --git a/layouts/_default/summary.html b/layouts/_default/summary.html
index 1f38c69d..469109f4 100644
--- a/layouts/_default/summary.html
+++ b/layouts/_default/summary.html
@@ -83,7 +83,7 @@
     {{- /* Summary content */ -}}
     <div class="content">
         {{- with .Summary -}}
-            {{- dict "Content" . "Ruby" $params.ruby "Fraction" $params.fraction "Fontawesome" $params.fontawesome | partial "function/content.html" | safeHTML -}}
+            {{- dict "Content" . "Ruby" $params.ruby "Fraction" $params.fraction "Fontawesome" $params.fontawesome | partial "function/content.html" | plainify | htmlUnescape  | chomp -}}
         {{- else -}}
             {{- .Description | safeHTML -}}
         {{- end -}}
```

result:
![image](https://github.com/HEIGE-PCloud/DoIt/assets/7602218/e087209a-62c2-4b2b-a8ab-9419248a2588)

**Comment by HEIGE-PCloud** [comment]
Many people actually want this behaviour to display rich text in summary. In your case it makes more sense to hand-craft the summary in the front matter. i.e.

```markdown
---
summary: "this is the plain text summary"
---
```

and remove the more tag.

Reference: https://gohugo.io/content-management/summaries/#summary-selection-order
