### ISSUE TITLE
Google Search Console is unable to index pages

### ISSUE THREAD

**Issue by unklnik** [HEIGE-PCloud/DoIt#1084]
### Describe the bug 描述你遇到的错误

I only recently started using DoIt however have been making sites using HTML and CSS for many years. Anyway, never seen this error before. Basically I am trying to get the site pages onto Google Search Index using Search Console. though I cannot due to an error that effects all pages FAILED:HOSTLOAD EXCEEDED (see image in screenshots section). 

So, what that means is that even though the template is great and I love it, Google Search Index does not like it. I have not changed the template in anyway and know from experience that something is wrong. I used Gtmetrix.com to analyse the page and it gives an excellent score however reports a LARGE DOM size which I think looks like the problem. This affects all pages of the site, not just one.

The other thing to note here is that this does not happen with Bing Webmaster Tools, which indexes the site fine. Currently, on Google, only the homepage is indexed nothing else.

### Expected behavior 期待的行为

Pages get indexed in search.

### Screenshots 屏幕截图

![image](https://github.com/HEIGE-PCloud/DoIt/assets/146096950/b72eef9c-a116-477c-a684-6be47971d8ad)

![image](https://github.com/HEIGE-PCloud/DoIt/assets/146096950/b9673141-d70f-42b6-abf2-4330cc37f888)

### Build Environment 构建环境

Windows 10 
DoIt v0.4.0
Hugo v0.119

### Preview Environment 预览环境

Windows 10 / New Edge

### Additional Information 补充信息

No changes have been made to template

**Comment by unklnik** [comment]
OK, just want to add that this is not a BUG as such (just didn't know where to put it) just wanted to point out that there does seem to be an issue with indexing. HOWEVER, this relates to server load (not a bug in the template) though I am thinking (this might be wrong) that is might relate to the DOM elements causing excessive load on the server when Google Search Console attempts to index at certain times of the day.

**Comment by HEIGE-PCloud** [comment]
If you have long articles, or complicated SVG graphs, or maths equations and etc, you will have a large DOM - it just means you have a lot of content on your webpage. That said, the Hostload exceed error is reported when Google decided that your server's capacity (estimated by Google) is not enough for its crawler, which is unlikely to be the case for static websites generated by Hugo. So the solution might be "try again" or "contact Google for more information".

**Comment by unklnik** [comment]
OK thanks understand
