### ISSUE TITLE
[FEATURE] Ability to disable image linking by default

### ISSUE THREAD

**Issue by DimmKirr** [HEIGE-PCloud/DoIt#1098]
### Describe the feature you want 描述你的功能需求

Hello, this is more of a support question.

Is there a way to use Github-style markdown image `![](image.jpg)` withut producing an `<a href="image.jpg"></a> container?`
My images are just screenshots and they don't require a link.

I understand this is to a `linked=true` defauilt behavior, but I'm not sure how to disable it so it's disabled for the GH-style markdown.

Thanks!

**Comment by DimmKirr** [comment]
I made a fix to allow this. https://github.com/HEIGE-PCloud/DoIt/pull/1099 Please review when you can

**Comment by HEIGE-PCloud** [comment]
Fixed in https://github.com/HEIGE-PCloud/DoIt/commit/9e7d09945b898ebbea83f9149af91643082a953c
