### ISSUE TITLE
[BUG] 默认样式设置无效

### ISSUE THREAD

**Issue by HonorKnight8** [HEIGE-PCloud/DoIt#110]
defaultTheme = "dark"

我想把默认样式设置成“暗色”，无效

**Comment by HEIGE-PCloud** [comment]
修好了，请更新至最新的 commit。

**Comment by HonorKnight8** [comment]
本地 hugo server 好了。
但执行 hugo 命令，把public文件夹发布到服务器后，`<select class="color-theme-select" id="theme-select-desktop" title="切换主题">`这个标签变成一直显示的；
而且切换不了

**Comment by HEIGE-PCloud** [comment]
尝试 shift + F5 刷新一下？在 https://hugodoit.pages.dev/ 上也存在这个问题吗？

**Comment by HonorKnight8** [comment]
还真是 Shift + F5 就解决了，我去面壁
