### ISSUE TITLE
[BUG] 404 page does not respect the current language

### ISSUE THREAD

**Issue by wu0407** [HEIGE-PCloud/DoIt#1114]
### Describe the bug 描述你遇到的错误

I built the Chinese and English website, The main website is in Chinese, but there is also an English version available.
The 404 page display chinese in English site.

### Expected behavior 期待的行为

display English 404 page

### Screenshots 屏幕截图

![image](https://github.com/HEIGE-PCloud/DoIt/assets/7602218/5b422002-d12b-43c5-8c4e-d7ebc2b1d1d0)

### Build Environment 构建环境

os windows 10  and hugo v0.117

**Comment by HEIGE-PCloud** [comment]
<img width="1505" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/52968553/26b34cf6-4d8f-415e-a692-363ca70c03d5">

I'm not sure what's the reason behind this but I didn't manage to reproduce it...

**Comment by wu0407** [comment]
The report situation running on hugo server is unexpect  while server by `hugo -d` is normal

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
Maybe you need to choose the right lang in nav?

**Comment by jmooring** [comment]
<https://github.com/gohugoio/hugo/issues/11777#issuecomment-1837840608>
