### ISSUE TITLE
[BUG] Cloudflare 的 Web Analytics 的功能的js加载出错

### ISSUE THREAD

**Issue by selcarpa** [HEIGE-PCloud/DoIt#1121]
### Describe the bug 描述你遇到的错误

token被错误转义

### Screenshots 屏幕截图

![image](https://github.com/HEIGE-PCloud/DoIt/assets/25505798/b0d538a5-d4b3-427d-a9e0-157acddc7269)

### Build Environment 构建环境

```shell
sel@sot ~> hugo version
hugo v0.121.0-e321c3502aa8e80a7a7c951359339a985f082757+extended linux/amd64 BuildDate=2023-12-05T15:22:31Z VendorInfo=snap:0.121.0
```

**Comment by HEIGE-PCloud** [comment]
<img width="1512" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/52968553/f7880397-758b-4d8d-a770-9b736faabd20">

It's just the Chrome DevTool doing some weird escaping when dealing with single quotes. The generated HTML is corrected and Analytics data is sent correctly. Can verify that by reading the value using JavaScript and checking the actual POST request.

<img width="462" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/52968553/a75837c0-5a05-470e-b208-03bb3eeef20e">
