### ISSUE TITLE
[BUG] 搜索页面的a标签宽度为0，无法点击到

### ISSUE THREAD

**Issue by cold-bin** [HEIGE-PCloud/DoIt#1149]
### Screenshots 屏幕截图

![image](https://github.com/HEIGE-PCloud/DoIt/assets/85239590/6baae062-f9f3-48e4-8f76-98bae4b40d6c)

**Comment by cold-bin** [comment]
![image](https://github.com/HEIGE-PCloud/DoIt/assets/85239590/9d562502-143d-449b-856a-1eb42c775fb8)
好像a没有把span包进去

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
safari 17.2.1 
firefox 121.0
chromium 116.0.5797.0
无法复现

<img width="1600" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/70063177/819f5ee6-50d9-44b0-8282-83dff028d759">

<img width="1512" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/70063177/0a823f57-25a6-4c6e-948c-0a3e3d5b9595">

<img width="1290" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/70063177/1267aff9-e089-4eb2-a5de-f8098d2bd245">
