### ISSUE TITLE
[BUG] Some problem...

### ISSUE THREAD

**Issue by Yuxin61** [HEIGE-PCloud/DoIt#1154]
### Describe the bug 描述你遇到的错误

`i18n`下的文档中似乎应该添加`[authors]`参数，否则`作者`页显示不太正确，如下：
![2024-01-07 21-19-39屏幕截图](https://github.com/HEIGE-PCloud/DoIt/assets/34358935/7ef5df82-a932-431c-a8d6-9557b3a0a067)

### Expected behavior 期待的行为

添加之后：
![2024-01-07 21-19-08屏幕截图](https://github.com/HEIGE-PCloud/DoIt/assets/34358935/caeea6f3-8378-4a38-8a0f-1219dec79e9b)
![2024-01-07 21-19-19屏幕截图](https://github.com/HEIGE-PCloud/DoIt/assets/34358935/dbc43b9c-7f4a-48ae-9944-9bf97bd41770)
可以正常显示：
![2024-01-07 21-19-57屏幕截图](https://github.com/HEIGE-PCloud/DoIt/assets/34358935/ed5e5445-ead2-47f8-8672-b821256670fa)

### Build Environment 构建环境

- OS: Ubuntu 20.04
- Theme version: 0.4.0
- Hugo version: v0.121.2-6d5b44305eaa9d0a157946492a6f319da38de154+extended

**Comment by CXwudi** [comment]
官方demo看起来没有问题
https://hugodoit.pages.dev/zh-cn/authors/
https://hugodoit.pages.dev/authors/

**Comment by Yuxin61** [comment]
应该是没有在content目录下添加authors的索引文件，添加之后应该是会从这个文件中获取title的值拼接到“所有”的后面。
<img src="https://github.com/HEIGE-PCloud/DoIt/assets/34358935/b0def7ef-ef11-4c85-9c51-72a26593f944" width="25%">
之前是看其他的选项都有这个默认值，所以也以为需要添加`[authors]`:joy:
