### ISSUE TITLE
[BUG] Error with markup in example sites and github actions to pages

### ISSUE THREAD

**Issue by viquitorreis** [HEIGE-PCloud/DoIt#1161]
### Describe the bug 描述你遇到的错误

Im trying to fix an issue in my personal blog, but nothing seems to work. Github actions keeps failing because of markup in exampleSites folder. The file markup seems to be correct, but github actions (jekyll) still fails for some reason im not aware of.

Rendering Liquid: land/themes/DoIt/exampleSite/content/posts/theme-documentation-extended-shortcodes/index.en.md github-pages 228 | Error: Liquid syntax error (line 26): Variable '{{</* style "text-align:right; strong{color:#00b1ff;}' was not properly terminated with regexp: /\}\}/ 

### Expected behavior 期待的行为

Pass github actions with no problems

### Screenshots 屏幕截图

![image](https://github.com/HEIGE-PCloud/DoIt/assets/106786194/2d294915-e9e1-4298-8aaa-302a4bbfa9a5)

### Build Environment 构建环境

Github actions for pages, linux

### Preview Environment 预览环境

Linux

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
No offense, but have I misunderstood?
This is a hugo theme, it's weird that you got errors from jekyll, please provide a minimum reproduction or relevant reproduction steps for further investigation.

**Comment by HEIGE-PCloud** [comment]
See https://github.com/HEIGE-PCloud/DoIt/blob/main/.github/workflows/pages.yml as an example for GitHub Pages deployment.
