### ISSUE TITLE
[BUG] site.webmanifest not applied

### ISSUE THREAD

**Issue by sam-samson** [HEIGE-PCloud/DoIt#1162]
### Describe the bug 描述你遇到的错误

Great theme! I have a problem though:

When I add a `site.webmanifest` file to my `/static` folder (based on [3.2 Favicons, Browserconfig, Manifest](https://hugodoit.pages.dev/theme-documentation-basics/)), the settings aren't applied. The content of the file (taken from the [example site](https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/static/site.webmanifest)):

    {
        "name": "DoIt Theme Documentation",
        "short_name": "DoIt Docs",
        "description": "The documentation site for Hugo DoIt Theme",
        "start_url": "/",
        "theme_color": "#03fc30",
        "background_color": "#03fc30",
        "orientation": "portrait",
        "display": "standalone"
    }
   

### Expected behavior 期待的行为

My expectation would be that everything is green, but it isn't. 

### Build Environment 构建环境

hugo v0.121.2

### Additional Information 补充信息

I also tried using a `browserconfig.xml` file, but it isn't applied either.

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
Is the file available in your output directory?

**Comment by sam-samson** [comment]
I was testing with `hugo server` (I don't think there is an output directory for that?). When I built it with `hugo` and then deploy, `site.webmanifest` is placed in the root directory (but also not applied).

**Comment by sam-samson** [comment]
Sorry, I think I misunderstood what this file is about. I thought the theme uses it & applies it to the CSS itself. But it just copies it to the web root, right? So that it is applied by android devices? In that case, this issue can be closed. Thanks for the quick response!

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
> But it just copies it to the web root, right?

yes
