### ISSUE TITLE
[BUG]  Image deformity in chrome v121

### ISSUE THREAD

**Issue by wu0407** [HEIGE-PCloud/DoIt#1165]
### Describe the bug 描述你遇到的错误

The image deformity in the logo and Avatars and the image is very small on the article page.

### Screenshots 屏幕截图

![image](https://github.com/HEIGE-PCloud/DoIt/assets/7602218/61cc9e52-1091-4b14-b7e6-7a50989009ae)

### Build Environment 构建环境

OS: windows 10 
chrome: v121.0.0
user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

### Additional Information 补充信息

[Feature: Auto Sizes for Lazy Loaded Images with Srcset](https://chromestatus.com/feature/5191555708616704)

**Comment by wu0407** [comment]
Removing `sizes="auto"` in the image content can fix this issue.

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
Can confirm.

Actually I think we can dump `srcset` property on `img` element, the implementation now seems more like a way to get prettier benckmark score, all three scales are derived from the same source.

**Comment by HEIGE-PCloud** [comment]
This really looks like a browser bug to me, the [`sizes` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#sizes) should not concern the aspect ratio...

> Actually I think we can dump `srcset` property on `img` element, the implementation now seems more like a way to get prettier benckmark score, all three scales are derived from the same source.

It's not currently used apart from the [image shortcode](https://hugodoit.pages.dev/theme-documentation-extended-shortcodes/#image), which allows manually specifing different image sizes. It's possible to transform large images into various smaller sizes automatically to optimise loading for smaller devices and actually make the `srcset` useful. https://gohugo.io/content-management/image-processing/#resize

**Comment by wu0407** [comment]
https://github.com/whatwg/html/issues/10079

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
> It's not currently used apart from the [image shortcode](https://hugodoit.pages.dev/theme-documentation-extended-shortcodes/#image), which allows manually specifing different image sizes. It's possible to transform large images into various smaller sizes automatically to optimise loading for smaller devices and actually make the `srcset` useful. https://gohugo.io/content-management/image-processing/#resize

Will try to implement this weekend, overall with `getRemoteImages` it is quite achievable.
