### ISSUE TITLE
[FEATURE] Don't cache remote image link when cacheRemoteImages is enabled 

### ISSUE THREAD

**Issue by wu0407** [HEIGE-PCloud/DoIt#1168]
### Describe the feature you want 描述你的功能需求

The image link in markdown and cacheRemoteImages is enabled,  The image for the link to be cached.
for examples:
```
[xxx](https://en.wikipedia.org/wiki/Netfilter#/media/File:Netfilter-packet-flow.svg)
```
Beacuse not only https://github.com/HEIGE-PCloud/DoIt/blob/main/layouts/_default/_markup/render-image.html  call  "function/resource.html" but also https://github.com/HEIGE-PCloud/DoIt/blob/main/layouts/_default/_markup/render-link.html#L7  also call "function/resource.html"
https://github.com/HEIGE-PCloud/DoIt/blob/main/layouts/partials/function/getRemoteImage.html

**Comment by wu0407** [comment]
@Sped0n

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
Yeah discovered it yesterday during development.

I have refactored it(isolate image resources fetching pipeline) in the srcset branch, will push it tonight.
