### ISSUE TITLE
[FEATURE]  Site.Author is deprecated in hugo v0.120

### ISSUE THREAD

**Issue by wu0407** [HEIGE-PCloud/DoIt#1169]
### Describe the feature you want 描述你的功能需求

Need to replace `.Site.Author` to `params.author`

```
WARN  The author key in site configuration is deprecated. Use params.author.email instead.
WARN  The author key in site configuration is deprecated. Use params.author.name instead.
```

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
Perhaps it's time to bump up the minimum version requirement.

**Comment by HEIGE-PCloud** [comment]
I don't know what happened, but this warning went away in the lastest Hugo builds. Is it still something we need to worry about?

https://github.com/HEIGE-PCloud/DoIt/actions/runs/8276195933/job/22644346903
