### ISSUE TITLE
[BUG] featured images path was not rendered properly on windows browsers

### ISSUE THREAD

**Issue by wey-gu** [HEIGE-PCloud/DoIt#117]
### Describe the bug 描述你遇到的错误

It's found on windows (firefox, edge) that the featured images on the home page suffered from 404.
It worked well on macOS for all browsers, thus this issue seemed to exist for a long time.
Am I doing it wrong? or something wrong in lazy load part or?

### Expected behavior 期待的行为
Browser should display this picture from `alt` rather than `data-src`, while it seemed to go for `data-src` only and 404 encouterred :(
```html
<a href="/nebula-operator-kind/" aria-label=Nebula&#32;Operator&#32;Kind，一键单机玩转&#32;Nebula&#32;K8s&#32;集群><img
        class="lazyload"
        data-src="featured-image.webp"
        data-srcset="/nebula-operator-kind/featured-image.webp, featured-image.webp 1.5x, /nebula-operator-kind/featured-image.webp 2x"
        data-sizes="auto"
        alt="/nebula-operator-kind/featured-image.webp"
        title="无需依赖，一键安装尝鲜基于 Nebula Operator 的 K8s Nebula Graph Cluster" height="auto" width="auto"
    />
```
I am not expert in the frontend, not sure if the wrong behavior I found is the root cause :-p

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/1651790/123203032-4b8d8880-d4e8-11eb-89c7-464a28584059.png)

### Build Environment 构建环境

- OS: [macOS]
- Theme version/commit: b4855efc13163ec0f55426e211d0c25d538295bd
- Hugo version: "v0.83.1+extended darwin/arm64 BuildDate=unknown"

### Preview Environment 预览环境

- OS: [Windows 10]
- Browser [Edge, Firefox]

### Additional Information 补充信息

Can be checked from siwei.io in a windows machine.

post head in `index.md`
```markdown
---
...
featuredImage: "featured-image.webp"
featuredImagePreview: "featured-image.webp"
---
```

**Comment by wey-gu** [comment]
update: tried manually changed lazysizes js to 5.3.1, issue still observed :-)

**Comment by HEIGE-PCloud** [comment]
Try using this way to import featured image for now.
```
resources:
- name: "featured-image"
  src: "featured-image.webp"
- name: "featured-image-preview"
  src: "featured-image-preview.webp"
```
I will look into it.

**Comment by wey-gu** [comment]
> Try using this way to import featured image for now.
> 
> ```
> resources:
> - name: "featured-image"
>   src: "featured-image.webp"
> - name: "featured-image-preview"
>   src: "featured-image-preview.webp"
> ```
> 
> I will look into it.

Thank you @HEIGE-PCloud !
I switched to the `resources` now, it should be fine now!

```diff
-        data-src="featured-image.webp"
-        data-srcset="/en/nebula-chia/featured-image.webp, featured-image.webp 1.5x, /en/nebula-chia/featured-image.webp 2x"
+        data-src="/en/nebula-chia/featured-image.webp"
+        data-srcset="/en/nebula-chia/featured-image.webp, /en/nebula-chia/featured-image.webp 1.5x, /en/nebula-chia/featured-image.webp 2x"
```

**Comment by HEIGE-PCloud** [comment]
The issue is [fixed](https://hugodoit.pages.dev/). `featuredImage` and `featuredImagePreview` should work correctly.

Now all featured images on the documentation site are set by the newly fixed `featuredImage` parameters instead of the old `resources` parameters.

**Comment by wey-gu** [comment]
> The issue is [fixed](https://hugodoit.pages.dev/). `featuredImage` and `featuredImagePreview` should work correctly.
> 
> Now all featured images on the documentation site are set by the newly fixed `featuredImage` parameters instead of the old `resources` parameters.

Thanks a ton, @HEIGE-PCloud !!! You are turely amazing.

**Comment by Thanatermesis** [comment]
Mmmh, seems like I have this issue but i don't understand why, so in the exampleSite it seems to work correctly, but when I try to use it (in the same way) for my site, these **relative** paths doesn't seems to be correctly find, so things like:

``` featuredImage: "featured-image.webp"```

or:

```
resources:
- name: "featured-image"
 src: "featured-image.webp"
```

In both cases, the image that is assigned is set as "website.com/featured-image.webp", which doesn't exist, the correct path is "website.com/test1/featured-image.webp", so the location of the files are like:

```
├── content
│   └── posts
│       └── test1
│           ├── featured-image.webp
│           ├── test1.en.md
│           └── test1.es.md
```

---

Same problem with shortcodes, so like:

```
{{< image src="featured-image.webp" caption="Language Switch" height="226" width="770">}}
```
it only works as:
```
{{< image src="/posts/test1/featured-image.webp" caption="Language Switch" height="226" width="770">}}
```
which is of course not the ideal, since posts are put all the files, images, etc in the same directory, but also can conflict in multilingual websites
