### ISSUE TITLE
[FEATURE] 点击图片能看大图

### ISSUE THREAD

**Issue by HonorKnight8** [HEIGE-PCloud/DoIt#118]
- 点击图片能看大图
  大佬有空看看能不能加上这个功能，就是文章里的图片，点一下能看大图

**Comment by HEIGE-PCloud** [comment]
已经支持了

https://hugodoit.pages.dev/zh-cn/theme-documentation-extended-shortcodes/#image

使用 `image` shortcode 插入图片即可。

**Comment by HonorKnight8** [comment]
原来如此
