### ISSUE TITLE
[BUG] resources.Get获取目录失败？

### ISSUE THREAD

**Issue by zshmbbs** [HEIGE-PCloud/DoIt#1200]
### Describe the bug 描述你遇到的错误

启动的时候提示错误信息
`Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:16:8: executing "index.html" at <partial "head/seo.html" .>: error calling partial: execute of template failed: template: partials/head/seo.html:45:61: executing "partials/head/seo.html" at <partial "function/resource.html">: error calling partial: "/themes/DoIt/layouts/partials/function/resource.html:10:26": execute of template failed: template: partials/function/resource.html:10:26: executing "partials/function/resource.html" at <resources.Get>: error calling Get: dirs not supported resource types: &{0xc000f86330 0xc00100adc0}`
好像是resources.Get获取目录的时候失败，这个目录是什么？应该怎么修正一下？

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
请提供最小重现

**Comment by zshmbbs** [comment]
新安装hugo，下载DoIt放在themes目录下，设置好config.toml，然后hugo server，就提示上面的信息了。
config.toml
`baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "hugo"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"

[params]
  # DoIt 主题版本
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
`

**Comment by HEIGE-PCloud** [comment]
请问你本地安装的 Hugo 的版本是多少？可以通过

```
hugo version
```

查看。

**Comment by zshmbbs** [comment]
hugo v0.92.2+extended

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
@HEIGE-PCloud Haven't got a chance to test it yet, but I have a guess, on L44 https://github.com/HEIGE-PCloud/DoIt/blob/3ca038287ab9999a1c21e7dd1ce1323109d55d41/layouts/partials/head/seo.html#L44
we didn't test `.Site.Params.seo.image` existance like L57 https://github.com/HEIGE-PCloud/DoIt/blob/3ca038287ab9999a1c21e7dd1ce1323109d55d41/layouts/partials/head/seo.html#L57

> related: https://discourse.gohugo.io/t/get-dirs-not-supported-resource-types-when-trying-to-use-param-value/26721

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
@zshmbbs 你把`/layouts/partials/head/seo.html`换成 https://github.com/Sped0n/DoIt/blob/patch-1/layouts/partials/head/seo.html 试试

**Comment by zshmbbs** [comment]
更换了以后，好用了。谢谢！
