### ISSUE TITLE
[FEATURE] Add Support Pagefind search engines

### ISSUE THREAD

**Issue by coloraven** [HEIGE-PCloud/DoIt#1204]
### Describe the feature you want 描述你的功能需求

Doit current uses `algolia` and `fuse` as search engines. With `fuse` if the same keyword appears multiple times in the same post, that post will be listed multiple times in the search results, and the index file for `fuse` is relatively large. I tried Pagefind, and this issue does not occur. However, I am not familiar with front-end development, so I don't know how to add Pagefind to the search engines .
Currently, I can just create new HTML files in the `static` directory to use Pagefind, but there are still some problems. For example, the Doit theme places the rendered HTML directly in the public root directory, unlike Hugo's native approach of placing it in the public/post directory. As a result, Pagefind can only index all HTML files in the public directory, including directories like categories, posts, tags, and series. This leads to indexing of search keywords if they are included in categories, posts, tags, or series.
### `fuse` search result
<img src="https://github.com/HEIGE-PCloud/DoIt/assets/5030800/5e063fcf-8b6e-4dd9-974b-16bf732ef2db" alt="alt text" width="50%" height="auto">

### `Pagefind`  search result
<img src="https://github.com/HEIGE-PCloud/DoIt/assets/5030800/ac4cd020-815d-40d1-86a3-ae16443c7842" alt="alt text" width="50%" height="auto">

### Useful reference 有价值的参考
https://pagefind.app/
https://zenn.dev/k1350/articles/42c13020038d4c

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
I've looked into Pagefind before, pretty interesting. If possible, I'll give it a try after I finish my bachelor thesis.

**Comment by coloraven** [comment]
> I've looked into Pagefind before, pretty interesting. If possible, I'll give it a try after I finish my bachelor thesis.

Great, looking forward to your masterpiece.

**Comment by eallion** [comment]
Looks pretty good.

**Comment by kkbt0** [comment]
Copy themes/DoIt/layouts/posts/single.html save as layouts/posts/single.html .
And modify it like  `<article class="......." data-pagefind-body> `

This will help pagefind to limite only posts page can be indexed.

https://pagefind.app/docs/indexing/

> You can control what content on your site is indexed via tags on your HTML elements. `data-pagefind-*`

**Comment by coloraven** [comment]
@Sped0n 太巧了，我一直关注，这次上来查看，竟然发现9分钟前实现了，美滋滋啊

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
> @Sped0n 太巧了，我一直关注，这次上来查看，竟然发现9分钟前实现了，美滋滋啊

@coloraven 让老哥久等了，这段时间私事比较多，安顿下来才有空补完
