### ISSUE TITLE
[BUG] Waline is broken after updating the client to V3

### ISSUE THREAD

**Issue by CXwudi** [HEIGE-PCloud/DoIt#1205]
### Describe the bug 描述你遇到的错误

As the title suggested, the waline is broken after https://github.com/HEIGE-PCloud/DoIt/commit/3964265e37af53d08882862a0bbe33277a217336

### Expected behavior 期待的行为

The waline should show up even with V3

### Screenshots 屏幕截图

![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/5096d2db-32b6-491d-8dec-596dfd9ef349)
![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/c35020cd-f1aa-4d8c-9d16-1b86995f7219)

### Build Environment 构建环境

- OS: Debian 12 from devcontainer
- Theme: https://github.com/HEIGE-PCloud/DoIt/commit/982b0811e4a9a3b1bb7b78a63517a6459742c846
- Hugo: v0.121.2 Extend

### Preview Environment 预览环境

- OS: Windows 10 Pro
- Browser: Brave Version 1.61.104 Chromium: 120.0.6099.115

### Additional Information 补充信息

I revert back to the commit before https://github.com/HEIGE-PCloud/DoIt/commit/3964265e37af53d08882862a0bbe33277a217336 which uses the V2 version of the waline, and it works well

**Comment by CXwudi** [comment]
I am not sure if this is also related https://github.com/walinejs/waline/issues/2379, maybe it is Waline's side problem?

**Comment by HEIGE-PCloud** [comment]
I think it's related to this one

https://github.com/walinejs/waline/issues/2204

I will have to revert back to v2 for now.

**Comment by CXwudi** [comment]
I see, I'm wondering why would the ES module thing break the blog
