### ISSUE TITLE
[minor] consider promoted via themes.gohugo.io ?

### ISSUE THREAD

**Issue by wey-gu** [HEIGE-PCloud/DoIt#121]
What I did to decide which framework/theme to use was to scan all themes from the official theme catalog, for Hugo it's https://themes.gohugo.io.

Thank God I came here from Loveit's issues. I don't think everyone is as lucky as me.

Would you consider put doit on https://themes.gohugo.io?

Thanks again for the awesome work!

**Comment by HEIGE-PCloud** [comment]
I had submitted this theme to hugoThemes as part of the milestone `v0.2.11` #46 https://github.com/gohugoio/hugoThemes/issues/1011

But unfortunately, it seems that Hugo team does not have enough time and people to review or promote it. Hopefully they can review it soon……😥

**Comment by wey-gu** [comment]
> I had submitted this theme to hugoThemes as part of the milestone `v0.2.11` #46 [gohugoio/hugoThemes#1011](https://github.com/gohugoio/hugoThemes/issues/1011)
> 
> But unfortunately, it seems that Hugo team does not have enough time and people to review or promote it. Hopefully, they can review it soon……😥

Aha, got it! Pat pat Finger-crossed!

**Comment by wey-gu** [comment]
It seems that repo was replaced by https://github.com/gohugoio/hugoThemesSiteBuilder today.
@HEIGE-PCloud

**Comment by HEIGE-PCloud** [comment]
Let's see what will happen... UwU https://github.com/gohugoio/hugoThemesSiteBuilder/pull/16

**Comment by HEIGE-PCloud** [comment]
WoW! https://themes.gohugo.io/themes/doit/
