### ISSUE TITLE
[BUG] hugo giscus 评论区无法自动切换夜间模式

### ISSUE THREAD

**Issue by hzp2333** [HEIGE-PCloud/DoIt#1212]
### Describe the bug 描述你遇到的错误

使用的giscus评论区，但是切换到夜间模式时，评论区没有自动切换。

### Expected behavior 期待的行为

请问可能是哪个模块出问题呢？

### Screenshots 屏幕截图

![8e3ebce3d24162b97ea4d5e985da55b](https://github.com/HEIGE-PCloud/DoIt/assets/79459902/f6e5f03f-90c7-4aec-9904-de86e3d12658)

### Build Environment 构建环境

使用的多语言博客，
`config.toml`设置如下，直接在结尾加上的这部分。
```
[params.page.comment]
      enable = true       
[params.page.comment.giscus]   
  enable = true   
  dataRepo  = "hzp2333/Giscus"
  dataRepoId  = "*********"   
  dataCategory  = "Announcements"   
  dataCategoryId  = "******************  
  lang = ""   
  mapping = "pathname"   
  reactionsEnabled = "1"   
  emitMetadata = "0"   
  inputPosition = "bottom"   
  lazyLoading = false
  darkTheme = "dark"
  lightTheme = "light"
```

### Additional Information 补充信息

当我把`config.toml`更换为 
```
 darkTheme = "dark"
  lightTheme = "dark"
```
时，博客无论白天还是夜间模式，评论区都是深色模式。
感觉是识别深色模型部分的变量传递出问题了？

**Comment by hzp2333** [comment]
目前我的方法是删去`comment.html`的
``` 
            {{- $commentConfig = $giscus.lightTheme | default "light" | dict "lightTheme" | dict "giscus" | merge $commentConfig -}}
            {{- $commentConfig = $giscus.darkTheme | default "dark" | dict "darkTheme" | dict "giscus" | merge $commentConfig -}} 
 ```
但是中英文切换不知道怎么处理了。

**Comment by HEIGE-PCloud** [comment]
在 DoIt 自己的 exampleSite 上没法复现，请检查自己引入的其他第三方脚本是否有冲突。
