### ISSUE TITLE
[FEATURE] 增加 Series 相关页面

### ISSUE THREAD

**Issue by wafer-li** [HEIGE-PCloud/DoIt#122]
### Describe the feature you want 描述你的功能需求

增加 Taxonomy 为 Series 的相关页面。

需求逻辑：

Series 即系列，是博客中高质量文章的体系汇总，相比【分类】和【标签】，其文章质量更高。

自己的博客有系列文章的话也更容易提高博客的知名度和质量。

下面会稍微详细的描述这个需求

- Feature 1 功能需求 1
  增加一个 Series 分类，类似于 Category，但是可以通过读取 series 下的 `_index.md` 在 list 之前增加简介内容
- Feature 2 功能需求 2
  增加一个与 Categories 类似的 Series 汇总界面

### Useful reference 有价值的参考

暂时没有，但我感觉采用卡片式可能会比较好？

If available, provide useful links to fulfill the feature.
如果可以的话, 提供实现这个功能的相关参考链接.

**Comment by HEIGE-PCloud** [comment]
添加了最基本的支持 (#123)，可以在这个[网址](https://3da15806.hugodoit.pages.dev/series/)预览效果，有以下几个问题想要请教：

1. 一篇文章能否同时属于多个系列？
2. 对于首页的简介应该如何处理？
![image](https://user-images.githubusercontent.com/52968553/124358033-04726680-dc51-11eb-89a7-3711b150c220.png)
3. 对于文章中的 meta 应该如何处理？
![image](https://user-images.githubusercontent.com/52968553/124358062-210e9e80-dc51-11eb-94ef-825c57e68fcd.png)

**Comment by wafer-li** [comment]
@HEIGE-PCloud 

待我稍微思考思考，或许我可以画一个简单的原型。

ETA: 25 min（一个番茄钟）

**Comment by wafer-li** [comment]
> 添加了最基本的支持 (#123)，可以在这个[网址](https://3da15806.hugodoit.pages.dev/series/)预览效果，有以下几个问题想要请教：
> 
> 1. 一篇文章能否同时属于多个系列？
> 2. 对于首页的简介应该如何处理？
>    ![image](https://user-images.githubusercontent.com/52968553/124358033-04726680-dc51-11eb-89a7-3711b150c220.png)
> 3. 对于文章中的 meta 应该如何处理？
>    ![image](https://user-images.githubusercontent.com/52968553/124358062-210e9e80-dc51-11eb-94ef-825c57e68fcd.png)

Answers:

1. 理论上系列应该有树状的层级关系，所以如果允许同时属于多个 series 的话，这多个 series 应该满足一个关系，即他们两两之间都应该是父子或爷孙关系。但是这么一来的实现难度感觉过高了，从实践上来说也很少采用这种层级形式，因此限制其只能属于一个系列。

2 和 3 本质上是一个问题，即是否应该显示【此文章属于什么系列】

对于是否显示，答案是：Yes

而显示的文案我没有比较好的想法，目前的想法是在 category 后面增加系列的显示。

如图是 xxx included in 【Category】

可以在其后面增加 of 【Series】

Series 的 Icon 可以采用一个【Task List】这类的 Icon

其余部分不变即可。

**Comment by HEIGE-PCloud** [comment]
https://49983e25.hugodoit.pages.dev/series/test-pages/

这样的简介可以么，直接复用了`<blockquote>`的样式。

我不打算为简介添加完整的 markdown 支持，一是很麻烦，二是简介本来也不应该写的太复杂，如果真的有需要应该在系列中创建第0篇文章，并在其中做详细介绍。

**Comment by wafer-li** [comment]
> https://49983e25.hugodoit.pages.dev/series/test-pages/
> 
> 这样的简介可以么，直接复用了`<blockquote>`的样式。

可

Series 的简介应该尽量短小，过长的内容应该单独开一个 Overview 的 Post 进行描述

**Comment by HEIGE-PCloud** [comment]
https://8a110aa8.hugodoit.pages.dev/

基本上算完成了，我明天写一下文档，补一下翻译就完事了。

**Comment by wafer-li** [comment]
@HEIGE-PCloud 

辛苦了！十分感谢！

感觉产品经理也不好当 😂

发版之后就关掉 issue 吧
