### ISSUE TITLE
Refactor Font Awesome and SimpleIcons

### ISSUE THREAD

**Issue by HEIGE-PCloud** [HEIGE-PCloud/DoIt#1227]
### The issue 

DoIt makes heavy use of Font Awesome's icons. But the way we load it in is pretty slow. We are using  CSS + web font to load these icons, which means the browser needs to first download and parse the CSS file, then it finds the links to the web fonts, then go and downloads all of them before it can render any icons. To make things worse, we also download all the icons on all pages. So even on a simple webpage without any font awesome icons, the user still needs to pay this heavy performance penalty. 

<img width="1431" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/52968553/1b80e101-79d4-4d2a-99eb-c1bd52fdefcf">

The files are pretty large as well. On documentation site's homepage, all the icons take up more than 30% of the total download size.

### The proposal

A better plan is to inline all the icons as SVGs right inside of the HTML, so users only download what's actually get displayed. Repeated icons will get gzipped, so they won't take up extra bandwidth.

For the most part, it should be pretty straightforward to implement. We can download and commit all the raw svg files into the repository (we are already doing this for SimpleIcons). Then use https://gohugo.io/functions/os/readfile/ to read them in as needed during build.

> Potential breaking change: I am not sure how to handle https://hugodoit.pages.dev/theme-documentation-content/#fontawesome I would rather replace this with a shortcode, but this will cause a huge breaking change.

## SimpleIcons

SimpleIcons are used as SVGs files, but they are loaded inside `theme.js` using fetch calls. 

https://github.com/HEIGE-PCloud/DoIt/blob/bc2dc96d4ea7d0dc1e7238dd89e978c8f2b8653a/assets/js/theme.js#L48-L64

Ideally, this should be moved to build time as well. https://github.com/HEIGE-PCloud/DoIt/blob/bc2dc96d4ea7d0dc1e7238dd89e978c8f2b8653a/layouts/partials/plugin/icon.html

**Comment by eallion** [comment]
It's really great.

**Comment by HEIGE-PCloud** [comment]
https://pagespeed.web.dev/analysis/https-pages-hugodoit-com/sc03psd1s7

100/100
