### ISSUE TITLE
[BUG] Build failed on Hugo v0.124.1

### ISSUE THREAD

**Issue by CXwudi** [HEIGE-PCloud/DoIt#1232]
### Describe the bug 描述你遇到的错误

A build failure is spot upon running `hugo server -D`

``` log
Watching for changes in /workspace/personal-blog/{archetypes,assets,content,data,static,themes}
Watching for config changes in /workspace/personal-blog/config/_default
Start building sites … 
hugo v0.124.1-db083b05f16c945fec04f745f0ca8640560cf1ec+extended linux/amd64 BuildDate=2024-03-20T11:40:10Z VendorInfo=gohugoio

WARN  Current environment is "development". The "comment system", "PWA", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "PWA", "CDN" 和 "fingerprint" 不会启用.
ERROR Inline fontawesome icons are deprecated. Remove params.page.fontawesome and audit all usage of :( fa icons ): on your site. Use the fa-icon shortcode instead. See https://hugodoit.pages.dev/theme-documentation-extended-shortcodes/#fa-icon
Built in 185 ms
Error: error building site: logged 1 error(s)
```

### Expected behavior 期待的行为

Build should not failed

### Build Environment 构建环境

- OS: Debian 12 from devcontainer
- Theme: https://github.com/HEIGE-PCloud/DoIt/commit/ea7dc16f031fb4069c88fcf4c34f3c344b89843a
- Hugo: v0.124.1 Extend

### Preview Environment 预览环境

- OS: Windows 10 Pro
- Browser: Brave Version 1.64.113 Chromium: 123.0.6312.86

### Additional Information 补充信息

Not sure if this is related https://github.com/HEIGE-PCloud/DoIt/issues/1227, as the build was successful a few days ago. I suspect that a commit pushed recently may have triggered that deprecation.

**Comment by CXwudi** [comment]
Oh, wait, it looks like the deprecation is written by you...

Let me investigate more before re-opening the issue

**Comment by CXwudi** [comment]
Lol for anyone encountering this deprecation, simply set `fontawesome = false` in `[params.page]`.

If you are using the `params.toml` file, it is in `[page]`

**Comment by HEIGE-PCloud** [comment]
> Lol for anyone encountering this deprecation, simply set `fontawesome = false` in `[params.page]`.
> 
> If you are using the `params.toml` file, it is in `[page]`

It’s safe to remove this option completely.

Also do check whether you are actually using this syntax :( fa icon ): Migrate to the fa-icon shortcode if needed.
