### ISSUE TITLE
Echart shortcode rendering issue

### ISSUE THREAD

**Issue by digitaltwinz** [HEIGE-PCloud/DoIt#1234]
I'm attempting to integrate the Echarts JSON shortcode into my publication, but I've encountered an issue where the chart section remains empty on the rendered webpage. Upon inspecting the page in Firefox, I noticed that the Echart JS library files are not being loaded in the browser. After spending almost an entire day consulting with ChatGPT to resolve this issue, I have to post it here.

To troubleshoot, I followed the Echart examples provided on their [demo site](https://hugodoit.pages.dev/theme-documentation-extended-shortcodes/#echarts). Additionally, I've disabled ad blockers and security headers, disabled JS minification everywhere, synced the "assets" folders, but the chart area still appears blank.

**Update:** the issue turned out to be the publication date: the chart **is not visible** if I use "2024-03-15" or "2023-03-15". However, it **is visible** if I use "2020-03-15" or "2022-03-15". Could anyone provide assistance in resolving this?

**Comment by HEIGE-PCloud** [comment]
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Comment by digitaltwinz** [comment]
It is easily reproducible, please just change the publication year from 2020 to 2024 for [the demo page](https://hugodoit.pages.dev/theme-documentation-extended-shortcodes/#echarts)

**Comment by HEIGE-PCloud** [comment]
<img width="899" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/52968553/343a221a-06ec-48cc-8632-b6c315ca2589">

I don't know... See #1235

**Comment by digitaltwinz** [comment]
Thanks for checking it! It seems I should check a date handling in the config.
