### ISSUE TITLE
[FEATURE] Series Display 

### ISSUE THREAD

**Issue by kkbt0** [HEIGE-PCloud/DoIt#1252]
### series display

When the series directory is in widescreen, it is displayed above the TOC directory or on the left side of the page.

### Useful reference 有价值的参考

like this https://canstand.github.io/compost/posts/shortcodes/

**Comment by HEIGE-PCloud** [comment]
Maybe we can put it on the left to mimic certain "documentation"-like themes like https://hugo-book-demo.netlify.app/docs/example/table-of-contents/with-toc/

<img width="1512" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/52968553/cf26b7ab-bc35-44d6-8095-faa514c8d6b4">

**Comment by kkbt0** [comment]
看起来很赞 
great : )

**Comment by CXwudi** [comment]
> Maybe we can put it on the left to mimic certain "documentation"-like themes like [hugo-book-demo.netlify.app/docs/example/table-of-contents/with-toc](https://hugo-book-demo.netlify.app/docs/example/table-of-contents/with-toc/)
> 
> <img alt="image" width="1512" src="https://private-user-images.githubusercontent.com/52968553/324228643-cf26b7ab-bc35-44d6-8095-faa514c8d6b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwOTcyMzMsIm5iZiI6MTcxNDA5NjkzMywicGF0aCI6Ii81Mjk2ODU1My8zMjQyMjg2NDMtY2YyNmI3YWItYmMzNS00NGQ2LTgwOTUtZmFhNTE0YzhkNmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAyMDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjN2I3NDgwNWY3MDMzNmRkMGVjNjU1MTdjNTNlYzU1YTgwZDc3NTU5YTA2NTlkNGVhYzYxZWQxNzlmMzlhYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XdJaiEzv5jljjN02qz1yy_8dQFQpVJA6iTSzjPBX9aw">

Uh, it looks more like yet another menu to me, instead of a series. But I am fine with either way.

**Comment by HEIGE-PCloud** [comment]
> Maybe we can put it on the left to mimic certain "documentation"-like themes like https://hugo-book-demo.netlify.app/docs/example/table-of-contents/with-toc/
> 
> <img alt="image" width="1512" src="https://private-user-images.githubusercontent.com/52968553/324228643-cf26b7ab-bc35-44d6-8095-faa514c8d6b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NjA5ODcsIm5iZiI6MTcxNTQ2MDY4NywicGF0aCI6Ii81Mjk2ODU1My8zMjQyMjg2NDMtY2YyNmI3YWItYmMzNS00NGQ2LTgwOTUtZmFhNTE0YzhkNmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDIwNTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MmJlMTZlZmEzZjZmMjc4MzU2YjIzODc0NTQ3MDNhZGFmY2Y0NTE3ZjVmNmJmOWNjMmI4NTNhNmYzNWU5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4R1p84iI05k-yzzs5ZdQtL6Mr1P6X2DDcB901yDGk4g">

I am not quite satisfied with this one either. I think we need a better design before proceeing.

**Comment by HEIGE-PCloud** [comment]
Not planned for now
