### ISSUE TITLE
[FEATURE] 文章排序 **sort**

### ISSUE THREAD

**Issue by al6nlee** [HEIGE-PCloud/DoIt#1258]
### Describe the feature you want 描述你的功能需求

<img width="1548" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/89306357/25758336-5843-4b99-82f5-fa17d9714ba0">

I want to sort the articles under the category by publication time, but I want to sort them by article title.

<img width="736" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/89306357/efbeb7be-d0a8-40b2-853c-5499265f0ee9">

I have also tried to modify the weight of the article to sort it, but it cannot change the sequence in the category, only the sequence of the article on the homepage.

**Comment by HEIGE-PCloud** [comment]
Edit: I think you will have to either fix the creation date for your posts or switch to using `series` and `series_weight` for sorting here. `categories` seems to always group by dates.

---

~Use `categories_weight`~

~https://gohugo.io/content-management/taxonomies/#example-taxonomic-weight~

~By the way, DoIt also supports `series` for grouping content, comparing to `categories`, it adds this extra navigation menu at the top of each post, which might be useful for your content.~

<img width="857" alt="image" src="https://github.com/HEIGE-PCloud/DoIt/assets/52968553/accff5d8-9634-43a8-b758-904aa51ea502">

**Comment by al6nlee** [comment]
ok，Perhaps it is possible to sort articles by controlling the series and series_weight.

**Comment by al6nlee** [comment]
![image](https://github.com/HEIGE-PCloud/DoIt/assets/89306357/1f23fafe-c070-4924-a710-d54ad7d92f32)
sucessfully, thanks~~
