### ISSUE TITLE
[BUG] Multiple Line Block Math Formula is not rendered

### ISSUE THREAD

**Issue by wafer-li** [HEIGE-PCloud/DoIt#126]
### Describe the bug 描述你遇到的错误

I have a KaTex formula as follows:

```
$$
\begin{aligned}
2 \times Area(a, b, c) =
\begin{vmatrix}
a_x & a_y & 1\\
b_x & b_y & 1\\
c_x & c_y & 1\\
\end{vmatrix}
= \\
\begin{vmatrix}
b_x - a_x & b_y - a_y \\
c_x - a_x & c_y - a_y \\
\end{vmatrix}
\end{aligned}
$$
```

It should be rendered as the screenshot shows, but it didn't, just stay the same.

### Expected behavior 期待的行为

It should be rendered as the screenshot shows.

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/12459199/124378453-f3bf0080-dce3-11eb-8b5c-f770080eab13.png)

### Build Environment 构建环境

- OS: Manjaro
- Theme version/commit b3dc66e
- Hugo version hugo v0.83.1-5AFE0A57+extended linux/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

### Preview Environment 预览环境

- OS: Manjaro
- Browser Firefox

### Additional Information 补充信息

Configuration files or front matter code...
配置文件或者前置参数的代码...

Just the same as the theme docs.

**Comment by HEIGE-PCloud** [comment]
There are some small adjustments need to be made to the KaTeX formulae for it to compatible with the Markdown parser.

1. All `\\` need to be entered as `\\\\` to escape the `\` symbol
2. There must be a space at the end of the line for which ends in `\\\\`

So, for your example, the formulae need to be changed into

```latex
$$
\begin{aligned}
2 \times Area(a, b, c) =
\begin{vmatrix}
a_x & a_y & 1\\\\ 
b_x & b_y & 1\\\\ 
c_x & c_y & 1\\\\ 
\end{vmatrix}
= \\\\ 
\begin{vmatrix}
b_x - a_x & b_y - a_y \\\\ 
c_x - a_x & c_y - a_y \\\\ 
\end{vmatrix}
\end{aligned}
$$
```
for it to work correctly.

![image](https://user-images.githubusercontent.com/52968553/124378748-b491af00-dce5-11eb-806c-d951bbbba378.png)

**Comment by wafer-li** [comment]
Thanks, I will make such adjustments.

Closing it.

**Comment by HEIGE-PCloud** [comment]
https://discourse.gohugo.io/t/use-goldmark-mathjax-extension/25721/20

There has been quite a lot of discussion around this issue. I will keep an eye on it if there is any updates from Hugo (quite unlikely) :(.

**Comment by HEIGE-PCloud** [comment]
I have added a `math` shortcode to solve this issue.

You no longer need to escape special characters inside a `math` shortcode.

https://hugodoit.pages.dev/theme-documentation-extended-shortcodes/#14-math
