### ISSUE TITLE
[BUG] scroll bar in the default style is blocking the code block in Windows 10

### ISSUE THREAD

**Issue by CXwudi** [HEIGE-PCloud/DoIt#1260]
### Describe the bug 描述你遇到的错误

Since https://github.com/HEIGE-PCloud/DoIt/commit/6d8755d309527a84c76dd1dadcfe1fb10d943ed7, the scroll bar in default style in Windows 10 is actually blocking the lower part of the code block. 
![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/73f4e5db-2031-49f6-8026-e1c428a303fd)

Before the code block reworking from https://github.com/HEIGE-PCloud/DoIt/pull/1225, this was rendered as:
![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/a81a4a50-0eeb-49a0-889a-7e97e91cb252)

### Expected behavior 期待的行为

Maybe the CSS needs to be adjusted to reserve some space for the scroll bar, and the amount of space should automatically be correctly determined by the rendering engine (so that no matter how thick is the scroll bar in the default style, the engine should always get it right.)

### Screenshots 屏幕截图

See above

### Build Environment 构建环境

- OS: Debian 12 from devcontainer
- Theme: 693e8f5cfc2215648232cb84c79f24a7ccc33aad
- Hugo: v0.124.1 Extend

### Preview Environment 预览环境

- OS: Windows 10 Pro
- Browser: Brave Version 1.64.113 Chromium: 123.0.6312.86

### Additional Information 补充信息

I guess it is just a small bug from 6d8755d309527a84c76dd1dadcfe1fb10d943ed7

**Comment by HEIGE-PCloud** [comment]
I removed the old style because on macOS, you get a nice overlay scrollbar that does not shift the layout and hides automatically by default. Also `::-webkit-scrollbar` is non-standard and does not work on Firefox anyway.

I don't have a Windows device right now, can you test whether https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter would help?

**Comment by CXwudi** [comment]
Unfortunately, `scrollbar-gutter: stable;` doesn't really work well. I personally prefer `scrollbar-width: thin;`, but not sure how it looks like on macOS.

This is what `scrollbar-width: thin;` looks like in Windows Chrome:
![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/71019530-979e-439b-9769-54b0263c39eb)

This is without (current state):
![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/c3735722-53f7-4b55-89de-bb703ac2a471)

This is `scrollbar-gutter: stable;`, pretty much no changes:
![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/e898bbfb-b5d2-42c5-9695-6d57490bb515)

I also noticed that there are quite a lot of tailwind CSS, maybe should we try https://www.npmjs.com/package/tailwind-scrollbar

**Comment by kkbt0** [comment]
Another interesting thing about the offset caused by the scrollbar is that the scrollbar causes the head bar position to change. This can be seen when switching pages. Because 100% is not equal to 100vw when there is a scrollbar.
GitHub also has this phenomenon.

**Comment by HEIGE-PCloud** [comment]
`scrollbar-width: thin;` seems to be a reasonable solution. In the worst case scenario we can always just add some `margin-bottom` to the code element. 

There is some effort called "fluent scrollbar" to bring an overlay scrollbar to Chrome and Edge on Windows. https://issues.chromium.org/issues/40213017 but there isn't much progress and activity recently.

**Comment by HEIGE-PCloud** [comment]
> Another interesting thing about the offset caused by the scrollbar is that the scrollbar causes the head bar position to change. This can be seen when switching pages. Because 100% is not equal to 100vw when there is a scrollbar. GitHub also has this phenomenon.

That's one of the reasons why I switched to the native scrollbar, because on macOS, you get an overlay scrollbar https://developer.chrome.com/docs/css-ui/scrollbar-styling#:~:text=Overlay%20scrollbars%20are%20floating%20scrollbars,the%20operating%20system%20to%20decide. that does not eat into the layout and thus avoid problems like this. But apparently it's not easy to get an overlay scrollbar on Windows.

**Comment by CXwudi** [comment]
Apparently, for Windows machines, there are some experimental flags in Chrome based browser where you can enable the macOS-liked scrollbar behaviour
![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/6fecc567-8d8d-493f-83cf-0de57e881d03)

This video shows the fluent scrollbar: https://www.youtube.com/watch?v=GdCNvcTu5ZA
![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/32eeaa6b-2bdb-4895-b9ec-ced8812c6d4e)

And this one shows an overlay scrollbar (with fluent scrollbar): https://www.youtube.com/watch?v=3EFHqmHcxhM
![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/d363faac-6b36-449c-a7e3-03b7c063805e)
![image](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/db463405-4a95-4d2e-9d43-95a526b47232)
