### ISSUE TITLE
[BUG] Header logo is cut on the sides

### ISSUE THREAD

**Issue by flobernd** [HEIGE-PCloud/DoIt#1289]
### Describe the bug 描述你遇到的错误

When using a `svg` logo in the header, it gets cut on the sides.

DoIt:
![186-166-max](https://github.com/HEIGE-PCloud/DoIt/assets/8585557/374da0c1-7c71-42a8-80a6-8524a8fc4d89)

### Expected behavior 期待的行为

The logo is displayed correctly.

LoveIt:
![171-139-max](https://github.com/HEIGE-PCloud/DoIt/assets/8585557/3481c428-4675-43f0-9fd2-f34ba6a0f197)

Bonus:
It would probably look nicer, if the logo is vertically aligned to the middle of the header text. Currently it's aligned on the bottom boundary it seems:
![185-181-max](https://github.com/HEIGE-PCloud/DoIt/assets/8585557/e6ed5daa-92fb-4c24-b214-6b475f85f9c0)

Comparing with the alignment of the menu items, it seems like the header text is positioned correctly, but the logo size is simply too large (36px).

### Screenshots 屏幕截图

DoIt:
![186-166-max](https://github.com/HEIGE-PCloud/DoIt/assets/8585557/374da0c1-7c71-42a8-80a6-8524a8fc4d89)

LoveIt:
![171-139-max](https://github.com/HEIGE-PCloud/DoIt/assets/8585557/3481c428-4675-43f0-9fd2-f34ba6a0f197)

### Build Environment 构建环境

- hugo v0.125.1-68c5ad638c2072969e47262926b912e80fd71a77+extended linux/amd64 on Docker
- latest DoIt commit

### Preview Environment 预览环境

Firefox on Windows 11

**Comment by HEIGE-PCloud** [comment]
The logo image is restricted to be a square to avoid layout shift

https://github.com/HEIGE-PCloud/DoIt/blob/0a0b127ebfe518f0fdd63d553ae14798bb94f27d/layouts/partials/header.html#L8

Do you think it's better remove this restriction or use the capability to insert the image as raw HTML in this case?

https://github.com/HEIGE-PCloud/DoIt/blob/0a0b127ebfe518f0fdd63d553ae14798bb94f27d/exampleSite/config/_default/params.toml#L56

**Comment by flobernd** [comment]
The logo actually is quadratic and defines `width="64" height="64"` in the source:
![logo](https://github.com/HEIGE-PCloud/DoIt/assets/8585557/b8593c10-774c-4c94-841a-b9ec5922eee6)

If I remove the size hint, the logo is no longer truncated at the left side, but still on the right:
![151-147-max](https://github.com/HEIGE-PCloud/DoIt/assets/8585557/a5a3c0d1-e842-4ddb-bb49-c7e723a1d2e6)

For me it looks like the header text positioning is the actual problem and not the logo. In this screenshot you can see how the header text overlaps the logo:
![3486-222-max](https://github.com/HEIGE-PCloud/DoIt/assets/8585557/70990b3d-1ed8-4dbf-9a26-92d552036459)

You can as well see, that the header text (and the menu) is not fully centered on the vertical axis.

**Comment by flobernd** [comment]
Hi @HEIGE-PCloud, thanks for trying to fix this 🙂 

Sadly, it looks like this now (64x64px in the svg code):
![214-176-max](https://github.com/HEIGE-PCloud/DoIt/assets/8585557/bc24205f-4236-4adb-b01d-8a255fb83186)

Without `width` and `height` specified in the svg:
![183-170-max](https://github.com/HEIGE-PCloud/DoIt/assets/8585557/7b6041f8-5c57-4fb8-a016-6c37a698bc7e)

**Comment by HEIGE-PCloud** [comment]
Try 36x36 or inlining the svg directly.

https://github.com/HEIGE-PCloud/DoIt/blob/cfdf56e712943a920ada598485613cbe601b58fd/exampleSite/config/_default/params.toml#L56

**Comment by HEIGE-PCloud** [comment]
Ok it should now definitely be fixed. Sorry I missed your logo's svg file previously.

**Comment by flobernd** [comment]
Thanks a lot! I can confirm that the latest fix solves the issue 🙂 I left a minor comment on the commit: https://github.com/HEIGE-PCloud/DoIt/commit/de76eff5a0757f000d8fe540b55aa5b7c0186c5b#r142794099

Not sure if this would have unwanted side-effects, but in my particular case it seems to further improve the result.
