### ISSUE TITLE
[FEATURE] Skill and experience timeline widget add

### ISSUE THREAD

**Issue by tonyho** [HEIGE-PCloud/DoIt#1290]
### Describe the feature you want 描述你的功能需求

Can you add the similiar function like this [theme](https://themes.gohugo.io/themes/toha/), so users can add they skills and experience timeline to make the blog post as an resume.

**Comment by HEIGE-PCloud** [comment]
I am not particularly interested in this one, but PR is always welcome~

**Comment by HEIGE-PCloud** [comment]
I am closing this issue for now as not planned. We can reopen it if there are more interests in this area.
