### ISSUE TITLE
[BUG] 文件名、目录名或卷标语法不正确。

### ISSUE THREAD

**Issue by bwcxyk** [HEIGE-PCloud/DoIt#1300]
### Describe the bug 描述你遇到的错误

`git submodule update --remote --merge`后
```
Error: error building site: "E:\hugo\blog\content\posts\Jenkins权限控制.md:1:1": "E:\hugo\blog\themes\DoIt\layouts\_default\_markup\render-image.html:16:166": execute of template failed: template: _default/_markup/render-image.html:16:166: executing "_default/_markup/render-image.html" at <partial "plugin/image.html">: error calling partial: "E:\hugo\blog\themes\DoIt\layouts\partials\plugin\image.html:27:59": execute of template failed: template: partials/plugin/image.html:27:59: executing "partials/plugin/image.html" at <resources.Get>: error calling Get: CreateFile E:\hugo\blog\assets\https:\img.bwcxtech.com\img\20200928161231.jpeg: The filename, directory name, or volume label syntax is incorrect.
```
为什么出现 E:\blog\assets\https ，我的图片不在本地。

### Screenshots 屏幕截图

![image](https://github.com/HEIGE-PCloud/DoIt/assets/28802427/a28cebf7-c3ed-489d-94c4-da4da6bafaa0)

**Comment by HEIGE-PCloud** [comment]
请问是否启用了 `cacheRemote = true`？能否提供具体的图片引用源码 `[](what/is/the/path/here?.png)`

**Comment by HEIGE-PCloud** [comment]
Hugo 的问题，详情请看 https://github.com/gohugoio/hugo/issues/10736

**Comment by bwcxyk** [comment]
好像没有人修复

**Comment by HEIGE-PCloud** [comment]
能否帮忙测试一下 https://github.com/HEIGE-PCloud/DoIt/pull/1302 是否能解决这个问题？

**Comment by bwcxyk** [comment]
> 能否帮忙测试一下 #1302 是否能解决这个问题？

测试过正常
![image](https://github.com/HEIGE-PCloud/DoIt/assets/28802427/5d867e82-bd8b-45fe-889e-f97970b4a424)
