### ISSUE TITLE
[BUG] img height error

### ISSUE THREAD

**Issue by kkbt0** [HEIGE-PCloud/DoIt#1303]
### Describe the bug 描述你遇到的错误

img height error

https://hugodoit.pages.dev/basic-markdown-syntax/#images 

The Stormtroopocat image height error.  
Some markdown images may not be fully displayed

### Screenshots 屏幕截图

![Snipaste_2024-06-21_11-30-46](https://github.com/HEIGE-PCloud/DoIt/assets/55222315/c4e1d196-7a56-48c5-9e5e-dcbe84b20ccb)
![Snipaste_2024-06-21_11-30-37](https://github.com/HEIGE-PCloud/DoIt/assets/55222315/9e271814-7714-456a-9203-dcda8ccfabfa)

**Comment by HEIGE-PCloud** [comment]
Yep, the good old sizes=auto issue. Should have never done that.
