### ISSUE TITLE
[BUG] Tags with '#' are not displayed correctly

### ISSUE THREAD

**Issue by flobernd** [HEIGE-PCloud/DoIt#1307]
### Describe the bug 描述你遇到的错误

I tried to use `C#` as a tag for a post.

Frontmatter:

```yaml
tags:
  - 'C#'
  - '.NET'
  - Patterns
```

On the "tags" page, everything works fine, but on content itself, the tag is missing in the footer:

![371-242-max](https://github.com/HEIGE-PCloud/DoIt/assets/8585557/652973db-87e8-4820-aa88-7c29e23e0ad5)

The problem exists regardless of enclosing the tag in `'` or not. It seems like the `#` character is triggering this behavior.

**Comment by HEIGE-PCloud** [comment]
It failed here 

https://github.com/HEIGE-PCloud/DoIt/blob/ff904e9aae3bca25b464bb4e8de80da39ff1da3a/layouts/posts/single.html#L58

the url needs to be escaped before passing to `urlize`.

I don't know what's the reason behind it, but the taxonomy handling code looks really ugly.

To fix it, change that line to

```
{{- $category := partialCached "function/path.html" (urlquery .) (urlquery .) | printf "/categories/%v" | $.Site.GetPage -}}
```

but I am inclined to refactor the section entirely.

**Comment by flobernd** [comment]
Thanks for the fast reply! I'll happily wait for the refactoring 🙂 Its probably not the most important bug anyways.

**Comment by HEIGE-PCloud** [comment]
Turned out the refactoring is non-trivial. I've pushed a fix for this, the refactoring can be tracked and implemented separately.

Ref: https://discourse.gohugo.io/t/how-to-get-permalink-of-taxonomies-in-templates/12927

**Comment by flobernd** [comment]
Thank you @HEIGE-PCloud !
