### ISSUE TITLE
[BUG] Series中包含空格，post-meta里面会无法渲染出文字

### ISSUE THREAD

**Issue by Christ9038** [HEIGE-PCloud/DoIt#1323]
### Describe the bug 描述你遇到的错误

我在文章顶部series中填入series = ["0基础Stable Diffusion入门"]，首页和详情页的系列后面就只剩图标，没有文字，a标签里也没有链接，系列的页面中是正常的。当我修改为series = ["0基础StableDiffusion入门"]后，首页和详情页都可以正常显示，a标签也有链接了。

### Expected behavior 期待的行为

字符串可以正常使用空格

### Screenshots 屏幕截图

有空格时：
<img width="559" alt="截屏2024-07-29 00 20 10" src="https://github.com/user-attachments/assets/b7121d0a-cc2c-49d6-bb99-17b24c9022f2">

没有空格时：
<img width="572" alt="截屏2024-07-29 00 21 13" src="https://github.com/user-attachments/assets/64bad540-01e1-4764-866b-7b3e6d252352">

有空格时再series页面下可以显示：
<img width="316" alt="截屏2024-07-29 00 27 30" src="https://github.com/user-attachments/assets/a12668e8-7e67-42f5-a51e-08ddc6b9f512">

### Build Environment 构建环境

hugo v0.129.0+extended darwin/arm64 BuildDate=2024-07-17T13:29:16Z VendorInfo=brew
Doit 2024年7月17日版本 main分支版本

**Comment by CXwudi** [comment]
现阶段最好的workaround是设置`content/series`, 可以参考exampleSite里的设置. https://github.com/HEIGE-PCloud/DoIt/tree/main/exampleSite/content/series

其实同时我也建议设置`content/series`, `content/categories`甚至是`content/tags`以保证最好的consistency

**Comment by HEIGE-PCloud** [comment]
https://github.com/gohugoio/hugo/issues/5687

Hugo 的老问题了 CXwudi 的回复是正解。
