### ISSUE TITLE
[FEATURE] Make a list of posts on a "all posts" page look similar to recent posts on the home page

### ISSUE THREAD

**Issue by cyrmax** [HEIGE-PCloud/DoIt#1337]
### Describe the feature you want 描述你的功能需求

Hello!
My friend recommended your Hugo theme as an awesome alternative to the old one I've been using for several years.
Your theme is cool and I love this plenty of configuration options to customize everything.
But the only problem is that I didn't found an ability to make the "all posts" page to present posts list in the same way I see it on the home page.
I expected to see a title as a heading (it is convenient for accessibility users), an author, publish date and a summary along with "read" link.
But while on the home page I see this nice thing, on the "all posts" page I see only headings with year numbers and links with posts titles along with publish date near them. No headings for every post, no author signature, no summary which is the biggest problem.

If this can be switched with some config option then please tell me, because I didn't found anything in documentation.
If this cannot be done at all and you don't plan to implement such a thing then sorry for disturbing you. Probably I'd fork your theme and implement this (or at least try to implement).
But if this is something acceptable as a new feature I would be glad to see it implemented in future (probably as a config option to not break existing design for all depending sites).

**Comment by HEIGE-PCloud** [comment]
Maybe I didn’t understand you correctly, but if you want the “all posts” page to display all the information on the home page, then what is stopping you from getting these information from the home page directly instead? The home page also lists all posts.
