### ISSUE TITLE
Control reading time

### ISSUE THREAD

**Issue by al6nlee** [HEIGE-PCloud/DoIt#1342]
### Describe the feature you want 描述你的功能需求

![image](https://github.com/user-attachments/assets/4c7d8e9f-d82e-4c4c-8d29-d671098197c6)
Perhaps we can add a parameter to configure the reading speed, which would be slightly more reasonable.
Maybe it's my problem. I searched for a long time but couldn't find the configuration.

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
https://gohugo.io/methods/page/readingtime/
