### ISSUE TITLE
Separation of Chapters and Sections

### ISSUE THREAD

**Issue by al6nlee** [HEIGE-PCloud/DoIt#1344]
### Describe the feature you want 描述你的功能需求

<img width="913" alt="image" src="https://github.com/user-attachments/assets/e9a41feb-c02e-4d53-83f4-a05261ec5d90">

<img width="246" alt="image" src="https://github.com/user-attachments/assets/ce4443af-1f75-43d3-8c3b-08ded8645f63">

Is there any configuration that can implement the concept of chapter directory? For example, Figure 1 shows the current configuration of DOIT themes, which can only be 1, 2, 3; I want to implement the concept of chapters in Figure 2.

**Comment by HEIGE-PCloud** [comment]
I don’t quite understand. You can just change the title of each post yourself right?

**Comment by al6nlee** [comment]
> I don’t quite understand. You can just change the title of each post yourself right?

OK，What I mean is chapter separation. For example, there are three summaries under the first chapter, and their directory structure is shown in the following diagram.But now the title arrangement is only one level.
<img width="296" alt="image" src="https://github.com/user-attachments/assets/e7ca7be7-118a-4e9a-a7b3-2473c34b9104">

**Comment by CXwudi** [comment]
It sounds to me that you are trying to make a menu using the Series function. I wouldn't say it is a proper usage of Series, because AFAIK a series is a sequence of posts that together describe something (e.g. [the documentation series](https://hugodoit.pages.dev/series/getting-start/) in the demo page). 

For your case, it would be better to create a separate post that just list all your chapters and sections in Markdown. And link the post to [the top level menu](https://github.com/HEIGE-PCloud/DoIt/blob/a78bd703fdfd456ae4515640d4633c23128f974b/exampleSite/config/_default/menu.en.toml#L50) like the showcase menu in the demo page

**Comment by al6nlee** [comment]
> It sounds to me that you are trying to make a menu using the Series function. I wouldn't say it is a proper usage of Series, because AFAIK a series is a sequence of posts that together describe something (e.g. [the documentation series](https://hugodoit.pages.dev/series/getting-start/) in the demo page).
> 
> For your case, it would be better to create a separate post that just list all your chapters and sections in Markdown. And link the post to [the top level menu](https://github.com/HEIGE-PCloud/DoIt/blob/a78bd703fdfd456ae4515640d4633c23128f974b/exampleSite/config/_default/menu.en.toml#L50) like the showcase menu in the demo page

Okay, I understand what you mean. However, whether using series or categories to arrange a bunch of articles, I am not very satisfied and lack a sense of hierarchy. The main reason why I am selecting series now is because there is a parameter called series_weight that can be used for sorting.

**Comment by HEIGE-PCloud** [comment]
I am not very keen on this because it seems to be a very niche use case, but it’s rather easy to slap a `series_indent` property or something on it with some CSS and it should work.

> As a side note, I am rather happy that this theme is in a state where new feature requests are all small nit picks.

**Comment by al6nlee** [comment]
> I am not very keen on this because it seems to be a very niche use case, but it’s rather easy to slap a `series_indent` property or something on it with some CSS and it should work.
> 
> > As a side note, I am rather happy that this theme is in a state where new feature requests are all small nit picks.

Fine
