### ISSUE TITLE
[BUG] tags with spaces aren't displayed

### ISSUE THREAD

**Issue by rivit98** [HEIGE-PCloud/DoIt#1362]
### Describe the bug 描述你遇到的错误

tags with spaces aren't displayed

### Expected behavior 期待的行为

tags with spaces are displayed

### Screenshots 屏幕截图

![image](https://github.com/user-attachments/assets/9906ae3e-49a7-4421-a399-15af3ac45364)

### Build Environment 构建环境

Commit: 0f6c6632

**Comment by HEIGE-PCloud** [comment]
https://github.com/HEIGE-PCloud/DoIt/issues/1307

This is an ongoing annoying problem.

Basically `urlize` does not escape special characters properly, and `urlquery` escapes stuff incorrectly.

**Comment by CXwudi** [comment]
Possibly, You could work around this by using a dedicated tag entry in https://github.com/HEIGE-PCloud/DoIt/tree/main/exampleSite/content/tags, see also my comment in https://github.com/HEIGE-PCloud/DoIt/discussions/1395

Not sure if it works

**Comment by HEIGE-PCloud** [comment]
> Possibly, You could work around this by using a dedicated tag entry in https://github.com/HEIGE-PCloud/DoIt/tree/main/exampleSite/content/tags, see also my comment in #1395
> 
> Not sure if it works

Ah I forgot about this, this should be the way to go. It works.
