### ISSUE TITLE
用了最新版感觉 summary 的样式有点问题.

### ISSUE THREAD

**Issue by xiaobinqt** [HEIGE-PCloud/DoIt#1368]
### Screenshots 屏幕截图

![image](https://github.com/user-attachments/assets/d8f300c8-6219-4439-9820-863f6b20180b)

![image](https://github.com/user-attachments/assets/1cce6f4f-d37b-43ab-a3fa-236eb676dea2)

**Comment by xiaobinqt** [comment]
之前摘要中的包含富文本块元素好像不会渲染，改成自动渲染的有点奇怪，能不能加个参数控制下？是否渲染摘要中的富文本是可控的。

![image](https://github.com/user-attachments/assets/f2c062ad-c4b3-4769-995f-690da302aee3)

**Comment by HEIGE-PCloud** [comment]
之前摘要中的富文本也是会被渲染的，这个行为是从 LoveIt 中继承的

https://github.com/HEIGE-PCloud/DoIt/blame/19edafd14a6978569bffb33321e5cb07183c045d/layouts/_default/summary.html#L76

与此同时，仍然不建议在摘要内容中包含富文本元素。这会导致渲染错误。
