### ISSUE TITLE
[FEATURE] Render Markdown in admonition shortcode

### ISSUE THREAD

**Issue by lgatellier** [HEIGE-PCloud/DoIt#1372]
### Describe the feature you want 描述你的功能需求

Hi,

Thanks for maintaining this theme, I've just migrated from LoveIt, and it was really straightforward :clap: 

Should it be possible to support rendering Markdown inside **admonition** shortcode ?

I'd like to add links, but they are not rendered, since `.Page.RenderString` is used instead of `markdownify`.

Thanks !

**Comment by CXwudi** [comment]
Not sure if this is duplicated https://github.com/HEIGE-PCloud/DoIt/issues/885. Basically, the native markdown format should be supported, but nested shortcodes are not supported.

**Comment by HEIGE-PCloud** [comment]
```md
{{< admonition >}}
[GitHub](https://github.com)
{{< /admonition >}}
```

<img width="871" alt="image" src="https://github.com/user-attachments/assets/ba914d0b-897e-4370-8e7a-b568bfb62372">

This works just fine for me.

---

By the way `.Page.RenderString` does render markdown https://gohugo.io/methods/page/renderstring/
