### ISSUE TITLE
[BUG] The social info config is error

### ISSUE THREAD

**Issue by mulberyn** [HEIGE-PCloud/DoIt#1373]
### Describe the bug 描述你遇到的错误

I config my blog according to the docs in https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/, but my blog cannot show the social info in the localhost.
After checking the errors, I found the params in \themes\DoIt\layouts\partials\home\profile.html line 53 and line 57 is different. fix this error, the info can be shown.

### Expected behavior 期待的行为

make the params the same, and update the theme-documentation-basics docs

### Screenshots 屏幕截图

![3](https://github.com/user-attachments/assets/ecad2093-ef62-4a33-94cf-56b4f3b5c73a)
$profile is params.home.profile
![2](https://github.com/user-attachments/assets/36783369-bc9d-4135-adfd-73c9e423834e)
so the $profile.social and the .Site.Params.social is different
![image](https://github.com/user-attachments/assets/b333f6e3-b116-4899-baf3-2accf37ee5fe)
correct above params to the same like ".Site.Params.social"
In this way the config docs theme-documentation-basics can be still useful

### Build Environment 构建环境

- OS: win11
- Theme version: 0.4.X
- Hugo version: hugo-extended v0.136.4

**Comment by mulberyyn** [comment]
maybe I am wrong, sorry.

**Comment by HEIGE-PCloud** [comment]
I am curious what's the conclusion for this? Is there a problem after all?

**Comment by mulberyyn** [comment]
> I am curious what's the conclusion for this? Is there a problem after all?

The question above is non-exist, I apologize for disturbing you.

But I found that in the mobile mode, the display location of search-clear icon is not at correct location, is it a true problem?

![image](https://github.com/user-attachments/assets/e32c14de-9016-4da3-836f-7232a46a0053)

**Comment by HEIGE-PCloud** [comment]
Created a new issue for tracking this
