### ISSUE TITLE
[BUG] Error building site after updating 

### ISSUE THREAD

**Issue by veronicageek** [HEIGE-PCloud/DoIt#1376]
### Describe the bug 描述你遇到的错误

I've updated to Hugo `v.0.136.5` and updated the DoIt theme to the latest. 
I had to also update some parts of the theme to `hugo.IsMultilingual`. When trying to build the site by running `hugo`, I get the following error:

`Error: error building site: render: failed to render pages: render of "page" failed: "{USERNAME}\{FOLDER}\{MY-REPO}\layouts\_default\baseof.html:57:8": execute of template failed: template: _default/single.html:57:8: executing "_default/single.html" at <partial "assets.html" .>: error calling partial: "C:\Users\{USERNAME}\{FOLDER}\{MY-REPO}\layouts\partials\assets.html:207:25": execute of template failed: template: partials/assets.html:207:25: executing "partials/assets.html" at <"lib/pjax/pjax.min.js.map">: **nil pointer evaluating resource.Resource.RelPermalink**`

I'm unable to deploy using Github Actions because of the Multilingual issue, and when I change the values, I get the error above.

### Expected behavior 期待的行为

The site builds correctly.

### Build Environment 构建环境

- Windows 11
- DoIt `v.0.4.0`
- Hugo `v.0.136.5`

**Comment by HEIGE-PCloud** [comment]
Are you sure you're on the latest commit for DoIt? I believe I addressed the `hugo.IsMultilingual` issue awhile ago https://github.com/HEIGE-PCloud/DoIt/commit/38df51c80f2214ff990eeed1f37d2e3fe15a5a8a

And the example site builds and deploys just fine https://github.com/HEIGE-PCloud/DoIt/actions/runs/11535798363/job/32111250697

**Comment by veronicageek** [comment]
Yes I'm on the latest.

I think I've tried everything so far and still got the same result:
- Different versions of `hugo` (from `0.89` to `0.122`, `0.123` and back to the latest `0.136.5`)
- Cloned again my repo
- Run `git submodule init` then `git submodule update --remote --merge`

First it's complaining about the `IsMultiLingual` in my files (with the "L" capital - which is normal as it's still "pre-update" to the latest `hugo`), so I change the files accordingly with lowercase (`IsMultilingual`).

And then that's when the error happens, and simply cannot get it to work no matter the version of `hugo` or the theme.

**Comment by veronicageek** [comment]
Didn't solve my problem, but closing this as I decided to move away from Hugo and GH Pages.
