### ISSUE TITLE
[BUG] lightgallery not work on homepage

### ISSUE THREAD

**Issue by wu0407** [HEIGE-PCloud/DoIt#1381]
### Describe the bug 描述你遇到的错误

If the summary contains an image that is unable browse use lightgallery.

### Screenshots 屏幕截图

![image](https://github.com/user-attachments/assets/7a469b54-d518-4e71-89a6-4204e491e928)
![image](https://github.com/user-attachments/assets/bc446fff-16fd-46c0-9359-ff8c49839f75)
![image](https://github.com/user-attachments/assets/464d3041-727f-43ea-a9bf-1facf98b140b)

### Build Environment 构建环境

hugo: v0.137.0

**Comment by wu0407** [comment]
solution 1:
```
      --document.getElementById("content"),
      ++document.getElementsByClassName("content"),
```

https://github.com/HEIGE-PCloud/DoIt/blob/324b48d09c0855b8fae02d74f063362874f5e75c/assets/js/theme.ts#L586-L590


solution 2:
```
---<div class="content"> 
++<div class="content" id="content"> 
```
https://github.com/HEIGE-PCloud/DoIt/blob/324b48d09c0855b8fae02d74f063362874f5e75c/layouts/_default/summary.html#L74

**Comment by HEIGE-PCloud** [comment]
I think that's expected? The images on the homepage serve as hyperlinks to the articles, so adding light gallery there will conflict with the link.

**Comment by wu0407** [comment]
> I think that's expected? The images on the homepage serve as hyperlinks to the articles, so adding light gallery there will conflict with the link.

That image is not a featured image, it is the only image on the page. It links to image self not to the article.

**Comment by HEIGE-PCloud** [comment]
Ah I misunderstood you. Sounds like another feature creep into the summary #1368

**Comment by HEIGE-PCloud** [comment]
People disagree on this for a long time, some think summary should not have any styles at all, some others want their articles to be fully rendered in the summary. I think this is again one of these cases and I don't have a good opinion here.

**Comment by HEIGE-PCloud** [comment]
The current state is "The basic markdown stuff works", so headings, lists and tables will be rendered with the right style, but anything involving fancy JavaScripts probably does not work.
