### ISSUE TITLE
[FEATURE] load lightgallery js on demand

### ISSUE THREAD

**Issue by wu0407** [HEIGE-PCloud/DoIt#1382]
### Describe the feature you want 描述你的功能需求

The lightgallery resource is large, so need to optimize loading speed.
It is very difficult to determine whether there is an image in the summary of the homepage on the render.
But It is easy to determine whether there is an image on the article page.
There are many pits about `Scracth`  `Store` and render cache on the Hugo server. https://discourse.gohugo.io/t/strange-behavior-with-scratch-variable/52288/11?u=xiao_qing

So The best method is to load it on demand from the front end.

**Comment by HEIGE-PCloud** [comment]
I think the easiest fix is to just mark these scripts as deferred

https://github.com/HEIGE-PCloud/DoIt/blob/e68974c47e4bcf086c6a0dbff153352e71fcfd16/layouts/partials/assets.html#L56-L60
