### ISSUE TITLE
[疑问] 为什么自定义样式无效呢

### ISSUE THREAD

**Issue by sugarlesss** [HEIGE-PCloud/DoIt#139]
### Describe the bug 描述你遇到的错误
我修改了 themes\DoIt\assets\css\_custom.scss ，但是不生效

一段简短的对于你遇到的错误的描述.
我将  themes\DoIt\assets\css\_custom.scss 内容修改为下面的代码，我想尝试调整一下行间距，但是发现无效。
```
.single {
    .content {
        p {
            margin: 1.5rem 0;
        }
    }
}
````

是我哪里操作不对吗？在试错过程中，我也尝试在根目录下新建了一个 assets\css\_custom.scss 文件，写入了相同的样式，但是依然无效。文档我看过了，但是没有看明白是什么意思。

**Comment by HEIGE-PCloud** [comment]
请在 `<your_site>/assets/css/` 文件夹下创建 `_custom.scss` 来应用自定义样式。

相关文档： https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#33-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F

**Comment by sugarlesss** [comment]
是的，我应该是按照你说的新建了文件，但还是不行，我目前不太清楚问题在哪里。
[![WVXsUI.md.png](https://z3.ax1x.com/2021/07/14/WVXsUI.md.png)](https://imgtu.com/i/WVXsUI)

**Comment by HEIGE-PCloud** [comment]
是否使用了 extended 版本的 Hugo？

使用 `hugo version` 命令来查询当前的 Hugo 版本。

**Comment by sugarlesss** [comment]
非常感谢！我更换成 extend 版本 hugo 后就可以了！阿里嘎多
