### ISSUE TITLE
[BUG] Search: URL is "undefined" for search results 

### ISSUE THREAD

**Issue by srikanthsubra** [HEIGE-PCloud/DoIt#1392]
### Describe the bug 描述你遇到的错误

I have tried both algolia and fuse search options.

The URL for the search results shows up as "undefined". Clicking on a result, takes me to <baseURL>/undefined.

index.json has a "url" attribute for each record.

Please investigate.

### Expected behavior 期待的行为

The correct relative URL should be included in the search result hyperlinks.

### Build Environment 构建环境

hugo version  
hugo v0.136.4+extended darwin/arm64 BuildDate=2024-10-22T08:35:58Z VendorInfo=brew

**Comment by srikanthsubra** [comment]
I figured out the issue. Will post an update in due course.

**Comment by HEIGE-PCloud** [comment]
I am glad you figured something out. I didn't manage to reproduce this and I have no idea what happened.

**Comment by HEIGE-PCloud** [comment]
Close as stale
