### ISSUE TITLE
[FEATURE] 当目录为空时，不渲染目录或隐藏目录 When the Contents is empty, do not render the Contents or hide the Contents

### ISSUE THREAD

**Issue by KinShin** [HEIGE-PCloud/DoIt#1396]
### Describe the feature you want 描述你的功能需求

When the `## title`  is not used to organize the article structure in the post, the content of the table of contents is blank, but the generated page will still have the words `<h2 class="toc-title">Contents</h2>`.

当 post 中未通过 `## 标题` 来组织文章结构时，目录内容为空白，但是生成的页面中还是会有 `<h2 class="toc-title">目录</h2>` 字样。

It is hoped that the word "Contents" will not be displayed when the contents is empty to make the blog look more concise.

希望当目录内容为空时不显示“目录”字样，以使博客看上去更加简洁。

**Comment by HEIGE-PCloud** [comment]
Add 

```
toc:
  enable: false
```

to the front matter to turn toc off for individual posts.
