### ISSUE TITLE
Here~

### ISSUE THREAD

**Issue by SpongeBab** [HEIGE-PCloud/DoIt#14]
Hello，初来乍到，这是第一次接受别人邀请o.o,要在这里沟通一下吗：）

**Comment by HEIGE-PCloud** [comment]
好耶！目前短期的工作有这几个

#5 是一个简单调整分割线的CSS样式的工作
#2 是为主题颜色切换添加下拉菜单的工作

这是一些比较基础的问题，刚好可以通过它们来上手一下这个主题。

当然如果你想添加新的功能，或者提交新的bug，直接提issue就可以了！

如果想认领某个issue，点击issue右边的Assignees并添加自己。

![image](https://user-images.githubusercontent.com/52968553/115956544-46668a00-a4f5-11eb-99c6-dabb182fc284.png)

然后创建一个新的branch，就可以在上面提交自己的commit啦

等开发完成之后，创建一个新的pull request，等review通过之后就可以merge到主分支啦~

**Comment by SpongeBab** [comment]
我刚尝试使用了一下这个主题，遇到了一些问题，尝试了一些方法，也没有解决。
这是完整的输出，我运行`hugo server`

```
(base) xiaopeng@xiaopeng-HP-Z800-Workstation:~/Hugo/hugo-blog$ hugo server
port 1313 already in use, attempting to use an available port
Start building sites … 
ERROR 2021/04/24 19:24:47 Configuration Error 配置文件错误

You haven't configured the LoveIt version param correctly yet. See https://hugoloveit.com/theme-documentation-basics/#basic-configuration
你还没有正确配置 LoveIt 的版本参数. 参考 https://hugoloveit.com/zh-cn/theme-documentation-basics/#basic-configuration

WARN 2021/04/24 19:24:47 

Current environment is "development". The "comment system", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "CDN" 和 "fingerprint" 不会启用.

Built in 38 ms
Error: Error building site: TOCSS: failed to transform "css/style.scss" (text/x-scss). Check your Hugo installation; you need the extended version to build SCSS/SASS.
```
我确信我没有别的错误，因为我使用了hugo-papermod主题，并且成功了。

是否我需要先下载LoveIt主题，才能使用这个主题？
如果这样，我觉得我们首先需要实现独立安装，因为原仓库好像已经停止维护了。
如果需要做些别的操作才能使用，我觉得先得写一份完备的READ.md，哈哈。
以上
