### ISSUE TITLE
[FEATURE] DoIt 支持百度统计吗

### ISSUE THREAD

**Issue by sugarlesss** [HEIGE-PCloud/DoIt#140]
### Describe the feature you want 描述你的功能需求

DoIt 支持百度统计吗

**Comment by HEIGE-PCloud** [comment]
DoIt 支持 Google Analytics 和 Fathom Analytics，不支持百度统计，也不打算对百度统计添加支持。

你可以自行修改 `DoIt\layouts\partials\plugin\analytics.html` 配置百度统计。
