### ISSUE TITLE
[BUG] code block expanding/collapsing won't work well in non-first Shortcode tabs/tab.

### ISSUE THREAD

**Issue by lvliangxiong** [HEIGE-PCloud/DoIt#1406]
### Describe the bug 描述你遇到的错误

When render md file with following content:

```
{{< tabs >}}

{{% tab title="index.js" %}}

first tab code block

{{% /tab %}}


{{% tab title="index.js" %}}

second tab code block

{{% /tab %}}

```
, second tab code block expanding/collapsing won't work well when click the title bar.

But if you turn on/off the code wrap button once, the expanding/collapsing function becomes normal.

Look like `chroma.style.maxHeight = chroma.scrollHeight + 10 + "px";` in theme.ts:896 failed to get scrollHeight for code blocks in other tabs. So it's limited to 10px.

![20241219-134509](https://github.com/user-attachments/assets/0bb5d23f-7845-42ee-b9a4-bb71742980d3)

### Expected behavior 期待的行为

Code block expand/collapse normally.

### Build Environment 构建环境

- macos intel 15.2 (24C101)
- hugo v0.139.4+extended+withdeploy darwin/amd64 BuildDate=2024-12-09T17:45:23Z VendorInfo=brew
- theme version: "0.4.X" latest commit

### Preview Environment 预览环境

- macos intel 15.2 (24C101)
- chrome Version 131.0.6778.140 (Official Build) (x86_64)

**Comment by HEIGE-PCloud** [comment]
Yeah this is a good old CSS problem for these kind of animations.

I think Chrome has a new feature that solves this easily, but it’s not available on Firefox or Safari https://developer.chrome.com/docs/css-ui/animate-to-height-auto

**Comment by lvliangxiong** [comment]
> Yeah this is a good old CSS problem for these kind of animations.
> 
> I think Chrome has a new feature that solves this easily, but it’s not available on Firefox or Safari https://developer.chrome.com/docs/css-ui/animate-to-height-auto

I'm not familiar with css though.
So you prefer adopting a new way to implement code block expand/collapse just like the doc you mentioned, instead of fix the reason which leads to zero scrollHeight? Any chance we can fix it with a small mod?

**Comment by HEIGE-PCloud** [comment]
> I'm not familiar with css though. So you prefer adopting a new way to implement code block expand/collapse just like the doc you mentioned, instead of fix the reason which leads to zero scrollHeight? Any chance we can fix it with a small mod?

I am happy to learn more about the solution you have in mind. I don't see a small mod fixing this.

**Comment by HEIGE-PCloud** [comment]
I figure `interpolate-size` is a rather small mod, though unfortunately some browsers do not support it https://github.com/HEIGE-PCloud/DoIt/pull/1407
https://do-it-git-fix-code-block-pclouds-projects.vercel.app/tab-tests/#tabs-with-codeblock

**Comment by lvliangxiong** [comment]
> > I'm not familiar with css though. So you prefer adopting a new way to implement code block expand/collapse just like the doc you mentioned, instead of fix the reason which leads to zero scrollHeight? Any chance we can fix it with a small mod?
> 
> I am happy to learn more about the solution you have in mind. I don't see a small mod fixing this.

I just comment out theme.ts:896 and theme.ts:920 on my local device testing, code block behaves normal. But I wonder wheather it'll ruin something...

**Comment by CXwudi** [comment]
@lvliangxiong maybe can you bring a PR and we can test it out

**Comment by HEIGE-PCloud** [comment]
> I just comment out theme.ts:896 and theme.ts:920 on my local device testing, code block behaves normal. But I wonder wheather it'll ruin something...

It removes the expansion animation.

**Comment by lvliangxiong** [comment]
> > I just comment out theme.ts:896 and theme.ts:920 on my local device testing, code block behaves normal. But I wonder wheather it'll ruin something...
> 
> It removes the expansion animation.

ok, I just launched a quick pr for your reference. Look forward to your better solution. 🫡

**Comment by HEIGE-PCloud** [comment]
As I said, this does not quite work, the expansion animation is removed

Expected:

https://github.com/user-attachments/assets/c00611d3-e789-46b1-8b17-af97a13a40a7


Actual:


https://github.com/user-attachments/assets/8ad160a1-f30c-4c0c-a033-2ecc25f35eb0
