### ISSUE TITLE
[FEATURE] Some feature pageStyle = "wide"

### ISSUE THREAD

**Issue by MiladMohammadi72** [HEIGE-PCloud/DoIt#1411]
### Describe the feature you want 描述你的功能需求

Hi, 
I know that in release 0.4.0 you removed this great feature -> pageStyle = "wide".

You definitely had your reasons, but I don't think it's right to remove a feature because it can't be implemented properly.

Please add this feature back if you can.

thank you.

**Comment by HEIGE-PCloud** [comment]
Can you share your use case for pageStyle wide? The original reason for adding it is that the LoveIt theme leaves a lot of blank spaces on a wide screen and it might be a good idea to fill these space with content. The reason for removing it is that actually, lines too long will make an article harder to read https://kickpoint.ca/the-readability-formula-making-your-website-easy-to-read/
I think you can achieve something similar easily with some custom CSS (just change the max width of a container) so it gets removed.


I’d like to hear more about your thoughts.

**Comment by MiladMohammadi72** [comment]
thank you 
yes, hard to read, but I solved my problem with custom CSS
here is:

themes/DoIt/assets/css/_page/_index.scss

```
.page {
  position: relative; 
  width: 80%;
  margin: 0;
  padding-top: $header-height;
  padding-left: 4% !important;
  padding-right: 4% !important;
  @include blur;
}
.home{
  width: 100%;
  padding: auto !important;
  text-align: center;
  display: flex;
  flex-direction: column;
  justify-content: center;
  padding: 0px !important;

}
.special{
  margin-left: 10% !important;
}
.archive{ 
  position: relative; 
  width: 100% !important;
  margin: 0;
  padding: 3% 20% !important;
}
```
now I have a wide-screen on all the pages.

**Comment by HEIGE-PCloud** [comment]
You can place it in `your_site/assets/css/_custom.scss` and it will be applied without the need to modify DoIt directly.
