### ISSUE TITLE
[BUG] 设置 Permalinks 规则后，<site>/categories 页面中的 URL 没有变化

### ISSUE THREAD

**Issue by sugarlesss** [HEIGE-PCloud/DoIt#145]
### Describe the bug 描述你遇到的错误

一段简短的对于你遇到的错误的描述.
我将 Permalinks 设置为如下规则
```
[Permalinks]
  posts= "/:section/:slug"
```
并且开启了伪静态
```
uglyurls = true
```
但 <site>/categories 页面中的 URL 没有做出相应的改变，仍然保持原样。

但首页（ 网站根目录 ）的 URL 已经根据我的设置做出了相应改变。对此我感到很困惑，这是否是正常的行为？

我在 issue 中搜索了相关问题，但没有找到类似的回答。

**Comment by HEIGE-PCloud** [comment]
如果我没猜错的话，解决的方法是重启 `hugo server` ~
