### ISSUE TITLE
[BUG] Search box doesn't open after page transition.

### ISSUE THREAD

**Issue by falsycat** [HEIGE-PCloud/DoIt#151]
### Describe the bug 描述你遇到的错误

After page transition, clicking a search icon doesn't open search box.

### Expected behavior 期待的行为

Search box should open when I click the icon even after page transition.

### Build Environment 构建环境

- OS: Arch Linux
- Theme commit: 8048c364688cbb6527322dc86f270f56520a363f
- hugo v0.85.0+extended linux/amd64 BuildDate=unknown

### Preview Environment 预览环境

- OS: Windows10
- Vivaldi 4.0.2312.33 (Stable channel) (64-bit)

### Additional Information 补充信息

- In my preview environment, this problem happens too in [hugodoit.pages.dev](https://hugodoit.pages.dev).
- Setting `relativeURLs` and `canonifyURLs` to `true` didn't solve the issue.

Maybe it's hard to read because I speak neither Chinese nor English. Thank you.

**Comment by HEIGE-PCloud** [comment]
The issued should be fixed with the latest commit, check it out! 😀

**Comment by falsycat** [comment]
It worked! Thank you. I appreciate it.
