### ISSUE TITLE
[FEATURE] Add some features for social links and homepage

### ISSUE THREAD

**Issue by Ahmed-E-86** [HEIGE-PCloud/DoIt#152]
Thanks for this amazing theme. I have searched hundreds of Hugo themes, and your theme is one of the best.

I am in no position to ask for anything from you, you have already done a lot, but I would love if you could add these features:

Feature 1:
An alternative links to **Paypal**, and **Patreon** like: **Librepay**, and **Ko-fi**.

Feature 2:
Add **featured posts**, and **latest posts** on the right side of home page as in [hugo-clarity](https://github.com/chipzoller/hugo-clarity) theme
Featured posts can be pulled out from **frontmatter** variable `featured: true`

Feature 3:
Add the ability to pin posts to the home page
Pinned posts can be pulled out from **frontmatter** variable `pinned: true`

I am sorry if I am asking for too many features, I wish I can add them as pull requests myself, but I am totally new to Hugo.

**Comment by HEIGE-PCloud** [comment]
Hello

For Feature 1, links for Libreapay, and Ko-fi will be added soon!

For Feature 3. The post on the home page is sorted by time by default. To "Pin" a post, you can set the [`weight` front matter](https://gohugo.io/content-management/front-matter/#predefined) for the post. The [exampleSite](https://hugodoit.pages.dev) is using this method to pin this [post](https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/content/posts/theme-documentation-basics/index.en.md) on the top.

For Feature 2, I don't see a way to fit a featured post section into the design pattern of DoIt theme's homepage. As mentioned before, the posts on homepage are sorted by `weight`, then by `postDate`, so all the posts on homepage have been sorted by **featured posts** and **latest posts** already, a dedicated section does not seem to be very useful.

**Comment by Ahmed-E-86** [comment]
I tested it, and it works fine. Thanks!
