### ISSUE TITLE
[FEATURE] Add support for Vssue or Intensedebate

### ISSUE THREAD

**Issue by Ahmed-E-86** [HEIGE-PCloud/DoIt#155]
Intensedebate is a comment system made by the same company who made wordpress.com, and it is free to use, but it is proprietary. You have already added support for many comment systems, but the only one that I found similar to Intensedebate and opensource at the same time is Vssue, and it is not supported either by your theme.

### Intensedebate use a script like this:

**Top script:**

```
<script>
                var idcomments_acct = 'put account_id here';
                var idcomments_post_id;
                var idcomments_post_url;
                </script>
                <script type="text/javascript" src="https://www.intensedebate.com/js/genericLinkWrapperV2.js">
            </script>
```

**Down script:**
```
<script>
                var idcomments_acct = 'put account_id here';
                var idcomments_post_id;
                var idcomments_post_url;
                </script>
                <span id="IDCommentsPostTitle" style="display:none"></span>
                <script type='text/javascript' src='https://www.intensedebate.com/js/genericCommentWrapperV2.js'>
            </script>
```

_The **down script** is more important than the top script._

Vssue uses 5 different scripts based on which storage repo you used (GitHub, GitLab, Bitbucket, Gitea, or Gitee), so it will be better to add just one script of them.

https://vssue.js.org/guide/gitlab.html

I would be so grateful if you could support any of them.

**Comment by HEIGE-PCloud** [comment]
Please test the Vssue comment system support at #157 and tell me whether it is working correctly since I have no way testing it myself.

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/126888004-53e5929d-66f7-4993-ad94-5f179abe8943.png)

IntenseDebate does not look very well out of the box, and I don't want to rewrite its CSS. I will still add the support for it, but it is not recommended.

**Comment by Ahmed-E-86** [comment]
OMG! I did not expect to get support for both. I am so grateful. Thanks.

For whatever reason, the comments does not appear for both. I did not find any script for any comment system inside the HTML files in the public folder. I do not know what is wrong.

**Comment by HEIGE-PCloud** [comment]
Have you switched to the dev branch for testing? They have not been merged into the main branch yet.

**Comment by Ahmed-E-86** [comment]
> Have you switched to the dev branch for testing? They have not been merged into the main branch yet.

Yes, I did, and `Vssue Comment System` is inside `comment.html`

**Comment by HEIGE-PCloud** [comment]
Have you changed the settings in `config.toml`?

```toml
[params.page.comment.vssue]
    enable = false
    platform = "" # ("bitbucket", "gitea", "gitee", "github", "gitlab")
    owner = ""
    repo = ""
    clientId = ""
    clientSecret = ""
```

By default, it is disabled as I don't have an OAuth app for testing it.

**Comment by Ahmed-E-86** [comment]
Yes, I used gitlab, and I filled all the fields. There is no trace of the script of vssue, or Intensedebate in the final HTML files inside the public folder. I searched for the word `script` and I did not find any of them.

**Comment by HEIGE-PCloud** [comment]
Weird, here is what I get:

```html
          <div id="comments">
            <div id="vssue"></div><noscript>
              Please enable JavaScript to view the comments powered by <a href="https://vssue.js.org/">Vssue</a>.
            </noscript>
          </div>
```

```html
  <div class="pjax-assets">
    <script type="text/javascript" src="/lib/vue/vue.runtime.min.js"></script>
    <script type="text/javascript" src="/lib/vssue/vssue.gitlab.min.js"></script>
    <script type="text/javascript" src="/lib/lightgallery/lightgallery.min.js"></script>
    <script type="text/javascript" src="/lib/lightgallery/lg-thumbnail.min.js"></script>
    <script type="text/javascript" src="/lib/lightgallery/lg-zoom.min.js"></script>
    <script type="text/javascript" src="/lib/clipboard/clipboard.min.js"></script>
    <script type="text/javascript" src="/lib/sharer/sharer.min.js"></script>
    <script
      type="text/javascript">window.config = { "code": { "copyTitle": "Copy to clipboard", "maxShownLines": 10 }, "comment": { "vssue": { "clientId": "test", "clientSecret": "test", "el": "#vssue", "owner": "test", "repo": "test", "title": "Theme Documentation - Basics" } }, "lightGallery": { "actualSize": false, "exThumbImage": "data-thumbnail", "hideBarsDelay": 2000, "selector": ".lightgallery", "speed": 400, "thumbContHeight": 80, "thumbWidth": 80, "thumbnail": true }, "search": { "algoliaAppID": "5YGRNRQK1G", "algoliaIndex": "en_index", "algoliaSearchKey": "0ff6874805de24b84aa1d5ebccad56cd", "highlightTag": "em", "maxResultLength": 10, "noResultsFound": "No results found", "snippetLength": 30, "type": "algolia" }, "sharerjs": true };</script>
    <link rel="stylesheet" href="/lib/vssue/vssue.min.min.css">
    <link rel="stylesheet" href="/lib/lightgallery/lightgallery.min.css">
  </div>
```

What pages are you searching? On some pages (for example the homepage) there is no comment section.

**Comment by HEIGE-PCloud** [comment]
By the way `hugo server` will load the site in development mode, for which the comment will not load. Use `hugo server -e production` for local preview server.

**Comment by Ahmed-E-86** [comment]
> hugo server -e production

I am sorry, it does not make any difference. I searched the posts for the word `comments`, and that is the only result I found:

```
</a><a href="#" id="view-comments" class="fixed-button" title="View Comments">
            <i class="fas fa-comment fa-fw"></i>
```

**Comment by HEIGE-PCloud** [comment]
Have you enabled the page comment? 

```toml
[params.page.comment]
      enable = true
```

This is what I get from the exampleSite. The comment section can show up correctly, although the comments will not be loaded with my invalid keys.

![image](https://user-images.githubusercontent.com/52968553/126905486-6cb39b2e-79dc-4a64-9091-75fb4fcf3260.png)

**Comment by Ahmed-E-86** [comment]
Yes, it is enabled, I even enabled comments in the front matter of each page. I tried also to add the script manually to comment.html, and it does not work.

**Comment by Ahmed-E-86** [comment]
Intensedebate works fine from the exampleSite, but Vssue gives me errors when I try to login, but it loads fine from the exampleSite.

**Comment by Ahmed-E-86** [comment]
I had to delete the frontmatter variable `comment: true` from every markdown file inside the posts folder to get the comment section to appear as it should be. Please, add that in the documentation.

![Screenshot from 2021-07-25 22-09-36](https://user-images.githubusercontent.com/29783425/126912061-e70d6fae-892a-4d80-af96-6aaaf18d7d53.png)

![Screenshot from 2021-07-25 23-24-44](https://user-images.githubusercontent.com/29783425/126913946-47a021d5-c66c-4c95-a5a8-dcd55dcc36cc.png)

**Comment by HEIGE-PCloud** [comment]
> I had to delete the frontmatter variable `comment: true` from every markdown file inside the posts folder to get the comment section to appear as it should be. Please, add that in the documentation.

Well, this explains everything. `comment` is not a simply Boolean variable that can be set to `true` or `false`, it is a set that contains all configuration of comment settings. To enable or disable the comment for each post individually, you should change the value of `comment.enable`. So here is the correct front matter:

```
comment:
  enable: true
```

By setting `comment` to `true`, all the configurations are overrided. The theme relies on `comment.enable` to decide whether to turn on the comment section, which is now set to `underfined`, that's why nothing shows up.

**Comment by Ahmed-E-86** [comment]
OH! That was my fault, sorry about that, and thank you for your amazing support. I am so grateful.
