### ISSUE TITLE
[BUG] A minor bug

### ISSUE THREAD

**Issue by Ahmed-E-86** [HEIGE-PCloud/DoIt#156]
When using the light mode, the colors of the **unselected numbers** of the pages are barely noticeable, and the color of the circle of **back to top** is barely noticeable as well.

### A screenshot to describe the issue:

![Screenshot from 2021-07-24 16-02-42](https://user-images.githubusercontent.com/29783425/126872336-7a8ce231-597b-42c3-bfdb-51eed5b831fe.png)

**Comment by HEIGE-PCloud** [comment]
Well, to me, the design of the color for unselected numbers and the circle looks fine. It should remain unnoticeable when it is not selected. What do you want it to look like?

**Comment by Ahmed-E-86** [comment]
A little darker gray will be good for me, I do not know if it will be cool for you. If it is not, I will just keep the dark theme as the default theme.

**Comment by bugxch** [comment]
Actually i don't think it's a bug, at mostly it's a feature not completed

**Comment by HEIGE-PCloud** [comment]
I plan not to change the background color of the back-to-top button, in order to keep it consistent with the heading's color. I have changed the font color of the pagination link to `$global-font-secondary-color`, it will be more noticeable in light mode.

**Comment by Ahmed-E-86** [comment]
I do not know what is the reason, but the font color of the pagination link is still the same, I even changed it manually to black, and it didn't change at all.

**Comment by HEIGE-PCloud** [comment]
Here is what I get from this [page](https://hugodoit.pages.dev/posts/):

![image](https://user-images.githubusercontent.com/52968553/126984881-5700e52a-5724-4dcd-8fd2-86dc3f317a57.png)

**Comment by Ahmed-E-86** [comment]
> Here is what I get from this [page](https://hugodoit.pages.dev/posts/):
> 
> ![image](https://user-images.githubusercontent.com/52968553/126984881-5700e52a-5724-4dcd-8fd2-86dc3f317a57.png)

It looks the same for me, but the colors of the main page looks different on the homepage of my local website.

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/126986008-5a864f33-3582-4f93-ba62-3fd88f3693ef.png)

Here is the color on the homepage, they are controlled by the same CSS selector.

**Comment by Ahmed-E-86** [comment]
I have no idea :smile: I will just finish the website, and upload it, and see how it looks.
