### ISSUE TITLE
[BUG] Some problem...

### ISSUE THREAD

**Issue by zming** [HEIGE-PCloud/DoIt#159]
### parse failed: template: partials/head/seo.html:148: unclosed action

添加主题和配置后运行不起来

### Expected behavior 期待的行为

添加主题和拷贝配置后，运行报错

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/20045153/126893383-90de91c4-9870-404d-b645-e09295cc2887.png)

### Build Environment 构建环境

- OS: macOS
- Theme version/commit [0.2.0]
- Hugo version [v0.73.0/extended]

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

### Preview Environment 预览环境

- OS: [ macOS]
- Browser [Chrome]

### Additional Information 补充信息

配置文件如说明那样

**Comment by HEIGE-PCloud** [comment]
请更新 Hugo 至最新的 `v0.86.0` 版本。

https://github.com/gohugoio/hugo/releases/tag/v0.86.0

**Comment by zming** [comment]
升级后解决，非常感谢
