### ISSUE TITLE
[Request] change the location of social share and lastmod

### ISSUE THREAD

**Issue by Ahmed-E-86** [HEIGE-PCloud/DoIt#161]
If you do not mind, could you please change the location of social share icons, and `updated on` to be at the top of the content instead of underneath it, or tell me how can I do that.

That is my last request, and thanks for your patience.

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/126929682-dcc7fe51-2453-477f-a7db-13be73bcb630.png)

Here is the top area of a typical post, where do you want to put the lastmod and the social share?

**Comment by Ahmed-E-86** [comment]
Above the picture, so the visitors know when they look at the date that it is updated, otherwise they will leave if the date is old, and it has not been updated. Also, it is not guaranteed that the visitor will read the article to the end.

I am a little confused about the share buttons, it could fit up or down, I am not quite sure. What do you think?

**Comment by HEIGE-PCloud** [comment]
The edit date of a post has been added next to its post date.

View how it looks here: https://hugodoit.pages.dev/theme-documentation-basics/

I am not changing the location of social icons as it makes more sense for people to share a post **after** reading it.

**Comment by Ahmed-E-86** [comment]
It looks fine. Thanks.

What do you use to show the number of views?

**Comment by HEIGE-PCloud** [comment]
Some comment plugins provide view count function. To be specific, [Valine](https://valine.js.org/en/index.html), [Waline](https://waline.js.org/en/) and [Twikoo](https://twikoo.js.org) are the three comment plugins which both support by DoIt and support view count statistics.

**Comment by Ahmed-E-86** [comment]
That will be so cool to have. Thanks for your reply, you are so helpful.
