### ISSUE TITLE
[FEATURE] author: nil?

### ISSUE THREAD

**Issue by gnohz** [HEIGE-PCloud/DoIt#167]
### Describe the feature you want 描述你的功能需求

- Is it possible to disable the author?
- Another issue: I used ox-hugo to convert org file to markdown. Then I have 
`author = ["author"]`
instead of 
`author = "author"`
However, the first one gives me an error message: 
`execute of template failed: template: partials/plugin/link.html:7:16: executing "partials/plugin/link.html" at <safeHTML>: error calling safeHTML: unable to cast []string{"author"} of type []string to string`

**Comment by HEIGE-PCloud** [comment]
You can replace all `author =` into `authors =` which should solve this problem.

**Comment by gnohz** [comment]
If you mean `authors = ["xxx"]`, then it does not work...

I found a similar issue in another post:
https://github.com/kaushalmodi/ox-hugo/issues/387

**Comment by HEIGE-PCloud** [comment]
`authors = ["xxx"]` is supported by DoIt theme and it should work out of the box (even without the further configuration mentioned in the docs).

https://hugodoit.pages.dev/theme-documentation-content/#author-setup

If it does not work, can you share the error log for debugging?

**Comment by HEIGE-PCloud** [comment]
Disabling the author is not supported.

You can configure the author information in `config.toml` once and for all.

```toml
[author]
  name = "xxx"
  email = "xxx"
  link = "xxx"
```

If nothing is configured, a default `Author` will be displayed and everything will work correctly as well.

**Comment by gnohz** [comment]
> `authors = ["xxx"]` is supported by DoIt theme and it should work out of the box (even without the further configuration mentioned in the docs).
> 
> https://hugodoit.pages.dev/theme-documentation-content/#author-setup
> 
> If it does not work, can you share the error log for debugging?

This is the markdown file in /content/posts/:

> title: "First_post"
> author: ["xxx"]
> date: 2021-08-02T22:39:25-07:00
> draft: true

> This is my first post.

and when I run `hugo server -D`, I got the following message:

`ERROR: 2021/08/05 22:37:50 render of "page" failed: execute of template failed: template: posts/single.html:17:8: executing "posts/single.html" at <partial "head/seo.html" .>: error calling partial: "~/org/diaries_hugo/themes/DoIt/layouts/partials/head/seo.html:129:41": execute of template failed: template: partials/head/seo.html:129:41: executing "partials/head/seo.html" at <safeHTML>: error calling safeHTML: unable to cast []string{"xxx"} of type []string to string`

**Comment by HEIGE-PCloud** [comment]
Have you changed `author: ["xxx"]` into `authors: ["xxx"]`?

**Comment by gnohz** [comment]
If I use `authors : ["xxx"]`, I got this:

```
render of "home" failed: execute of template failed: template: index.html:36:20: executing "content" at <.Render>: error calling Render: failed to execute template ["summary"] v: execute of template failed: template: _default/summary.html:39:16: executing "_default/summary.html" at <partial "meta/author" .>: error calling partial: "~/org/diaries_hugo/themes/DoIt/layouts/partials/meta/author.html:18:22": execute of template failed: template: partials/meta/author.html:18:22: executing "partials/meta/author.html" at <index $.Site.Data.authors $authorID>: error calling index: index of untyped nil
Rebuild failed:

Failed to render pages: render of "page" failed: execute of template failed: template: posts/single.html:17:8: executing "posts/single.html" at <partial "head/seo.html" .>: error calling partial: "~/org/diaries_hugo/themes/DoIt/layouts/partials/head/seo.html:150:26": execute of template failed: template: partials/head/seo.html:150:26: executing "partials/head/seo.html" at <index $.Site.Data.authors $authorID>: error calling index: index of untyped nil
```

**Comment by gnohz** [comment]
btw, I found [this](https://github.com/kaushalmodi/hugo-onyx-theme/blob/master/layouts/partials/author.html) to have a list of authors. 

Back to my original request to add the option for us to enable/disable authors. I am asking this because for example, most of us may just to blog for personal thoughts, but not a collaboration.

**Comment by HEIGE-PCloud** [comment]
I have managed to reproduce this error. To fix it, create a file `your_site/data/authors/xxx.toml` (you might need to create the folder `data` and `authors` for it) to let the Hugo `.Data` work. The name or the content of `xxx.toml` does not matter, just leave it blank if you want.

**Comment by HEIGE-PCloud** [comment]
There is no technical difficulity to "disable" the author, however it takes some effort to make it looks good when author is disabled.

![image](https://user-images.githubusercontent.com/52968553/128475634-d05e2d3b-bf25-4c69-bbfb-e8f23ada0e7d.png)

If we simply remove it, then the `published` need to be capitalized, involving changes in i18n translations. And remove the `&nbsp` before. It is possible to implement, but I think it is unnecessary. Like what you say, most people use it for personal blog, and it makes perfectly sense for people to sign their name in the front of their blog post. So we provide a simple option in `config.toml` for you to set that globally and without worrying it in the future. If you don't want to specify your name, then just leave the settings blank, remove all `authors` or `author` font matter, then it will show `Author`.

![image](https://user-images.githubusercontent.com/52968553/128476301-e04f5023-28f3-4608-bf1d-146254cfc0bb.png)

For which I think is very acceptable.

If you just hate the word `author`, then set the `author.name` to a space.

```toml
[author]
  name = " "
```

It is as easy as set some `author.enable` to `false` and the author is **completely visually disabled**.

![image](https://user-images.githubusercontent.com/52968553/128476720-395264dc-6e43-4317-95eb-50893ebaaada.png)

**Comment by gnohz** [comment]
> I have managed to reproduce this error. To fix it, create a file `your_site/data/authors/xxx.toml` (you might need to create the folder `data` and `authors` for it) to let the Hugo `.Data` work. The name or the content of `xxx.toml` does not matter, just leave it blank if you want.

I did as you suggested, but still no luck.

**Comment by HEIGE-PCloud** [comment]
> > I have managed to reproduce this error. To fix it, create a file `your_site/data/authors/xxx.toml` (you might need to create the folder `data` and `authors` for it) to let the Hugo `.Data` work. The name or the content of `xxx.toml` does not matter, just leave it blank if you want.
> 
> I did as you suggested, but still no luck.

Have you tried restart `hugo server`?

**Comment by gnohz** [comment]
> > > I have managed to reproduce this error. To fix it, create a file `your_site/data/authors/xxx.toml` (you might need to create the folder `data` and `authors` for it) to let the Hugo `.Data` work. The name or the content of `xxx.toml` does not matter, just leave it blank if you want.
> > 
> > 
> > I did as you suggested, but still no luck.
> 
> Have you tried restart `hugo server`?

Now it works, since I forgot to change `author` to `authors`.

**Comment by gnohz** [comment]
As for the option of disabling author, I tried to delete the following
`<span class="post-author">
                     {{- $options := dict "Class" "author" "Destination" $authorLink "Title" "Author" "Rel" "author" "Icon" (dict "Class" "fas fa-user-circle fa-fw") "Content" $author -}}
                     {{- partial "plugin/link.html" $options -}}
                     </span>`
in the `layouts/posts/single.html`, and it no author appears, also "published" with lower case "p".

But I also like your idea, to set
```
[author]
  name = " "
```
and it's simpler. 

Thank you so much for your time and help here.

**Comment by kaushalmodi** [comment]
For any ox-hugo user coming across this issue thread, you can make ox-hugo export your author list in `authors` front-matter instead of the default `author` by adding this at the top of the Org file(s):

```org
#+hugo_front_matter_key_replace: author>authors
```

This key replacement feature is documented [here](https://ox-hugo.scripter.co/doc/replace-front-matter-keys/#replace-author-with-authors). 

Ref: https://github.com/kaushalmodi/ox-hugo/issues/608#issuecomment-1086930066
