### ISSUE TITLE
[FEATURE] 请问可以增加 Topbar 吗

### ISSUE THREAD

**Issue by GinShio** [HEIGE-PCloud/DoIt#172]
### Describe the feature you want 描述你的功能需求

就是在最上面有一个极细小的进度条，用来指示当前阅读进度。并可以在配置文件中手动开关与更换颜色

### Useful reference 有价值的参考

类似于 GitHub Repo 加载页面时，顶部出现的进度条 (不过这个是表示加载进度而非当前阅读进度)

**Comment by HEIGE-PCloud** [comment]
为啥不直接看侧边的滚动条？

**Comment by wu-yue-yu** [comment]
侧边进度条就可以解决阿，这个主题专注于阅读的，越简洁越好吧。个人感觉读技术文章的时候少有注意到进度条，除非是看小说之类的🤣

**Comment by GinShio** [comment]
唔，确实侧边滚动条可以解决
在之前看到别的 blog 也有 topbar，所以一直想加入尝试玩一下下
可惜之前在 LoveIt 时尝试过但不太会
orz 所以就提了下 issue

**Comment by HEIGE-PCloud** [comment]
我不打算加入阅读进度条显示

1. "别的主题有"并不是一个足够好的理由。
2. 用 topbar 显示阅读进度并不比原生 scrollbar 更清晰。

![image](https://user-images.githubusercontent.com/52968553/128595931-4b728cfc-b2aa-495f-848e-443c4239a978.png)

例如这个页面，当我阅读完 "Build the Website" 这一节后，如果我需要知道当前的阅读进度，我只需要继续向右阅读。右侧的目录提供了所有内容的概览，高亮了我目前所在的章节，我可以点击章节标题来快速跳转。继续向右看，原生的 scrollbar 告诉我我在页面上的位置，我也可以拖动它直接快速跳转。相比而言，顶部的 topbar 不仅更难寻找（特别是在宽屏上），而且需要将视线完全离开文本来到页面顶端，然后再返回寻找当前阅读到的位置，并不实用。

3. 你可能会注意到，DoIt 是有一个 topbar 的。在页面进行 pjax 加载的时候，一条淡蓝色的 topbar 被用于显示加载的状态。重载这条 topbar 让它同时显示阅读进度反而会造成困惑。
