### ISSUE TITLE
[FEATURE] Dark mode for Telegram comments

### ISSUE THREAD

**Issue by dannyloxavier** [HEIGE-PCloud/DoIt#180]
### Describe the feature you want 描述你的功能需求

- Feature 1 功能需求 1
I want to be able to choose dark mode on comments for telegram

### Useful reference 有价值的参考

Including this in `layouts/partials/comment.html`, between lines 156 and 157 this:
```
             {{- if $telegram.dark -}}                                                                                                
                {{- $attr = printf `%v data-dark="1"` $attr -}}
            {{- end -}}
```
And `dark = true` inside the `[params.page.comment.telegram]` section at `config.toml`, will do the thing! =D

**Comment by HEIGE-PCloud** [comment]
I have added this option for telegram comment. Be aware that telegram comment's theme is fully determined by the settings in `config.toml`, so when user changes DoIt's color theme on their side, telegram comment's color will not follow.

**Comment by dannyloxavier** [comment]
Thank you very much!
