### ISSUE TITLE
ReferenceError: mermaid is not defined

### ISSUE THREAD

**Issue by islongshiyu** [HEIGE-PCloud/DoIt#181]
### Describe the bug 描述你遇到的错误

when i use mermaid in my posts, ReferenceError: mermaid is not defined

**Comment by HEIGE-PCloud** [comment]
Mermaid should be supported out of the box without any further configuration. And it seems to work correctly on the [demo site](https://hugodoit.pages.dev/mermaid-tests/). Can you provide more information? Does refreshing the page help? Does the HTML include the script tag for Mermaid? Or if you can provide a demo site with its source files that reproduces this issue will be very helpful.

**Comment by islongshiyu** [comment]
thanks, i saw this error when i build my blog at localhost.
it works well after i published to server

**Comment by islongshiyu** [comment]
thanks, i saw this error when i build my blog at localhost.
it works well after i published to server
