### ISSUE TITLE
[BUG] The deployment is inconsistent with the preview

### ISSUE THREAD

**Issue by jygzyc** [HEIGE-PCloud/DoIt#184]
### The deployment is inconsistent with the preview

The deployment is inconsistent with the preview

### Expected behavior 期待的行为

both should be same

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/33087260/129485382-ba3760ab-d8ed-4038-acaf-06e61d6427a9.png)
![image](https://user-images.githubusercontent.com/33087260/129485406-a003d740-e7bd-41cc-b6ec-d31484dd4a73.png)

### Build Environment 构建环境

- OS: Windows 10,
- DoIt：newest
- Hugo v0.87.0-B0C541E4+extended windows/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio

### Preview Environment 预览环境

- OS: Windows 10
- Browser Edge

### Additional Information 补充信息

![image](https://user-images.githubusercontent.com/33087260/129485473-438ce30f-e240-4de6-99dd-a850fd2d2957.png)

**Comment by HEIGE-PCloud** [comment]
Try turning off the fingerprint in `config.toml`

```toml
[params]
  fingerprint = ""
```

**Comment by jygzyc** [comment]
Fine! Thank you!
