### ISSUE TITLE
[BUG] 低版本 Firefox 无法正常加载 Awesome Font

### ISSUE THREAD

**Issue by GinShio** [HEIGE-PCloud/DoIt#208]
### Describe the bug 描述你遇到的错误

在低版本 Firefox ESR (68, 78) 无法正常加载 Awesome Font，但在 Firefox 91 ESR 中可以正常加载

### Expected behavior 期待的行为

在低版本 Firefox ESR 中可以正常加载

### Screenshots 屏幕截图

  - Firefox 68.9.0esr
    ![firefox_68 9 0esr](https://user-images.githubusercontent.com/38715657/132383171-b68341f0-8a22-42e3-9c1f-7a569dcaa50b.png)
  - Firefox 78.13.0esr
    ![firefox_78 13 0esr](https://user-images.githubusercontent.com/38715657/132383195-6dd3fc97-5cdf-43f7-9068-854eca61aba2.png)
  - Firefox 91.1.0esr
    ![firefox_91 1 0esr](https://user-images.githubusercontent.com/38715657/132383214-c2fcd9f2-b93a-42af-ab0d-7873566cb9c0.png)

### Build Environment 构建环境

- OS: openSUSE 15.2 (Linux Kernel 5.3.18)
- Hugo Version: **v0.87.0+extended** (linux/amd64)
- Theme Version: **735c3bc2** (after v0.2.12)

### Preview Environment 预览环境

  | 系统          | 浏览器  | 版本          | 加载情况 |
  | ---           | ---     | ---           | ---      |
  | Windows 7     | Firefox | 78.14.0esr    | 无法加载 |
  | Windows 7     | Firefox | 92.0          | 正常     |
  | openSUSE 15.2 | Firefox | 68.9.0esr     | 无法加载 |
  | openSUSE 15.2 | Firefox | 78.13.0esr    | 无法加载 |
  | openSUSE 15.2 | Firefox | 91.1.0esr     | 正常     |
  | Android 10    | Firefox | 91.3.1        | 正常     |

**Comment by HEIGE-PCloud** [comment]
关于 Font Awesome 对于 Firefox 低版本的兼容性问题，我建议你直接联系 Font Awesome 反馈。

在 DoIt 主题中，你可以尽可能避免使用 Font Awesome 的图标来避免相关兼容性问题。对于截图中所展示的社交图标，你可以在文件 `assets\data\social.yml` 中将来自 Font Awesome 相关的图标来源替换为 SimpleIcons，或者也可以通过

```
Icon:
    Src: svg/icons/icon.svg
```
的方式在 `assets\svg\icons` 文件夹下自行托管相关图标。

在其他使用 Font Awesome 图标的地方也可以自行替换为其他图标。

你也可以尝试降级 Font Awesome (`assets\lib\fontawesome-free\all.min.css`) 至老版本以获得对于旧浏览器更好的兼容性。

Reference: [Font Awesome 兼容性](https://fontawesome.com/v5.15/how-to-use/on-the-web/other-topics/browser-support)
