### ISSUE TITLE
[BUG] lunr error

### ISSUE THREAD

**Issue by thinkhp** [HEIGE-PCloud/DoIt#209]
### Describe the bug 描述你遇到的错误

lunr 功能无法使用，报错 TypeError: window.use is not a function

### Screenshots 屏幕截图
![image](https://user-images.githubusercontent.com/26300404/132649764-2d784ce8-5429-400a-a814-b279b14ff16d.png)

### Build Environment 构建环境

- OS: [macOS]
- Theme version/commit [3c1b2c8d4219e7699a4d7e289288dd2bb561f6bb]
- Hugo version [v0.87.0+extended]

### Preview Environment 预览环境

- OS: [macOS]
- Browser [Chrome]

**Comment by HEIGE-PCloud** [comment]
应该修好了，更新到最新的 commit 看看能不能用。
