### ISSUE TITLE
[BUG] 在社交媒体中分享网址时，无法正确读取网站名称

### ISSUE THREAD

**Issue by yeahwong** [HEIGE-PCloud/DoIt#217]
例如，在telegram上分享某页面后，预览只会显示网站的域名或者前缀，无法正确显示整个网站的标题。

**Comment by HEIGE-PCloud** [comment]
Related reference: https://ogp.me/

**Comment by HEIGE-PCloud** [comment]
Telegram 使用 `og:site_name` 属性获取网站名称。

```html
<meta property="og:site_name" content="your site name">
```

Hugo 自带了 [Open Graph 模板](https://gohugo.io/templates/internal/#open-graph)，DoIt 主题也使用了该模板用于[生成 meta 信息](https://github.com/HEIGE-PCloud/DoIt/blob/a4f340ee99de1c28c82d961e8c8736f6a6c507b3/layouts/partials/head/meta.html#L5)。

通过查阅 [Hugo 源码](https://github.com/gohugoio/hugo/blob/3efc2e2af8d677d968606460d044d54244cc6623/tpl/tplimpl/embedded/templates/opengraph.html#L28)，可以看到 Hugo 使用的是 `.Site.Params.title` 来获取网站名称。所以只需要在 `config.toml` 中添加以下配置

```toml
[params]
  title = "your site name"
```

即可正确显示网站名称。

![image](https://user-images.githubusercontent.com/52968553/132956177-1fbacadc-8351-410c-9452-db8173ca884b.png)

**Comment by yeahwong** [comment]
我又发现一个问题，链接在telegram或twitter中，有的链接会显示图片，而doit的博客并不会显示，这个需要怎么设置？谢谢。

**Comment by HEIGE-PCloud** [comment]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/52968553/147002531-4899bcfc-f43e-48ab-a6a3-5202ce9a5d89.png">

@yeahwong 推特上的显示似乎在我这里没有问题。Telegram 不显示也许是因为我使用了 webp 格式的图片，Telegram 不支持。换回 png 之后应该就可以了。代码上应该是没什么问题的，在文章前置参数中配置 `featuredImage` 就可以启用了。

可以参考 exampleSite：

https://github.com/HEIGE-PCloud/DoIt/blob/188fdde2163ae851591a9d2d7b26ab3ab041c244/exampleSite/content/posts/theme-documentation-basics/index.en.md?plain=1#L9

**Comment by yeahwong** [comment]
啊，原来和图片格式有关，谢谢指教。
