### ISSUE TITLE
[BUG] Friend link has styling issues on mobile

### ISSUE THREAD

**Issue by HEIGE-PCloud** [HEIGE-PCloud/DoIt#218]
在手机上测试友情链接卡页面，如果网站标题过长，手机页面上会出现友情链接卡错落的现象，网站名称与头像会挤在一起。

_Originally posted by @yeahwong in https://github.com/HEIGE-PCloud/DoIt/issues/82#issuecomment-917308560_

**Comment by HEIGE-PCloud** [comment]
@yeahwong

https://do-it-git-fix-friend-pcloud.vercel.app/friend-link-tests/

对移动端的行为做了修改，现在在窄屏下每行只显示一个友链，并将完整显示 bio，正确处理 overflow。

**Comment by yeahwong** [comment]
> @yeahwong
> 
> https://do-it-git-fix-friend-pcloud.vercel.app/friend-link-tests/
> 
> 对移动端的行为做了修改，现在在窄屏下每行只显示一个友链，并将完整显示 bio，正确处理 overflow。

谢谢开发者的维护工作。

**Comment by HEIGE-PCloud** [comment]
你觉得没问题我就 merge 了
