### ISSUE TITLE
[BUG] Page wide in vercel and others....

### ISSUE THREAD

**Issue by kyb3rcipher** [HEIGE-PCloud/DoIt#221]
### Describe the HELP (NOT IS A BUG)

My Website (for example): https://kyb3rvizsla.com

Update the theme and notice some changes. I have my website in "wide" page mode when I run the server on my local machine, it places everything bine (see image 1) but when I deploy it with vercel/netlify it changes me (see image 2) I have seen that this happens with the [HEIGE-PCloud](https://planet-cloud.fun) page, I do not know why this happens I used GitHub pages and it does not happen, the problem with GitHub pages is that it is not yet advanced enough as vercel in terms of domain management ,  some help?

### Screenshots 屏幕截图
Image 1
![image](https://user-images.githubusercontent.com/63558088/132966345-01128070-5e13-4323-a23b-7938c0ea73dc.png)
![image](https://user-images.githubusercontent.com/63558088/132966349-4d359713-cb9a-433d-a694-af45540cfa62.png)

Image 2
![image](https://user-images.githubusercontent.com/63558088/132966303-8fe18ae2-e170-45c0-bb68-307c113382b5.png)
![image](https://user-images.githubusercontent.com/63558088/132966312-1a681a47-5d92-4730-9064-d7a0ff6bff4e.png)

**You can see the space it leaves!**

Vercel config build
![image](https://user-images.githubusercontent.com/63558088/132966487-8e4f6845-3238-4dcb-aeca-7fa96526ee24.png)
![image](https://user-images.githubusercontent.com/63558088/132966490-55437719-3803-4213-9f05-be4b67eff594.png)

### Build Environment 构建环境

- OS: [Vercel]
- Theme version/commit [commit: 1d9709999de5b2f4d8e264b7a43f444b9027cfe0] (I have already updated it and it keeps happening.)
- Hugo version [lasted version 0.88.1] (But it doesn't matter with 0.85 and 0.87 it is the same.)

### Additional Information 补充信息

Configuration files or front matter code...
See my config file in [my website repo](https://github.com/kyb3rvizsla/kyb3rvizsla.com) - You can see the construction logs in this repository

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/132983722-f0edc11e-7df4-45f4-b0f2-9efffe3bcd88.png)

This is what I see on this [page](https://kyb3rvizsla.com/posts/kali-or-parrot/). Is it the `wide` mode you expect?

**Comment by HEIGE-PCloud** [comment]
The site should build the same no matter what platform you use.

Here is the documentation site built on [Vercel](https://do-it-green.vercel.app/theme-documentation-basics/), for which the `wide` mode seems to work correctly to me.

[My blog](https://planet-cloud.fun/) use the `normal` mode instead of the `wide` mode, so it is behaving correctly.

**Comment by kyb3rcipher** [comment]
Thanks for answering. in despair yesterday I ended up uploading the public folder generated from my local machine. But today I returned to the host vercel here the config:
![image](https://user-images.githubusercontent.com/63558088/132985168-bb4e9a18-5822-4f9d-93bd-e4c60f7a340a.png)
![image](https://user-images.githubusercontent.com/63558088/132985170-d589e19c-fe8a-4e70-8190-22932430f909.png)

He put the [repo](https://github.com/kyb3rvizsla/kyb3rvizsla.com) in public again, therefore the logs are also included in [config.toml](https://github.com/kyb3rvizsla/kyb3rvizsla.com/blob/main/config.toml)

But it still happens if it were a misconfiguration error, it should also happen when I run ```hugo``` on my machine and it throws me a public but not when I do it, it works only when it goes to vercel.

![image](https://user-images.githubusercontent.com/63558088/132985271-45d5a8e0-3a8c-4bea-926d-26b659764912.png)

And that came back with vercel.

**Comment by HEIGE-PCloud** [comment]
I see, `params.page.toc.enable` is not set in your `config.toml`. So the table of content on the right does not know how to behave and fall back to the default style.

Add the following configurations to your `config.toml` should fix the issue.

```toml
[params.page.toc]
      # whether to enable the table of the contents
      enable = true
      # whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = true
```

Please check your `config.toml` against this [sample](https://hugodoit.pages.dev/theme-documentation-basics/#site-configuration), you still need to keep these configuration options set even if you don't want to change them.

**Comment by kyb3rcipher** [comment]
Okay, I'll add all the parameters later, but for now, what is the parameter table for the navbar to be wide?

In vercel:
![image](https://user-images.githubusercontent.com/63558088/132987621-3405aeae-e47d-422b-b179-ee7cb0252c8c.png)


 In local:
![image](https://user-images.githubusercontent.com/63558088/132987598-ba3f7784-69b6-49fe-bd80-245abb75c136.png)

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/132988728-1af251d8-98a6-4bad-8fb0-ba40e839a845.png)

The padding of the heading is not adjustable, it always takes 10% of the screen size on desktop. Not sure what's gone wrong in your local environment, but the Vercel one is the correct one.

**Comment by kyb3rcipher** [comment]
Okay, very thanks
