### ISSUE TITLE
typeit types the site name 3 times

### ISSUE THREAD

**Issue by xpufx** [HEIGE-PCloud/DoIt#222]
I just migrated from loveit. I hadn't changed anything in themes/loveit but I do have a few simple overrides.

I have typeit enabled for the site name at the top.  typeit types the name of the site 3 times.

May be related to #213

**Comment by HEIGE-PCloud** [comment]
Can you provide more information, maybe a demo site for easier debugging? Since TypeIt is clearly working correctly on the [documentation site](https://hugodoit.pages.dev/), I cannot reproduce that on my side.

**Comment by xpufx** [comment]
I deployed again with typeit enabled for the header name ([params.header.title] name) . I checked on windows firefox and android kiwi. It takes a few clicks around the site for it to appear.

It actually seems to be adding one more every time you click something. Honestly it's hilarious to watch :)

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/133143496-abe86319-0f78-4a06-93f9-36d7e43d9a10.png)

Have you updated the theme to the latest commit? The `theme.js`  file on your site does not seem to contain that fix I create for #213

**Comment by HEIGE-PCloud** [comment]
> It actually seems to be adding one more every time you click something. Honestly it's hilarious to watch :)

Yes, because the DoIt theme loads new pages with PJAX loading (#78). The re-loading bug is caused by creating a new TypeIt instance while the old one is not destroyed. The latest commit should contain a fix preventing that from happening.

**Comment by xpufx** [comment]
I was on the latest release. I cloned the code now and it's working properly. Thanks.!
