### ISSUE TITLE
Block Fenced Code boxes broken on mobile

### ISSUE THREAD

**Issue by xpufx** [HEIGE-PCloud/DoIt#223]
Long lines of code escape the box.

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/133084386-78e55f2d-60cb-4a7f-b922-d1462ef00235.png)

The overflow seems to be handled correctly to me.

**Comment by xpufx** [comment]
This is on Firefox/Android.

![overflow](https://user-images.githubusercontent.com/25581961/133089681-44ffd319-84a0-43fc-8560-12985edb7468.jpg)

**Comment by HEIGE-PCloud** [comment]
The CSS property `overflow: auto hidden`  is used to handle the overflow, which should be supported by Firefox.

Please check against this [page](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow) with the `overflow: auto;` demo to see whether your browser is compatible with this CSS property.

**Comment by xpufx** [comment]
I tested the browser. It's fine. I will see if I can figure out what's going on in the published HTML/CSS. Although, it's weird since your browser displays it fine.

**Comment by HEIGE-PCloud** [comment]
No, there is no such configuration.

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/133093235-25e5202f-1487-4965-8ec4-a953aae61902.png)

It works correctly on iOS Safari as well. So I think it may be caused by some browser compatibility issues...

**Comment by xpufx** [comment]
Works fine on Kiwi browser (chromium based) too.  I will see if I can identify the source of the issue on firefox.

**Comment by xpufx** [comment]
I think Firefox was caching the old state of the site with loveit's broken box. Thanks for your help. All good now.
