### ISSUE TITLE
[BUG] Font Awesome Icon not work

### ISSUE THREAD

**Issue by kyb3rcipher** [HEIGE-PCloud/DoIt#233]
### Describe the bug 描述你遇到的错误
Some font awesome icons won't load

一段简短的对于你遇到的错误的描述.

### Expected behavior 期待的行为
I tried to load the font awesome icon "instagram-square" and it wouldn't load.

一段简短的对于你期待的行为的描述.

### Screenshots 屏幕截图
![image](https://user-images.githubusercontent.com/63558088/134104427-e5970024-197c-495a-81f3-d1ff086f76da.png)
![image](https://user-images.githubusercontent.com/63558088/134104442-0982aff3-9b44-470c-8c2e-551fbb001802.png)
![image](https://user-images.githubusercontent.com/63558088/134104469-d98d09e3-45e4-47e4-a938-34f9f422b64b.png)
![image](https://user-images.githubusercontent.com/63558088/134104478-19385e83-78fc-46af-b99f-cf38ecf25833.png)
Firefox:
![image](https://user-images.githubusercontent.com/63558088/134104704-de285d40-85f9-41a8-9139-013c310068f7.png)

如果可以的话, 提供屏幕截图对解决问题很有帮助.

### Build Environment 构建环境

- OS:Fedora Linux
- Theme version/commit 1d9709
- Hugo version 0.88.1 (lasted)

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

### Preview Environment 预览环境

- OS: Fedora Linux
- Browser Microsoft Edge Beta - but it was tested in other browsers

### Additional Information 补充信息

Configuration files or front matter code...
[Website Repo](https://github.com/kyb3rvizsla/kyb3rvizsla.com)

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/134125415-51a5a855-e8cd-404f-a6a6-6ecf8d70659e.jpeg)

Is this the instagram icon?

**Comment by kyb3rcipher** [comment]
Yes that is the instagram icon that works the one that does not work is "instagram-square"

**Comment by HEIGE-PCloud** [comment]
Should be fixed with the latest commit. The Fontawesome webfont library has not been updated for a long time...

**Comment by kyb3rcipher** [comment]
Okay, thanks
