### ISSUE TITLE
[FEATURE] 增加buymeacoffee.com按钮

### ISSUE THREAD

**Issue by yeahwong** [HEIGE-PCloud/DoIt#238]
请求在文摘内文页面中增加buymeacoffee赞赏功能的支持，谢谢。

**Comment by HEIGE-PCloud** [comment]
Buymeacoffee 提供了许多不同样式与风格的赞助图标，你可以在 [dashboard](https://www.buymeacoffee.com/dashboard) 中的 “Integrations to take it to the next level” 自行创建喜欢的 website buttons。复制生成的 image code 并将其放在文章末尾来显示你的赞赏图标。

```html
<a href="https://www.buymeacoffee.com/PCloud" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" style="height: 60px !important;width: 217px !important;" ></a>
```
![image](https://user-images.githubusercontent.com/52968553/134738012-3fa8de28-c23d-4dd1-9839-5ad3fd003843.png)

你可以通过修改 `style` 属性来调整它的位置与大小。

你也可以通过创建 [自定义 shortcode](https://gohugo.io/templates/shortcode-templates/) 使插入与维护赞赏按钮更加方便。

Buymeacoffee 的自定义功能众多，由 DoIt 主题维护相关接口成本高昂且并不带来显著使用便利，所以我并不打算为其添加功能。

**Comment by yeahwong** [comment]
谢谢回复。是否可以增加一个在文章内页文末设置一个banner的功能呢？这样方便插入某些东西。

**Comment by HEIGE-PCloud** [comment]
添加一个通用的赞助按钮应该是可行的。

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/134744787-f2b5fe09-6546-45f6-b2cf-262e0c31a969.png)


可以在每个页面的页脚上方加一个类似这样的作者列表，右侧可以放置一个（或者数个）赞赏按钮。

**Comment by yeahwong** [comment]
弱弱地问一下，图片里面Author旁边的小人半身是否可以去掉？

**Comment by HEIGE-PCloud** [comment]
这 demo 是从 [friend shortcode](https://hugodoit.pages.dev/friend-link-tests/) 那里抄的样式，看看意思意思，后面会调的。

想做成这样的列表是考虑到多作者支持 (#98) 一个页面可以放多个作者的赞赏链接。右边的按钮支持直接配置 html，从而可以直接放置多个赞赏按钮。点击头像或者名称可以跳转到分类页面，或者个人网站。

**Comment by yeahwong** [comment]
这个友情链接样式中也有那个半身小人，然后某某作者某某时间发布文章那里也有这个半身小人，我个人觉得加了这个半身小人挺难看的。

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/137115254-32a49546-9fdf-4be8-aa17-c2f22e945d16.png)

我的最新想法是这样的。

1. 如果配置了 `authors` 多作者选项，并排显示多个作者的 avatar。
2. 如果配置了 `author` 选项，使用 `author.avatar` 作为头像。
3. ~~最后 fallback 到 `home.profile.avatarURL`~~ 如果均未配置，则不显示头像。
4. 可以通过 `params.page.sponsor.link` 或者 `params.page.sponsor.custom` 来配置下方的 Sponsor 按钮。
5. 在 `params.page.sponsor.link` 填入一个链接，主题会提供一个默认样式的赞助按钮。
6. 在 `params.page.sponsor.custom` 中填入自定义 HTML code，覆盖 `link` 的行为（通过这种方式支持同时显示多个赞助方式）。
7. 在 `params.page.sponsor.bio` 中填入介绍。
8. 以上选项均支持在 `config.toml` 和页面中单独配置。


抱歉这个 issue 拖了这么久没有解决，我会在这两天提交一个 PR 实现这个功能。

**Comment by yeahwong** [comment]
谢谢，辛苦啦。

**Comment by wey-gu** [comment]
辛苦啦，明明不喜欢 html/css 还这么 nice 👍。（从 Cloud Valley 过来）

**Comment by HEIGE-PCloud** [comment]
> 辛苦啦，明明不喜欢 html/css 还这么 nice 👍。（从 Cloud Valley 过来）

我错了 我不摸鱼了......（来交 pr 啦 #275
