### ISSUE TITLE
cannot sponsor？

### ISSUE THREAD

**Issue by wey-gu** [HEIGE-PCloud/DoIt#241]
It seems I am not recognized as gh sponsorship?
And when I was selecting monthly tier I got this error:

![image](https://user-images.githubusercontent.com/1651790/134790095-38470185-1073-411c-b039-9614fd1e42df.png)

Could you plz help on this when you have some time?

Thanks!
BR

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/134801799-c0a21cec-abdc-4d70-ae44-10e25de63b8f.png)
![image](https://user-images.githubusercontent.com/52968553/134801809-96b832ad-8889-4068-a80b-e9e012e7d082.png)
![image](https://user-images.githubusercontent.com/52968553/134801812-dc334eed-da33-4a0d-a678-4f0f972fced8.png)

I too have no clue what is happening...

I will contact GitHub Support and hopefully get it sorted soon.

**Comment by wey-gu** [comment]
Thank you :)
I meant to sponsor 20 one-time and then have(plus) the monthly one, while it seems not supporting this kind of situation?

**Comment by HEIGE-PCloud** [comment]
Here is the response I got from GitHub Support.

Hi there,
Thanks for getting in touch.
It looks like there might be a glitch in that specific sponsorship record, though I'm pleased to find it's not impacting on their payments being transferred to you.
If you're in contact with wey-gu, could you copy them into this conversation, or ask them to reach out directly?
I'll then be able to share more details and hopefully get this resolved for you both.
Thanks,
Laurie

LOL😂

**Comment by wey-gu** [comment]
Haha, thanks!
I just sent a support request referring to this issue and mentioned Laurie in ticket #1326832 :)

**Comment by HEIGE-PCloud** [comment]
I have received a $30 One time sponsor successfully! Thank you 😁

**Comment by wey-gu** [comment]
Thank you! After confirmed "all dots connected" from Laurie, the monthly tier will come then :D

**Comment by wey-gu** [comment]
The monthly tier had also been placed just now with the help of Laurie.

>Fabulous! I can see that's in place, and today's payment has transferred to HEIGE-PCloud successfully.
>
>I also checked that the sponsorship is showing up appropriately on both your profiles:
>
>https://github.com/sponsors/HEIGE-PCloud
>
>https://github.com/wey-gu
>
>I'm hopeful you're good to go from here, but please let me know if I can help with anything else :)
>
>Thanks,
>
>Laurie

If you still have the ticket opening with Laurie, help me to thank her again, please.

Closing this issue.
Cheers!
