### ISSUE TITLE
[FEATURE] Waline: option to show or not the user's browser and OS

### ISSUE THREAD

**Issue by dannyloxavier** [HEIGE-PCloud/DoIt#250]
### Describe the feature you want 描述你的功能需求

- Feature 1 功能需求 1
  I want the possibility to enable or disable the user's info about browser and OS.

### Useful reference 有价值的参考

This discussion is about the same question https://github.com/walinejs/waline/discussions/576 , where can be solved using this CSS to hide them

```
.vmeta {
  display:none;
}
```

Thank you for your work and have a nice day.

**Comment by dannyloxavier** [comment]
### Useful reference (again)

It is possible to set 'DISABLE_USERAGENT' to 'true'
It's officially supported by them
You can check it on https://waline.js.org/en/reference/server.html#basic

**Comment by HEIGE-PCloud** [comment]
Yes, and it is an option on the server side.

**Comment by dannyloxavier** [comment]
Oh, my...
Thanks for the information! =)
Sorry for so many requests. =/
