### ISSUE TITLE
[FEATURE] Waline: Comment line break

### ISSUE THREAD

**Issue by dannyloxavier** [HEIGE-PCloud/DoIt#251]
### Describe the feature you want 描述你的功能需求

- Feature 1 功能需求 1
  I want this feature to solve a line break problem.
  When the phrase is too long, the word is cutted. This solution is to bring the entire word down.
  Basically, including something like this to the Waline scss will solve this problem:

```
.v[data-class=v] .vcards .vcard .vcontent {
  word-break: normal;
}
```
### Useful reference 有价值的参考

I saw this here: https://github.com/walinejs/waline/discussions/189

**Comment by HEIGE-PCloud** [comment]
Why not ask Waline to fix it on their side? I can use custom style sheet to implement a fix, but it is much better if their default style sheet works correctly out of the box.🤔

**Comment by dannyloxavier** [comment]
It's true. Thank you anyway. Gonna ask them. 😁

**Comment by dannyloxavier** [comment]
This latest version already solve this problem. Thank you, anyway!
