### ISSUE TITLE
[BUG] Waline doesn't translate to pt-BR

### ISSUE THREAD

**Issue by dannyloxavier** [HEIGE-PCloud/DoIt#253]
### Describe the bug 描述你遇到的错误

When using `defaultContentLanguage = "pt-br"` and `languageCode = "pt-BR"`, the waline interface becomes chinese (chinese is the default language).
Using 'en', instead, makes the whole site in english and the waline too.
I can't test if the language code has any kind of typo because the `lang` parameter from waline was removed from the config.toml.
I would test if it works with pt-br, pt-BR, ptBR and ptbr. =/

### Expected behavior 期待的行为

Waline server and DoIt theme's waline client were updated to 1.3.9 with pt-BR translation and was expected to works 

### Build Environment 构建环境

- Netlify: OS: [Ubuntu 21.04]
- Theme version/commit [0a9470a]
- Hugo version [0.81 extended]

**Comment by HEIGE-PCloud** [comment]
This is quite a tricky issue. I use [Hugo Site Variables](https://gohugo.io/variables/site/) `.Lang` to [set the language](https://gohugo.io/variables/site/) for Waline (and for all other comment systems that support i18n). On a multilanguage site, this allows the comment plugin to be loaded with the corresponding language on different pages.
For example, on DoIt Documentation site, you will find the comment is displayed in [en](https://hugodoit.pages.dev/theme-documentation-basics/#comments) and [zh-cn](https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#comments) correctly.
`.Lang` fills in an [RSS Language Code](https://www.rssboard.org/rss-language-codes) based on the setting. And in your case, no matter what you put in the setting, Portuguese (Brazil)'s language code `pt-br` will be filled to Waline, which does not match the [`pt-BR`](https://github.com/walinejs/waline/tree/main/packages/client/src/config/i18n) code in Waline causing it to fall back to default language.
There are no universal standards for language code and other project may or may not respect the RSS standard. As you can see a simple `Language` option will not work for multilanguage sites. It is way too complex to maintain a "mapping table" between different language codes as well.
For other projects, they can try to support multiple language codes standards, for example [Twikoo](https://github.com/imaegoo/twikoo/blob/4e3f925f8b0f4da5f9fe1987dd9d02d2bcf1d969/src/js/utils/i18n/index.js) is a good example.  For me, I probably can provide a hidden `Language` option that override the default `.Lang` behaviour and force the language to be set by user.

**Comment by dannyloxavier** [comment]
Thanks for the reply!
The version 1.3.9 was included the language `pt-br`, for compatibility and still not working. =(

**Comment by HEIGE-PCloud** [comment]
As I mentioned above, it is not about the “language” support, but the “language code format”. Lower case pt-br is filled instead of pt-BR which is causing this problem.

**Comment by HEIGE-PCloud** [comment]
I will take a look.

**Comment by dannyloxavier** [comment]
As I said. There is the waline with pt-BR and pt-br (both at the same time), now.
You are right! It's language code format.

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/135274266-d084a47b-5407-42fc-8b07-5a4ebf22e974.png)

I have got it to work. The reason is the #252 does not really update the `Waline.min.js` to 1.3.9. I have no idea what version it is.

**Comment by dannyloxavier** [comment]
You are the best! Thank you!!!

**Comment by Mister-Hope** [comment]
Hi there, I am the developer of current waline client, and I am negative towards the changes in the newest version (this version is not published by me). Client is a fronend script running on broswers, and should follow the HTML standard (Since TS39 does not clearlify it in ECMAScript).

In the spec, HTML ISO Country Codes should always be uppercase.

Res:

- https://www.w3.org/International/articles/language-tags/index.en
- https://www.rfc-editor.org/rfc/rfc5646.txt

If a user is receiving `pt-br` somehow by mistake, it's his job to correct it (such as `lang === 'pt-br'? 'pt-BR' : lang`) I don't think this should be added in our code.

I am a little busy these days, so I may not have time to check your codes. Could you explain why you are receiving a lowercase lang code? (E.g.: on what result from what toolchain?)

BTW, I will have a dicussion with waline 's current owner, and may remove lowercase support

**Comment by HEIGE-PCloud** [comment]
[Hugo](https://gohugo.io/content-management/multilingual/) uses [RSS language code](https://www.rssboard.org/rss-language-codes) instead of the HTML ISO Country Codes, for which all codes are lowercases. So it is quite difficult to setup Waline for a multilanguage site properly if the lower cases country codes are not supported as I mentioned above.

> This is quite a tricky issue. I use [Hugo Site Variables](https://gohugo.io/variables/site/) `.Lang` to [set the language](https://gohugo.io/variables/site/) for Waline (and for all other comment systems that support i18n). On a multilanguage site, this allows the comment plugin to be loaded with the corresponding language on different pages. For example, on DoIt Documentation site, you will find the comment is displayed in [en](https://hugodoit.pages.dev/theme-documentation-basics/#comments) and [zh-cn](https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#comments) correctly. `.Lang` fills in an [RSS Language Code](https://www.rssboard.org/rss-language-codes) based on the setting. And in your case, no matter what you put in the setting, Portuguese (Brazil)'s language code `pt-br` will be filled to Waline, which does not match the [`pt-BR`](https://github.com/walinejs/waline/tree/main/packages/client/src/config/i18n) code in Waline causing it to fall back to default language. There are no universal standards for language code and other project may or may not respect the RSS standard. As you can see a simple `Language` option will not work for multilanguage sites. It is way too complex to maintain a "mapping table" between different language codes as well. For other projects, they can try to support multiple language codes standards, for example [Twikoo](https://github.com/imaegoo/twikoo/blob/4e3f925f8b0f4da5f9fe1987dd9d02d2bcf1d969/src/js/utils/i18n/index.js) is a good example. For me, I probably can provide a hidden `Language` option that override the default `.Lang` behaviour and force the language to be set by user.

As far as I know, there is no technical difficulties to support both standards, but it is up to you. 🤔

And you can blame Hugo for it if you want https://github.com/gohugoio/hugo/issues/7344

**Comment by Mister-Hope** [comment]
I see it, rss do use lowercase, but it's probably not a common standard. (It greatly narrows xml and do have it's own tags, and not much pretty related to html) I will rethink about it later.

**Comment by Mister-Hope** [comment]
I see your problems, you are receveing rss starded code from Hugo, and that is set by user, right?

I think it's possible for you to write a transform function here to support Waline, but yes, it's much more easier if waline can native support rss langcode.

**Comment by Mister-Hope** [comment]
I am still negative towards it because I think rss itself is obeying https://www.rfc-editor.org/rfc/bcp/bcp47.txt first. This is made by  IETF, and should be unify accoss the internet. Do you know other language or standard that also make country code lowercase? 🧐
