### ISSUE TITLE
[FEATURE] 新增文章加密功能

### ISSUE THREAD

**Issue by gclm** [HEIGE-PCloud/DoIt#254]
### Describe the feature you want 描述你的功能需求

新增和hexo一样新增文章加密功能

效果如下：
![image](https://user-images.githubusercontent.com/27618687/135372184-8f0037d5-dc40-47b6-bef0-b090a85dfc7e.png)

### Useful reference 有价值的参考

- https://github.com/D0n9X1n/hexo-blog-encrypt/blob/master/ReadMe.zh.md

**Comment by HEIGE-PCloud** [comment]
文章加密超过了主题能提供的功能的范畴，你可以使用 [hugo-encrypt](https://github.com/Izumiko/hugo-encrypt) 来实现相关功能。

**Comment by gclm** [comment]
好的，谢谢
