### ISSUE TITLE
[FEATURE] 新增最近10篇文章（已经实现不会搞多语言）

### ISSUE THREAD

**Issue by gclm** [HEIGE-PCloud/DoIt#255]
### Describe the feature you want 描述你的功能需求
- 新增最近10篇文章

目前我已经自己实现了，但是不会做多语言，不知道如何pr或者是否官方可以实现这个需求呢？
![image](https://user-images.githubusercontent.com/27618687/135380291-21d72129-8663-41e7-a96c-c4630df4d119.png)

### Useful reference 有价值的参考

- https://gohugo.io/templates/lists/
- https://blog.gclmit.club/posts/

**Comment by HEIGE-PCloud** [comment]
无论是在首页还是所有文章页面，所有文章都是按照时间顺序排列的，最新的文章本来就会排在顶部。为什么需要单独的一个最近更新板块呢？

![image](https://user-images.githubusercontent.com/52968553/135417706-f4d6f6ec-4859-469e-a233-a22df2b83214.png)

在你提供的这个 demo 中，“最近更新”板块下的文章与下方的文章在文章内容与顺序上都是完全一样的，为什么需要单独添加这个模块呢？

**Comment by gclm** [comment]
1.  文章是存在更新的操作的。
2. 目前首页和文章归档这里都是基于文件创建时间排序的，所以会存在老文章更新过但是查看的人不知道他更新过的问题。
3. **最近更新是基于文章更新时间排序展示的**

**Comment by HEIGE-PCloud** [comment]
这个功能是实用的，在实现方式上需要更多的考量。我的想法是

- 在“最近更新”中不显示 `lastmod` 与 `date` 相同的文章，以过滤掉新发布的文章
- 仅显示一定时间段内更新的文章（如一个月内）
- 提供单独的 RSS 订阅

**Comment by gclm** [comment]
可以可以，比我考虑的更全面

**Comment by HonorKnight8** [comment]
能不能做个 “按发布时间排序” 、 “按更新时间排序”

**Comment by HEIGE-PCloud** [comment]
在同一页面上同时显示 “按发布时间排序” 和 “按更新时间排序” 遇到了一些技术障碍。

> If you call .Paginator or .Paginate multiple times on the same page, you should ensure all the calls are identical. Once either .Paginator or .Paginate is called while generating a page, its result is cached, and any subsequent similar call will reuse the cached result. This means that any such calls which do not match the first one will not behave as written.

https://gohugo.io/templates/pagination/
