### ISSUE TITLE
[FEATURE] Enhance searching

### ISSUE THREAD

**Issue by HEIGE-PCloud** [HEIGE-PCloud/DoIt#259]
Currently, the search result only guides the user to the correct page, but not the correct paragraph. By adding paragraph information to `index.json` `uri` field to enhance the searching experience.

**Comment by 2ynhub** [comment]
@HEIGE-PCloud , Can enhanced searching be turned off?
For example, at https://hugodoit.pages.dev/posts/, if I search 'theme', there are so many results with 'Theme Documentation - Basics' and 'Theme Documentation - Content' and 'Theme Documentation - Built-in Shortcodes'. So, 'Theme Documentation - Extended Shortcodes' post is not shown in the result list. And, if I have a post with more than 10 paragraphs, that post is all over the result list. So, making it hard to find other posts.
