### ISSUE TITLE
[FEATURE] 支持Safari标签页颜色

### ISSUE THREAD

**Issue by yeahwong** [HEIGE-PCloud/DoIt#261]
在Safari15中浅色模式下的网站header与标签页的颜色不一致，希望修正这一问题，这样看起来更舒心。

**Comment by HEIGE-PCloud** [comment]
在 `your_site/assets/css/_override.scss` 中，你可以覆盖 `themes/DoIt/assets/css/_variables.scss` 中的变量以自定义样式。

```scss
$header-background-color = #custom_color
```

你可以通过修改 `$header-background-color` 变量来调整浅色模式下 header 的颜色。

Reference: https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#33-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F

**Comment by yeahwong** [comment]
并不是自定义header的颜色，而是定义Safari标签页颜色与主题header颜色一致，新版本的Safari新增加了标签页颜色的功能。

**Comment by HEIGE-PCloud** [comment]
抱歉，我不使用 MacOS 也不使用 Safari，对相关的功能与接口不太熟悉。能否麻烦你提供相关的文档以供参考呢？

**Comment by yeahwong** [comment]
也许可以参考这个链接

https://useyourloaf.com/blog/safari-15-theme-color/
