### ISSUE TITLE
[BUG] Waline's view count is broken?

### ISSUE THREAD

**Issue by CXwudi** [HEIGE-PCloud/DoIt#263]
### Describe the bug 描述你遇到的错误

After I setup waline and also put `visitor = true` in `[params.page.comment.waline]`, it shows this screenshot
设置好waline后并开启`visitor = true`, 并没有成功显示view count
![image](https://user-images.githubusercontent.com/17377423/136104261-c3bfe803-c40f-4f45-80f6-b5e81d8291bb.png)

### Expected behavior 期待的行为

I should see the view count like in the demo
应该像demo那样显示view count

### Screenshots 屏幕截图

see above
同上

### Build Environment 构建环境

- OS: WSL2 Ubuntu 20.04 in Windows 10 21h1
- Theme version/commit: b3d6a33
- Hugo version: hugo v0.88.1+extended linux/amd64 BuildDate=unknown

### Preview Environment 预览环境

- OS: Windows 10 21h1
- Browser: Chrome

### Additional Information 补充信息

This is my complete config file
这是我的完整的config.toml
[config.zip](https://github.com/HEIGE-PCloud/DoIt/files/7289372/config.zip)

**Comment by HEIGE-PCloud** [comment]
在 #244 里不知道为啥把 `visitor` 配置项删掉了。。。我提交了一个 fix，麻烦更新到最新的 commit 测试一下。

**Comment by CXwudi** [comment]
![image](https://user-images.githubusercontent.com/17377423/136116893-a28049d4-c6a7-4e44-8fb4-b72ec5229a80.png)
好快的效率, 感谢
