### ISSUE TITLE
[FEATURE] 新增打印博文为pdf并自动下载pdf

### ISSUE THREAD

**Issue by gclm** [HEIGE-PCloud/DoIt#266]
### 新增打印博文为pdf并导出

- 打印html为pdf
- 自动下载pdf

### Useful reference 有价值的参考
- https://greasyfork.org/zh-CN/scripts/428697-%E7%BD%91%E9%A1%B5%E6%96%87%E7%AB%A0%E8%BD%ACpdf-%E7%BD%91%E9%A1%B5%E5%B1%80%E9%83%A8%E5%8C%BA%E5%9F%9F%E6%89%93%E5%8D%B0-%E9%80%82%E7%94%A8%E4%BA%8E%E7%9F%A5%E4%B9%8E-csdn-%E7%AE%80%E4%B9%A6-%E5%8D%9A%E5%AE%A2%E5%9B%AD-%E5%BC%80%E6%BA%90%E4%B8%AD%E5%9B%BD-%E6%8E%98%E9%87%91-%E6%80%9D%E5%90%A6

![image](https://user-images.githubusercontent.com/27618687/136198722-7ce4ddb2-6cdc-42fd-98d0-fd46de983682.png)

**Comment by HEIGE-PCloud** [comment]
DoIt 的页面中使用了大量 JS 用于美化页面，图片也均使用 lazyload 加载，打印为 PDF 并非易事。为了方便编辑或分享，在文档底部可以开启阅读原始文档功能，可以直接查看[源 Markdown 文件](https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/index.md)。

所以我并不认为主题有必要提供这个功能，有“以 PDF 格式分享网页”需求（虽然我不理解为啥有这样的需求？）的同学应该使用相关脚本、浏览器插件，或者使用原始 Markdown 进行分享。

**Comment by gclm** [comment]
好的。
