### ISSUE TITLE
Incorrect indentation of gists

### ISSUE THREAD

**Issue by eyllanesc** [HEIGE-PCloud/DoIt#269]
### Describe the bug

The output of the gists do not respect indentations

### Expected behavior

Using the gist provided from Hugo's docs I get the following:

### Screenshots

Current output:

![Screenshot_20211007_042716](https://user-images.githubusercontent.com/4896200/136358045-4683043f-e156-4a4f-b86a-c6a688138243.png)

Expected output:

![Screenshot_20211007_042852](https://user-images.githubusercontent.com/4896200/136358680-0ff022e7-f2ba-446d-80b4-fec78ab63f7c.png)

The same is observed on your blog: https://hugodoit.pages.dev/theme-documentation-built-in-shortcodes/#2-gist

### Build Environment 构建环境

- OS: Arch Linux
- Theme version/commit  f22e86c
- hugo v0.88.1+extended

**Comment by HEIGE-PCloud** [comment]
It is a stylesheet issue; I have fixed it in the latest commit. Check it out [here](https://hugodoit.pages.dev/theme-documentation-built-in-shortcodes/#2-gist)!

**Comment by eyllanesc** [comment]
@HEIGE-PCloud many thanks
