### ISSUE TITLE
手机用搜索输入时输入法用不了

### ISSUE THREAD

**Issue by SourceOnce** [HEIGE-PCloud/DoIt#280]
手机上搜索时输入法弹出一下就弹回去了，包括官方文档也是

**Comment by HEIGE-PCloud** [comment]
能提供浏览器版本与手机系统版本的相关信息吗？

**Comment by HEIGE-PCloud** [comment]
https://user-images.githubusercontent.com/52968553/137639312-30b04951-bc84-46e7-bbd0-339aba3475f4.MOV

在 iOS Safari 上我没能复现这一问题，搜索栏在 Chrome 的 device emulation 中也工作正常。因此我怀疑是相关浏览器版本与兼容性造成的问题。

**Comment by SourceOnce** [comment]
安卓11，浏览器为yandex和edge，以及安卓版chrome

**Comment by SourceOnce** [comment]
https://user-images.githubusercontent.com/51945211/137656627-384b3f2f-44c6-4111-863f-fe3ebe2d8aac.mp4

三个浏览器都是这种情况

**Comment by HEIGE-PCloud** [comment]
这个搜索框就是个 `<input type="text" placeholder="{{ .Site.Params.search.placeholder }}" id="search-input-mobile">`

我手边的安卓设备上也没能复现这个问题。

能否请你先访问这个[网站](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text)，并告诉我

![image](https://user-images.githubusercontent.com/52968553/137704778-93e7f30b-428a-4f45-827e-03af30e11045.png)

这个输入框是否工作正常？

能否请你再访问这个[网站](https://hugoloveit.com/)，并告诉我它的输入框在你的设备上是否工作正常？

**Comment by SourceOnce** [comment]
这两个都是正常的。。。。就是doit的会上面那种问题，可能是手机问题😂😂

**Comment by HEIGE-PCloud** [comment]
也许换一个输入法试试看？

**Comment by HEIGE-PCloud** [comment]
也许和

```js
$searchInput.addEventListener('focus', () => {
    document.body.classList.add('blur');
    $header.classList.add('open');
}, false);
```

```js
$searchInput.addEventListener('input', () => {
    if ($searchInput.value === '') $searchClear.style.display = 'none';
    else $searchClear.style.display = 'inline';
}, false);
```

有关

**Comment by SourceOnce** [comment]
代码在哪个文件呀

**Comment by HEIGE-PCloud** [comment]
> 代码在哪个文件呀

https://github.com/HEIGE-PCloud/DoIt/blob/main/src/js/theme.js

**Comment by SourceOnce** [comment]
苹果设备都可以，我这边的安卓都不可以，不知道什么原因，代码对比loveIt也看不出什么问题。。。。

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/137875883-9ff4cf21-e357-442d-887e-d83a99dc6163.png)

我在 Chrome 和 Firefox 的 emulator 上也复现不出来... 所以还挺麻烦的.......

https://3708120f.hugodoit.pages.dev/ 能否尝试一下这个网址是否工作正常？

**Comment by SourceOnce** [comment]
哇，这个是正常的

**Comment by SourceOnce** [comment]
https://blog.gdgroups.club/
这个是我的

**Comment by HEIGE-PCloud** [comment]
可能与 #135 有关。#278 也与 #135 有关。

**Comment by SourceOnce** [comment]
请问我该如何解决这个问题

**Comment by HEIGE-PCloud** [comment]
这是最后一个正常工作的版本 https://68984a37.hugodoit.pages.dev/
这是第一个损坏版本 https://79b244b3.hugodoit.pages.dev/

这是造成问题的 commit https://github.com/HEIGE-PCloud/DoIt/commit/564cae8e955f7c8e37becc66556ceffde013894e

**Comment by HEIGE-PCloud** [comment]
应该和 `    if (!searchConfig || isMobile && window._searchMobileOnce || !isMobile && window._searchDesktopOnce) return;` 有关。

这个接近 1000 行的 `theme.js` 已经有向屎山发展的趋势了。没有注释也没有单元测试，维护的时候删一点加一点也不知道会搞坏什么东西 :/

**Comment by HEIGE-PCloud** [comment]
https://do-it-git-fix-search-pcloud.vercel.app/

麻烦帮忙测试一下 这个网址上的搜索框是否工作正常？

**Comment by SourceOnce** [comment]
工作正常
