### ISSUE TITLE
[FEATURE] About series

### ISSUE THREAD

**Issue by eyllanesc** [HEIGE-PCloud/DoIt#282]
The concept of series implies some order (typically chronological), for example, if a topic X is developed in the first post then the basic concepts will be treated and the next posts will use the basic concepts. For example you have the series[ "Getting start with DoIt"](https://hugodoit.pages.dev/series/getting-start/) with the posts where based on the title and content the order should be:

1. Theme Documentation - Basics
2. Theme Documentation - Content
3. Theme Documentation - Built-in Shortcodes
4. Theme Documentation - Extended Shortcodes

I don't understand why the first post(03-06) has a newer creation date than the others(03-05, 03-04, 03-03). It would be great if the creation date is corrected.

Now if going to the underlying problem, it would be great that the order that the posts appear must be from the oldest to the newest. Currently the order is the opposite:

![Screenshot_20211017_170326](https://user-images.githubusercontent.com/4896200/137646563-9c3b9997-3b1a-488f-ad72-378110e2050f.png)

An additional request is that in the posts that belong to a series then a list of the other posts(links) be placed in order to be able to navigate easily, for example, take the post of this blog as an example: https://kubasejdak.com/techniques-of-variadic-templates

![Screenshot_20211017_170724](https://user-images.githubusercontent.com/4896200/137646660-5ffe65de-b417-4aa7-99fb-29f4e11fb825.png)

**Comment by HEIGE-PCloud** [comment]
For the creation date issue, the DoIt theme is inherit from the [LoveIt theme](https://github.com/dillonzq/LoveIt), and these documentations come from there as well. The [creation date](https://hugoloveit.com/posts/) is set by the original author. I probably can change that to the "correct date"...?

For the order of the posts, I don't think changing it to sort from the oldest to the latest solves all problems. When you write a series of posts, you don't always start from the first one and write to the end, sometimes you might want to insert a new post in the series, or you might want to focus on the most attractive posts first. I think it is better to introduce a more flexible way of ordering the posts: [`Weight > Date > LinkTitle > FilePath`](https://gohugo.io/templates/lists/#order-content) so you can manually set the order of the posts by assigning them different weights.

The side affect of this method is that the posts will not be grouped by the years anymore.

![image](https://user-images.githubusercontent.com/52968553/137731466-5c7504f5-6944-4fab-be48-c4c209a80be3.png)

The "2020" will not show up and the date format on the right needs to be updated.

The idea of a list of other posts is great! I guess I can reuse the style of the static toc and make it something like this

![image](https://user-images.githubusercontent.com/52968553/137732532-b0f2d845-1573-4fb0-9a7b-44496b8df192.png)

**Comment by eyllanesc** [comment]
@HEIGE-PCloud  I love your ideas.

1. The weight for me is flexible and simple enough.
2. The image you provide from the post list of a series I love.
