### ISSUE TITLE
部署到 github pages上 点击阅读原始文档中文乱码

### ISSUE THREAD

**Issue by nyancccat** [HEIGE-PCloud/DoIt#287]
请问一下，本地预览网站的时候，在浏览器打开「阅读原始文档」，中文正常显示.
但部署到 pages 后，再在浏览器打开「阅读原始文档」，中文全是乱码。
本地 .md 确定是utf-8 ,主题配置文件和git提交过程基本上都排除编码问题了，可是问题依旧。

**Comment by HEIGE-PCloud** [comment]
https://github.com/dillonzq/LoveIt/issues/418

**Comment by HEIGE-PCloud** [comment]
https://developers.cloudflare.com/rules/transform/request-header-modification/create-dashboard

套 Cloudflare 也许可以解决这个问题...

**Comment by nyancccat** [comment]
> https://developers.cloudflare.com/rules/transform/request-header-modification/create-dashboard
> 
> 套 Cloudflare 也许可以解决这个问题...

最后用 netlify 部署，再用 Cloudflare 提提速，算是解决了，感谢回复，主题很棒，谢谢！

**Comment by digevil** [comment]
Same problem here while using github pages to deploy. Problem solved after deploying onto Netlify.

And the github pages team won't let you change *.md file header by far.
