### ISSUE TITLE
[BUG] giscus 首次加载显示异常

### ISSUE THREAD

**Issue by iuxt** [HEIGE-PCloud/DoIt#289]
### Describe the bug 描述你遇到的错误

使用giscus作为评论系统时，首次打开网页评论框只有线条，但是切换到黑暗模式再切换回来就正常了

### Screenshots 屏幕截图
![Screenshot_2021-10-25-10-33-54-106_com android chrome](https://user-images.githubusercontent.com/23610854/138626642-f8d8d2e9-5769-41b7-a09e-8e05a91691f9.jpg)

**Comment by iuxt** [comment]
另外还有个问题，就是开启了giscus会影响文章的修改日期（修改日期都变成了今天），换回其他的评论系统就没有这个问题了。

**Comment by HEIGE-PCloud** [comment]
我已经提交了一个 commit 修复了默认主题的问题。https://github.com/HEIGE-PCloud/DoIt/commit/a64d476f112439e8de09f797a5e87bca42895ae8

修改日期的问题我没能复现。能不能提供一个最小复现 demo？

![image](https://user-images.githubusercontent.com/52968553/138656421-00f957d2-dbd7-40d9-b974-fd453df0454f.png)

**Comment by iuxt** [comment]
感谢大佬，lastmod 时间变动问题确实存在，但是目前还不确定是怎么复现的，等我再看看
