### ISSUE TITLE
[BUG] 模版报错：parse failed: ttemplate: partials/meta/author.html:8: unclosed action

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#290]
### 执行 hugo new /posts/test.md  或  hugo server -D 这两个命令时报错，提示如下：
/themes/DoIt/layouts/partials/meta/author.html:8:1": parse failed: template: partials/meta/author.html:8: unclosed action

注：我的 config.toml 配置文件中的 主题目录配置为：themesDir = "./themes/DoIt"

### Expected behavior 期待的行为
请修复该错误，谢谢！

### Build Environment 构建环境
- OS: [macOS 11.6 (20G165)]
- Theme version/commit [v0.2.12, 8f53f73]
- Hugo version [v0.80.0]

**Comment by HEIGE-PCloud** [comment]
请尝试升级你的 hugo 版本，然后再试一次。DoIt 仅对 0.83 及以上版本的 hugo [提供支持](https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#1-%E5%87%86%E5%A4%87).

**Comment by ghost** [comment]
> 请尝试升级你的 hugo 版本，然后再试一次。DoIt 仅对 0.83 及以上版本的 hugo [提供支持](https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#1-%E5%87%86%E5%A4%87).

OK!
