### ISSUE TITLE
[FEATURE] 请求让 HTML 的 <img> 标签与 lightgallery 的适配；分页Bug；年月日对齐；文章底部的Back无效

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#291]
### 请求让 HTML 的 <img> 标签与 lightgallery 的适配；分页Bug；年月日对齐；文章底部的Back无效

- Feature 1 ：为了能自定义图片大小，我在原来的[博客主题Even](https://hugo-theme-even.netlify.app)中可以使用 Html 的 \<img> 标签中的一些属性来控制。（Even主题里使用了 fancybox 来全屏展示图片）
但现在 DoIt 主题中，得不到 lightgallery 特性的支持了，也就是：**鼠标不能点击图片进行全屏阅览**。
例如：\<img src="/img/test.jpg" style="width:40%; height:40%; display:block; margin:0 auto" title="test"/> ，这样的话就可以在页面中把图片缩放为40%的展示效果。但在 DoIt 中却得不到 lightgallery 特性的支持。
如果使用MarkDown的标记：\!\[test]\(/img/test.jpg) ，这样的话可以得到 lightgallery 的支持，但却又不能自定义缩放，图片在页面里很大，体验看着不协调。
**我希望这个功能解决，谢谢！**

- Feature 2：在 All Categories 页面里，我有一个 “分类A”，页面显示出了分页，并且分了两页。但我的“分类A” 有13条内容在第一页已经全部显示出来了，但却还显示出 第二页 的分页数字“2”，点击第二页的数字“2”后效果和第一页的展示完全一致。所以这个**分页应该有问题**。在第一页完全展示后，不应该出现第二页的分页角标。
**我希望这个功能解决，谢谢！**

- Feature 3：在 All Posts 和 Categories 页面中，展示的 **年月日 没有对齐**，如下图：
<img width="154" alt="Screenshot 2021-10-25 at 20 29 57" src="https://user-images.githubusercontent.com/29486126/138695537-bb958098-c05f-4269-84ee-0d382056ed1b.png">

<img width="128" alt="Screenshot 2021-10-25 at 20 29 32" src="https://user-images.githubusercontent.com/29486126/138695718-b21ac459-6b2b-4320-b03b-10f6e1bc3269.png">

**我希望这个功能解决，谢谢！**

- Feature 4：文章底部的 “Back” 无效
在点击 “Back” 后，没有任何反应

### 有价值的参考
<img width="373" alt="Screenshot 2021-10-25 at 20 35 36" src="https://user-images.githubusercontent.com/29486126/138696878-b8043194-e3fe-4694-9dab-7102fc3d0b1b.png">

以上，都可以参考[博客主题Even](https://hugo-theme-even.netlify.app/post/)

综上，我希望目前这四个问题能够得到支持解决，谢谢！
也希望与你一起交流！

**Comment by HEIGE-PCloud** [comment]
1. 请通过 [image shortcode](https://hugodoit.pages.dev/zh-cn/theme-documentation-extended-shortcodes/#image) 自定义图片的大小

![image](https://user-images.githubusercontent.com/52968553/138772809-f26f6cb4-b406-4de8-ab7e-d7409b29d725.png)

```
{{< image src="/images/lighthouse.webp" caption="Lighthouse (`image`)" src_s="/images/lighthouse-small.webp" src_l="/images/lighthouse-large.webp" >}}

{{< image height="40%" width="40%" src="/images/lighthouse.webp" caption="Lighthouse (`image`)" src_s="/images/lighthouse-small.webp" src_l="/images/lighthouse-large.webp" >}}
```
2. 修了 https://github.com/HEIGE-PCloud/DoIt/commit/d4339bda8be43af63acc97fff419c335fd1ecd86 

在 #286 里引入了这个问题。

3. 未能复现，我怀疑是字体或者兼容性的问题。在我的浏览器中，这个[页面](https://hugodoit.pages.dev/posts/)长这样。

![image](https://user-images.githubusercontent.com/52968553/138773158-9f4abc5d-7c08-47f4-bf83-1744243bfb56.png)

4. 修了 https://github.com/HEIGE-PCloud/DoIt/commit/c13b40019ba70808e6983e198b0a1340679c49b9

back 无法返回是因为它的 href 被设置为了 `#`，将其修改为 `javascript:void(0);` 后应该可以提供更好的兼容性。

**Comment by ghost** [comment]
> 1. 请通过 [image shortcode](https://hugodoit.pages.dev/zh-cn/theme-documentation-extended-shortcodes/#image) 自定义图片的大小
> 
> ![image](https://user-images.githubusercontent.com/52968553/138772809-f26f6cb4-b406-4de8-ab7e-d7409b29d725.png)
> 
> ```
> {{< image src="/images/lighthouse.webp" caption="Lighthouse (`image`)" src_s="/images/lighthouse-small.webp" src_l="/images/lighthouse-large.webp" >}}
> 
> {{< image height="40%" width="40%" src="/images/lighthouse.webp" caption="Lighthouse (`image`)" src_s="/images/lighthouse-small.webp" src_l="/images/lighthouse-large.webp" >}}
> ```
> 
>  1. 修了 [d4339bd](https://github.com/HEIGE-PCloud/DoIt/commit/d4339bda8be43af63acc97fff419c335fd1ecd86)
> 
> 在 #286 里引入了这个问题。
> 
> 1. 未能复现，我怀疑是字体或者兼容性的问题。在我的浏览器中，这个[页面](https://hugodoit.pages.dev/posts/)长这样。
> 
> ![image](https://user-images.githubusercontent.com/52968553/138773158-9f4abc5d-7c08-47f4-bf83-1744243bfb56.png)
> 
> 1. 修了 [c13b400](https://github.com/HEIGE-PCloud/DoIt/commit/c13b40019ba70808e6983e198b0a1340679c49b9)
> 
> back 无法返回是因为它的 href 被设置为了 `#`，将其修改为 `javascript:void(0);` 后应该可以提供更好的兼容性。



您好，非常感谢！我已经pull了新的代码，OK了。

对于以上问题：

1. 年月日不对齐，我的环境是 mac OS 11.6，Safari浏览器：Version 15.0 (16612.1.29.41.4, 16612)，确实是没有对齐。另外，我在mac OS 上用 Chrome 和 Firefox 也都是不能对齐的。还有我在手机上的浏览器也试过，同样不能对齐。（建议你兼容，可以参考[博客主题Even](https://hugo-theme-even.netlify.app/post/) ，以及它的样式，日期统一在左侧，列表之间有连接线，鼠标悬停在上面时有浮动的效果，这样也好跟 DoIt 主题的一些动态效果适配，整体的体验会更好些！）
2. 代码框在鼠标点击时，左侧行号的位置会出现一条竖线，再点一次就消失，再继续点有复现。（建议修复）如下图：
<img width="156" alt="Screenshot 2021-10-26 at 15 37 09" src="https://user-images.githubusercontent.com/29486126/138830497-003e4ddc-4920-446b-9559-ac89fc05256b.png">

3. 页面的字体和颜色，我在使用两天后，感觉DoIt主题字体看起来视觉效果上容易疲劳，也不太协调，主要是太粗、太黑。建议字体和字体颜色做改进，可以参考[这个博客主题](https://www.haomwei.com) 。如下图：
<img width="1096" alt="Screenshot 2021-10-26 at 15 20 29" src="https://user-images.githubusercontent.com/29486126/138828328-93b00146-f059-4de8-986e-1f00ee10fb80.png">
<img width="1117" alt="Screenshot 2021-10-26 at 15 20 43" src="https://user-images.githubusercontent.com/29486126/138828381-a82ccfbc-b66d-45cf-b7c8-bcc1ae3cc7a1.png">

4. 建议 Categories 中也加上数字角标显示该类别下的文章数量，就像Tags里的那样很好。
5. 如何在 hugo server -D 的状态下，展示评论系统？我想随时都可以预览评论系统，在哪里配置呢？

期待答复，交流，谢谢！

**Comment by HEIGE-PCloud** [comment]
5. 请运行 `hugo server -D -e production` 来启用评论区。

感谢你的建议，能否请你将它们拆分成单独的 issue 以便于讨论和跟踪，谢谢。

**Comment by ghost** [comment]
> 1. 请运行 `hugo server -D -e production` 来启用评论区。
> 
> 感谢你的建议，能否请你将它们拆分成单独的 issue 以便于讨论和跟踪，谢谢。

非常感谢！
我已经拆分成单独的issue
