### ISSUE TITLE
[FEATURE] 年月日的对齐样式

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#294]
### 年月日的对齐样式

- 在 All Posts 和 Categories 页面中，展示的 年月日 没有对齐，如下图：
<img width="154" alt="Screenshot 2021-10-25 at 20 29 57" src="https://user-images.githubusercontent.com/29486126/139010328-ebcaaf92-4cf0-4774-a338-10858ceff931.png">
<img width="128" alt="Screenshot 2021-10-25 at 20 29 32" src="https://user-images.githubusercontent.com/29486126/139010414-9262d559-3f38-4a31-8eed-44a03ee349f1.png">
我的环境是 mac OS 11.6，Safari浏览器：Version 15.0 (16612.1.29.41.4,16612) ，确实是没有对齐。另外，我在mac OS 上用 Chrome 和 Firefox 也都是不能对齐的。还有我在手机上的浏览器也试过，同样不能对齐。
**我希望这个功能解决**

### 有价值的参考
https://hugo-theme-even.netlify.app
建议你兼容，可以[参考博客主题Even](https://hugo-theme-even.netlify.app/post/) ，以及它的样式，日期统一在左侧，列表之间有连接线，鼠标悬停在上面时有浮动的效果，这样也好跟 DoIt 主题的一些动态效果适配，整体的体验会更好些！

**Comment by HEIGE-PCloud** [comment]
没有对齐也是一个字体的问题，使用一个等宽的字体它就能对齐了。和 #296 可以一起处理。

动画就不加了，没什么必要，也避免破坏 `<a>` tag hover 样式的一致性。

**Comment by HEIGE-PCloud** [comment]
我在这个 commit https://github.com/HEIGE-PCloud/DoIt/commit/17f5b11ee925da9dfcd41286ca5753c16a9f3913 中提交了一个修复

麻烦你访问 https://hugodoit.pages.dev/posts/ 现在日期是否已经对齐？

**Comment by ghost** [comment]
PC端，我在mac OS下三个浏览器看了，OK！

在手机端，看是这样的：
![original-9f6b36d3-d3d7-427c-8a7f-95bccf458cb7](https://user-images.githubusercontent.com/29486126/139256992-b407179f-88f8-46d6-8da7-50a823f1cd2e.jpeg)

![original-ac0e7311-38b1-40fa-9d92-d7459bb719f7](https://user-images.githubusercontent.com/29486126/139257035-12a32e0b-41d8-4a35-8662-5129d8d44597.jpeg)

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/139274911-01a34091-06a4-439e-bbf4-a2aa6b40151f.png)

Overflow 现在可以被正确处理。

**Comment by ghost** [comment]
Nice 👌

**Comment by ghost** [comment]
> ![image](https://user-images.githubusercontent.com/52968553/139274911-01a34091-06a4-439e-bbf4-a2aa6b40151f.png)
> 
> Overflow 现在可以被正确处理。

您好，
中文字体的文章标题，或者中英文混合文章标题，一旦长度足够长的话，在手机浏览器上显示的仍然不能对齐日期。希望再优化一下吧，谢谢！

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/139459077-6f7a3651-c22e-4da7-89ef-3764b43cfa18.png)

没能复现。

**Comment by ghost** [comment]
> ![image](https://user-images.githubusercontent.com/52968553/139459077-6f7a3651-c22e-4da7-89ef-3764b43cfa18.png)
> 
> 没能复现。

sorry，是我的手机浏览器缓存导致。
没问题了。
谢谢！
