### ISSUE TITLE
[FEATURE] 代码框在鼠标点击时，左侧行号的位置会出现一条竖线

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#295]
### 代码框在鼠标点击时，左侧行号的位置会出现一条竖线

- 代码框在鼠标点击时，左侧行号的位置会出现一条竖线。当鼠标点击在行号的位置上时，竖线会右移。影响体验，如下图：
<img width="540" alt="Screenshot 2021-10-27 at 14 25 51" src="https://user-images.githubusercontent.com/29486126/139011598-604f7ec0-19e6-43a7-9fd9-79121d1c2ecc.png">
  
<img width="540" alt="Screenshot 2021-10-27 at 14 26 24" src="https://user-images.githubusercontent.com/29486126/139011613-80da5c05-cd6c-4516-afa0-d29c37aa431a.png">

我希望这个功能解决

**Comment by HEIGE-PCloud** [comment]
这个所谓“竖线”其实是一个选择框。它由 `<pre>` tag 的 `tabindex=0` 属性触发。这个属性在 [Hugo 0.86](https://gohugo.io/news/0.86.0-relnotes/#other) 中引入。https://github.com/gohugoio/hugo/commit/f27e542442d19436f1428cc22bb03aca398d37a7

**Comment by HEIGE-PCloud** [comment]
它本来的作用是向键盘用户提供无障碍访问，使用 Tab 可以正确选中 `<pre>` tag 中的内容。在 Windows 下，点击代码框并不会有任何提示，使用 Tab 键浏览可以显示一个选择框。

![image](https://user-images.githubusercontent.com/52968553/139053576-d38de1b1-5b62-4a8b-a4ff-396046afa7c3.png)

在 Mac 下，点击包含这一属性的 `pre` tag 就会触发这个蓝色选择框。这一行为在 Hugo 的官网上也得到了复现。

![IMG_3584](https://user-images.githubusercontent.com/52968553/139053828-c48f2968-f502-4874-a998-8ced6466469c.PNG)

**Comment by HEIGE-PCloud** [comment]
我不打算移除 tabindex 属性，也许我可以少许调整一些样式，让这个蓝色框显示完整。

**Comment by ghost** [comment]
知道了。
有没有优化的可能？

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/139281803-e201584e-c88e-4265-ad92-a129306fbf02.png)

现在这个选择框会被显示完整。

**Comment by ghost** [comment]
好的。
