### ISSUE TITLE
[FEATURE] 页面的字体和颜色

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#296]
### 页面的字体和颜色，我在使用两天后，感觉DoIt主题字体看起来视觉效果上容易疲劳，也不太协调，主要是太粗、太黑。建议字体和字体颜色做改进，建议参考这个博客主题 ：https://www.haomwei.com

- 首页的文章标题、文章正文的文章标题、正文的字体、分类页面、标签页面 都建议优化
  正文字体大小建议 15px 或 16px
  我希望这个功能解决 ...
- 以上字体的颜色，不建议颜色太深，因为 DoIt 主题本身就是保持了简洁的整体风格，如果字体太粗，颜色太深，会影响整体的风格。
  我希望这个功能解决 ...

### Useful reference 有价值的参考
https://www.haomwei.com

如下图：
<img width="1096" alt="Screenshot 2021-10-26 at 15 20 29" src="https://user-images.githubusercontent.com/29486126/139013019-c9f7dac7-7ce3-4706-8d63-60708f6055a8.png">

<img width="1117" alt="Screenshot 2021-10-26 at 15 20 43" src="https://user-images.githubusercontent.com/29486126/139013068-ddd7e9bd-7848-416a-b7b7-2ebecb76e32c.png">

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/139246047-fb7d62a6-fb03-4237-a9a2-f9100447fdcd.png)

正文字体大小本来就是 16px......

![image 1](https://user-images.githubusercontent.com/52968553/139246678-bbf39d63-7dcd-4bd3-b9f4-dee052e25f9d.png)

![image 2](https://user-images.githubusercontent.com/52968553/139246721-2a79f8ef-ece2-4f76-b140-2917bc62b78d.png)

你认为图一和图二中哪个字体更好看一些呢？

**Comment by HEIGE-PCloud** [comment]
对于字体与可读性，每个人有着自己的偏好。DoIt 通过提供[自定义样式](https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#33-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)使用户可以随心所欲地自定义自己的博客，选择自己心仪的字体，调整大小以及颜色。

通过创建 `your_site\assets\css\_override.scss` 并在其中覆盖原本的字体变量

```css
$global-font-family: PingFangSC-Regular,Helvetica,"Helvetica Neue","Segoe UI","Hiragino Sans GB","Source Han Sans CN","Microsoft YaHei",STHeiti,"WenQuanYi Micro Hei",sans-serif;
$global-font-size: 15px;
$global-font-color: #444;
```

便可将字体设定为你喜欢的样式。所有可以修改的变量均可在 https://github.com/HEIGE-PCloud/DoIt/blob/main/assets/css/_variables.scss 找到。
上方的示例中使用了 www.haomwei.com 中的字体，大小以及颜色。

![image](https://user-images.githubusercontent.com/52968553/139252010-e798b39d-5702-47ce-88e4-e4a8a6ef0a84.png)

**Comment by ghost** [comment]
您好！
我个人偏向 **第一张图** 中的字体。**第一张图** 中的字体在中、英、数字 三类看起来都可以的。

但是，现在的字体为什么 中文汉字 下的标点符号，句号和逗号看起来都像是英文状态下的，图一和图二都这样。

中文状态下的句号是个小圆圈，这样应该好一些。
<img width="474" alt="Screenshot 2021-10-28 at 19 52 39" src="https://user-images.githubusercontent.com/29486126/139250827-79317f8d-53c3-4c5d-9842-d407e4178b08.png">

**Comment by ghost** [comment]
> 对于字体与可读性，每个人有着自己的偏好。DoIt 通过提供[自定义样式](https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#33-%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)使用户可以随心所欲地自定义自己的博客，选择自己心仪的字体，调整大小以及颜色。
> 
> 通过创建 `your_site\assets\css\_override.scss` 并在其中覆盖原本的字体变量
> 
> ```css
> $global-font-family: PingFangSC-Regular,Helvetica,"Helvetica Neue","Segoe UI","Hiragino Sans GB","Source Han Sans CN","Microsoft YaHei",STHeiti,"WenQuanYi Micro Hei",sans-serif;
> $global-font-size: 15px;
> $global-font-color: #444;
> ```
> 
> 便可将字体设定为你喜欢的样式。所有可以修改的变量均可在 https://github.com/HEIGE-PCloud/DoIt/blob/main/assets/css/_variables.scss 找到。 上方的示例中使用了 [www.haomwei.com](http://www.haomwei.com) 中的字体，大小以及颜色。
> 
> ![image](https://user-images.githubusercontent.com/52968553/139252010-e798b39d-5702-47ce-88e4-e4a8a6ef0a84.png)

好的，明白！谢谢！
