### ISSUE TITLE
[FEATURE] 页面右下脚返回顶部的小火箭效果

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#298]
### 页面右下脚返回顶部的小火箭，建议点击后有一个上滑的缓慢过程，而不是一点击就立即跳转回顶部，这样体验会更好

建议这两个参考：
https://www.haomwei.com
https://hugo-theme-even.netlify.app

**Comment by HEIGE-PCloud** [comment]
相比于加载额外的 js，DoIt 使用原生的 [CSS smooth scroll](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) 来提供滚动。这一特性受到绝大多数主流浏览器的支持，但 Safari 用户需要手动开启这一特性。

![image](https://user-images.githubusercontent.com/52968553/139024195-78c3d681-e138-4215-b31d-0745d6f9a762.png)

我并不打算单独为 IE 和 Safari 用户适配特殊的滚动效果。

**Comment by ghost** [comment]
明白了。
我想学习一下 Safari 如何手动开启？我不懂前端，谢谢！

**Comment by HEIGE-PCloud** [comment]
抱歉，我不用 Mac OS，但是以下是我使用搜索引擎为你找到的答案。

https://mil-tokyo.github.io/webdnn/docs/tips/enable_webgpu_macos.html

**Comment by ghost** [comment]
非常感谢！
我在Safari里并没有看到上文中说的 “WebGPU” 这个字眼的选项。
这个问题就到这吧，暂时不关注该问题了。

**Comment by HEIGE-PCloud** [comment]
你需要开启的是 CSSOM View Smooth Scrolling 选项。
