### ISSUE TITLE
A possible friend links layout

### ISSUE THREAD

**Issue by wu-yue-yu** [HEIGE-PCloud/DoIt#30]
I also copy from other guys, but I forget to save the author's link. If there's infringement, please tell me, since I can't contact with the author.
[My friend links webpage](https://www.summerfire.cn/friend/)

**Comment by wu-yue-yu** [comment]
Oh, I guess I find it.
I copied the layout from [here](https://blog.233so.com/2020/04/friend-link-shortcodes-for-hugo-loveit/)

**Comment by HEIGE-PCloud** [comment]
Check it out at this [page](https://776ed259.hugodoit.pages.dev/friend-link-tests/), try different color theme and mobile/desktop view, tell me what you think~😆
