### ISSUE TITLE
[FEATURE] 鼠标点击菜单后，下方的一块区域出现阴影，查看录屏

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#304]
### 鼠标点击菜单后，下方的一块区域出现阴影，查看录屏：

https://user-images.githubusercontent.com/29486126/139254407-b20c1a06-b82a-4655-ac66-2d844baa03a6.mov

### 有价值的参考
但是，在该站点中却没有复现：https://planet-cloud.fun
什么问题呢？

**Comment by ghost** [comment]
mac OS 上的三个浏览器都这样。
并且在手机端也复现。

**Comment by HEIGE-PCloud** [comment]
在 https://hugodoit.pages.dev/ 上能复现吗？

**Comment by ghost** [comment]
> 在 https://hugodoit.pages.dev/ 上能复现吗？

这个在mac OS 下三个浏览器，以及手机端 都没问题。

不知道我的版本为什么导致那样的效果。一开始我以为就是这个特效，对比你的以后才发现了问题。

**Comment by HEIGE-PCloud** [comment]
是否对主题做过任何自定义修改？或者请提供一个最小可复现 demo 方便排查。
