### ISSUE TITLE
[BUG] 友链样式错乱

### ISSUE THREAD

**Issue by youngxhui** [HEIGE-PCloud/DoIt#308]
### Describe the bug 描述你遇到的错误

友链样式错乱

如果友链不填写 “描述”，样式会发生错乱。

### Expected behavior 期待的行为

可以正常对齐

### Screenshots 屏幕截图

错乱样式

![image](https://user-images.githubusercontent.com/16971804/139355289-ed120e88-b453-4b42-8083-75c3cc3c0ed4.png)

[https://youngxhui.top/links/](https://youngxhui.top/links/)

填写描述后

![image](https://user-images.githubusercontent.com/16971804/139355866-7783c773-ed9a-48f8-9c16-e782b57a524d.png)

可以正常对齐

### Build Environment 构建环境

- OS: Linux
- Theme version/commit: ed3341d31cde09006b80de6e3d03ac36c65cb9d2
- Hugo version: hugo v0.88.1-5BC54738+extended linux/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

### Preview Environment 预览环境

- OS: [windows11]
- Browser [edge, firefox]

### Additional Information 补充信息

Configuration files or front matter code...
配置文件或者前置参数的代码...

**Comment by HEIGE-PCloud** [comment]
Related to https://discourse.gohugo.io/t/shortcodes-and-p-tags/2164/3
