### ISSUE TITLE
[FEATURE] Add multiple improvements

### ISSUE THREAD

**Issue by digitaltwinz** [HEIGE-PCloud/DoIt#321]
**- Feature 1: Custom headers**
  I want this feature to enable custom headers. Please see the Cloudflare blog post [here](https://blog.cloudflare.com/custom-headers-for-pages/). Links for testing and example is given below.
  
**- Feature 2: Early hints and asset preloading**
  I want this feature to speed page loading by preloading assets. More information is [here](https://blog.cloudflare.com/early-hints/) or [here](https://mathieuhendey.com/2020/10/bundling-and-preloading-hugo-assets/).

**- Feature 3: SEO**
  I want this feature to improve SEO by adding relevant meta tags in the code. More information is [here](https://mathieuhendey.com/2020/10/seo-for-hugo-blogs/).

 ### Useful reference 
https://blog.cloudflare.com/custom-headers-for-pages
https://securityheaders.com for testing (example: https://securityheaders.com/?q=https%3A%2F%2Fhitrobotics.com%2F)
https://blog.cloudflare.com/early-hints
https://mathieuhendey.com/2020/10/bundling-and-preloading-hugo-assets
https://mathieuhendey.com/2020/10/seo-for-hugo-blogs/

**Comment by eyllanesc** [comment]
@digitaltwinz For **Feature 1**: https://gohugo.io/news/0.67.0-relnotes. 

The theme has nothing to do with that feature so you can implement it by adding the config.toml. Instead, you could ask that these fields be added to the config.toml of exampleSite.

**Comment by HEIGE-PCloud** [comment]
For Feature 2, I have created an issue to track its progress #323 

For Feature 3, DoIt has already optimized for SEO. See 

https://github.com/HEIGE-PCloud/DoIt/blob/main/layouts/partials/head/seo.html

https://github.com/HEIGE-PCloud/DoIt/blob/main/layouts/partials/head/meta.html

**Comment by digitaltwinz** [comment]
Thank you both for your replies and links!
