### ISSUE TITLE
[FEATURE] Edit this page

### ISSUE THREAD

**Issue by eyllanesc** [HEIGE-PCloud/DoIt#322]
### Describe the feature you want

- Feature 1: It would be great to add a link or button where clicking on the source code file is linked so that it can be edited similar to what is shown in readthedocs.io:

![Screenshot_20211031_025741](https://user-images.githubusercontent.com/4896200/139573712-3978fe6c-a5d6-40b4-a08f-deedb0be7f04.png)

It should go in the bottom section where it says "Read Markdown" or next to the commit hash:

![Screenshot_20211031_030757](https://user-images.githubusercontent.com/4896200/139573976-dd8f7e4b-78f6-402c-8916-81aa96a780c2.png)

The url should be configurable in config.toml:

```toml
edit_url = "https://github.com/HEIGE-PCloud/DoIt"
```

Also you might need more information to generate the url, for example mkdocs adds the edit_uri parameter: https://www.mkdocs.org/user-guide/configuration/#edit_uri

For example for the post: `https://hugodoit.pages.dev/basic-markdown-syntax` the link should be `https://github.com/HEIGE-PCloud/DoIt/edit/main/exampleSite/content/posts/basic-markdown-syntax/index.en.md` from which it follows that 3 parameters are needed:

- repo_url: `https://github.com/HEIGE-PCloud/DoIt`
- edit path: `edit/main`
- relative path: `exampleSite/content/posts/basic-markdown-syntax/index.en.md`

FORMAT: `{repo_url}/{edit_path}/{relative_path}`

In bitbucket the format is: `https://bitbucket.org/user/repo/src/master/{filename}?mode=edit`

so the most generic thing should be:

FORMAT: `{repo_url}/{pre}/{relative_path}/{pos}`

Maybe you should use the "gitRepo" field and add the extra fields under "params":

https://github.com/HEIGE-PCloud/DoIt/blob/731d671d5532b21e2d2556984aa9a2d9f1a58d53/exampleSite/config.toml#L505-L531

### Useful reference

- https://discourse.gohugo.io/t/how-to-implement-edit-this-page-on-github/1166
- https://docs.readthedocs.io/en/stable/guides/remove-edit-buttons.html
- https://www.mkdocs.org/user-guide/configuration/#edit_uri

**Comment by HEIGE-PCloud** [comment]
I think I can use the same approach as `Template` in social.yml

https://github.com/HEIGE-PCloud/DoIt/blob/95f0401aa6e87d0f0fb972b0c3fbfc0d4e7ca98d/assets/data/social.yml#L89-L95

The user sets up one field

```toml
edit_path = "https://github.com/HEIGE-PCloud/DoIt/edit/main/%v"
# https://bitbucket.org/user/repo/src/master/%v?mode=edit
# https://gitlab.com/user/repo/-/edit/master/%v
```

and `%v` will be replaced by `relative_path` using [`printf`](https://gohugo.io/functions/printf/).

**Comment by eyllanesc** [comment]
@HEIGE-PCloud You are great, I love your idea
