### ISSUE TITLE
[BUG] 404页中的 返回 “手指” 按钮无效

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#324]
定位到了 # 号

**Comment by HEIGE-PCloud** [comment]
Safari is the new IE with weird behaviors all over the places.

**Comment by HEIGE-PCloud** [comment]
https://stackoverflow.com/questions/10223809/in-mobile-devices-safari-a-href-onclick-return-false-doesnt-work-why

**Comment by ghost** [comment]
OK
