### ISSUE TITLE
修改菜单 “Posts” 的名称为 “Archives” 之后，在页面中名称不统一

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#331]
当我在 config.toml 文件中修改菜单 “Posts” 的名称为 “Archives” 之后，在页面中名称还是 “All Posts” 。

如下图：

<img width="312" alt="Screenshot 2021-10-31 at 12 21 27" src="https://user-images.githubusercontent.com/29486126/139567594-1c15fff7-4c31-4eed-bc56-6756fb1a89ec.png">

<img width="305" alt="Screenshot 2021-10-31 at 12 21 54" src="https://user-images.githubusercontent.com/29486126/139567599-8cca4f38-244e-4ebe-9b8a-c5743ba4be4b.png">

_Originally posted by @real-nicholas in https://github.com/HEIGE-PCloud/DoIt/discussions/320_

**Comment by HEIGE-PCloud** [comment]
页面中名称统一使用分类的名称，与菜单中的设置无关。
