### ISSUE TITLE
[FEATURE] 建议：设置 pageStyle = "wide" ，并开启 目录 后，请保持页面样式统一

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#332]
### 设置 pageStyle = "wide" 后，如果文章开启了右侧的目录，页面样式不统一

在config配置文件中，设置 **pageStyle = "wide"** 后：
对于没有目录的页面：效果居中；
对于有目录的页面：会被 右侧目录 挤到左侧。
被挤到左则的 DIV：
```
<article class="page single">
    <div class="content" id="content" lg-uid="lg0"></div>
    <div class="post-footer" id="post-footer"></div>
</article>
```
当这 两种 页面互相切换时，视觉上会有明显的交叉感，影响用户体验。
建议：右侧的目录，不要影响页面的居中效果。

### 有价值的参考
可以参考主题 Even （https://github.com/olOwOlo/hugo-theme-even）
没有目录：https://olowolo.com/post/google-doodle-kids-coding-collect-carrots-solution/
有目录：https://olowolo.com/post/new-mybatis-dynamic-sql/
这个主题，在有目录 ，没有目录时都保持了页面居中的统一样式。

**Comment by HEIGE-PCloud** [comment]
这是 wide 且开启目录的样式

![image](https://user-images.githubusercontent.com/52968553/140284547-1129c8cf-eb3f-405a-a8c7-a612478392eb.png)

你希望不开启目录时它长啥样？这样？

![image](https://user-images.githubusercontent.com/52968553/140284728-f287593b-cd1e-4de8-b8c2-31312711fd1b.png)

既保持目录又保持 wide 又保持居中是不可能的，因为那种样式叫做 normal。

![image](https://user-images.githubusercontent.com/52968553/140284931-ea17b719-f933-48d8-b423-5fb679d2babc.png)

**Comment by ghost** [comment]
是我没有表达清楚。

下面用 test-1 和 test-2 两篇文章的页面对比说明：
1、config 配置开启 pageStyle = "wide"
2、test-1 是一篇有目录的文章，目录标题字号为 H2
3、test-2 是一篇**没有**目录的文章，正文字号为 15px。（test-2 的 toc: false ，不让它显示右侧的目录框，因为它本身没有目录）

我的意思是：当用户在 test-1 和 test-2 两个页面互相切换时，页面上内容的宽度看起来不统一（看起来就像 test-1 不居中，test-1 的文章标题的位置已经左移到 “DoIt” 的 logo 的正下方了）。

两个页面 来回切换 的录屏效果：

https://user-images.githubusercontent.com/29486126/140305865-b46608d7-67fc-4b40-be9e-3bc469f81ba2.mov




如果从你前端专业的角度，你认为我说的不对 或 没有必要优化，请无视！
