### ISSUE TITLE
[FEATURE] Banner

### ISSUE THREAD

**Issue by eyllanesc** [HEIGE-PCloud/DoIt#335]
### Describe the feature you want

- Banner: In some circumstances it is required to notify users of something because it would be nice to provide a banner. That banner should show up at the top of the topbar as shown in [mkdocs-material](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#version-warning):

![](https://squidfunk.github.io/mkdocs-material/assets/screenshots/version-warning.png)

but it should also have a button to close the banner and not show up again like in StackOverflow.

![](https://i.stack.imgur.com/GhtJI.png)

**Comment by eyllanesc** [comment]
The logic should be the same as the cookie consent.

**Comment by HEIGE-PCloud** [comment]
I doubt how many people will use it, but here is an example that might help.

https://codepen.io/matswainson/pen/PGrqGG
