### ISSUE TITLE
[FEATURE] 功能建议：在文章下方 添加 版权信息 栏

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#338]
### 建议：在文章下方添加版权信息栏
可由用户自己在 config 文件中配置 是否开启 版权信息栏。

### 有价值的样式参考：

<img width="841" alt="https::www heson10 com:posts:3217 html" src="https://user-images.githubusercontent.com/29486126/140602774-fc8f8c02-81b1-4db7-934c-36b83efe7826.png">

**Comment by HEIGE-PCloud** [comment]
http://hugodoit.pages.dev/zh-cn/theme-documentation-content/#front-matter

目前已经通过 license front matter 支持了这一功能，但是没有提供默认模板

欢迎提交 pr

**Comment by ghost** [comment]
默认模板？
你指的是 HTML ，CSS 样式？
还是其他什么呢？

**Comment by eyllanesc** [comment]
@HEIGE-PCloud I think it could be placed in the upper section of the post like the FeelIt theme does(see [example](https://khusika.com/hello-world/)):

![Screenshot_20211107_164822](https://user-images.githubusercontent.com/4896200/140663055-0960bd53-3d4c-4fbb-b2eb-1f760c2f9f82.png)

In that them the license is established using(see [here](https://raw.githubusercontent.com/khusika/khusika.github.io/master/content/posts/hello-world/index.en.md)):

```md
license: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
```

I think it is simple and elegant, not breaking the style of the theme.

**Comment by ghost** [comment]
对于文章的版权信息栏，是否可以考虑几点：

1、直接通过 config 配置 Copyright = true / false 来全局控制是否显示出版权信息栏。
展示内容包括：
作者名称
本文链接
版权授权协议（如CC BY-NC-SA 4.0）

2、博主的原创（没有引用其他人的文章）：
这情况，直接由 Copyright = true / false 来展示。

3、博主引用了其他人的文章内容，或纯粹的转载他人内容：
这种情况，可以在 Front Matter 中单独为该文章配置额外的版权引用说明。
主要是添加被引用人的文章链接（如果引用多个人的文章，可以是一个数组，如 referlinked: ["", ""]）

内容包括：
作者名称
本文链接
版权授权协议（如CC BY-NC-SA 4.0）
被引用人的文章链接

**Comment by HEIGE-PCloud** [comment]
@real-nicholas 为啥要把引用放在版权信息栏里？引用应该使用 [Markdown 脚注语法](https://hugodoit.pages.dev/zh-cn/basic-markdown-syntax/#12-%E8%84%9A%E6%B3%A8)来正确标注。

作者名称和本文链接都是页面上已经有的信息，为什么需要在“版权信息”里重复一遍？

> @HEIGE-PCloud I think it could be placed in the upper section of the post like the FeelIt theme does(see [example](https://khusika.com/hello-world/)):
> 
> ![Screenshot_20211107_164822](https://user-images.githubusercontent.com/4896200/140663055-0960bd53-3d4c-4fbb-b2eb-1f760c2f9f82.png)
> 
> In that them the license is established using(see [here](https://raw.githubusercontent.com/khusika/khusika.github.io/master/content/posts/hello-world/index.en.md)):
> 
> ```lisp
> license: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
> ```
> 
> I think it is simple and elegant, not breaking the style of the theme.

我认为这个解决方案是比较好的，但是需要把链接和名字设为单独的配置项，避免在设置项中出现 HTML。

**Comment by ghost** [comment]
@HEIGE-PCloud 

> @real-nicholas 为啥要把引用放在版权信息栏里？引用应该使用 [Markdown 脚注语法](https://hugodoit.pages.dev/zh-cn/basic-markdown-syntax/#12-%E8%84%9A%E6%B3%A8)来正确标注。
> 
> 作者名称和本文链接都是页面上已经有的信息，为什么需要在“版权信息”里重复一遍？
> 
1、最开始，我是提议把 版权信息 放到文章下方的位置。（我一开始也不知道 Front Matter 中有 license 参数可以把版权显示在文章头部）

2、考虑把 作者名称、文章链接、被引用人链接 放在版权信息里重复出现，是因为有可能爬虫抓取页面数据时，只抓取文章正文内容，屏蔽掉了作者和被引用人的信息，导致版权无法受到保护。（不过 这些其实都可以自己在文章下方显式列出来）

按照上方给出的方案 [example](https://khusika.com/hello-world/)，我没意见。

**Comment by ghost** [comment]
Front Matter 中的 license 参数可以在 config 文件中统一配置吗？
