### ISSUE TITLE
[FEATURE] 样式建议：页面立体层次感

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#344]
### 有价值的参考

可以参考这两个主题： [FeelIt](https://github.com/khusika/FeelIt)  和  [Mainroad](https://github.com/Vimux/Mainroad)

这样，文章、评论、页脚 三个部分在整个网页中更加 凸显 层次感，如图：

<img width="1264" alt="Screenshot 2021-11-08 at 19 17 23" src="https://user-images.githubusercontent.com/29486126/140733174-d34b86a5-d165-4095-9d97-112aaf134016.png">

<img width="1264" alt="Screenshot 2021-11-08 at 19 17 46" src="https://user-images.githubusercontent.com/29486126/140733194-d54b915c-cf7c-4c32-b646-f43fa2068099.png">

**Comment by HEIGE-PCloud** [comment]
DoIt 将坚持自身扁平化的设计风格。
