### ISSUE TITLE
[FEATURE] Add a signature to the end of the posts

### ISSUE THREAD

**Issue by Ahmed-E-86** [HEIGE-PCloud/DoIt#355]
### Describe the feature you want

- New Feature
  I would like if you could add a custom paragraph to be placed at the end of the body of each post by using **config.toml**

**Comment by eyllanesc** [comment]
@Ahmed-E-86  You could use the sponsor section: 

https://github.com/HEIGE-PCloud/DoIt/blob/895634b343cfdbaa04478ec1e43f79cae9f44f40/exampleSite/config.toml#L269-L273

If my suggestion is not valid then you could indicate what the objective of that section would be, indicate some practical example.

**Comment by Ahmed-E-86** [comment]
Thanks for your response. That will work, but I want to include HTML tags, because I want to format the text and add other links.

**Comment by eyllanesc** [comment]
@Ahmed-E-86 Then use the section "custom", in the piece of code that I show you see an example where HTML tags and links are placed.

**Comment by Ahmed-E-86** [comment]
Custom is used for the link, not the whole text, am I wrong?

**Comment by eyllanesc** [comment]
@Ahmed-E-86 Okay, it seems that my suggestion does not meet your requirements. So I suggest that you justify the use of that new section but imagine that every so often someone is going to ask for a similar section but in another part (below the title, above the title, etc). Each part of the post has an objective, could you indicate a practical case of what that section would be used for?

**Comment by Ahmed-E-86** [comment]
Something like a signature, at the end of the body, before or after the sponsor section. Whatever the owner of the project approves.

**Comment by HEIGE-PCloud** [comment]
I mean... If you want to add a paragraph to the end of each post, why don't you just add it directly? Using some commands like `echo "my text" | tee -a *.md` can do this very easily. 

If you want to manage the signature centrally, then you can create a custom [shortcode](https://gohugo.io/templates/shortcode-templates/) `{{% myshortcode /%}}` and add this shortcode to the end of the posts. Then you only need to update the content in the shortcode, or the arguments passing to the shortcode.

I understand what you expect from me is some kind of settings in the `config.toml` like

```toml
[param.page.signature]
    enable = true
    content = "<p>Some HTML</p>"
```

And allowing you to change this setting in the frontmatter as well. 

It is very simple to implement this feature, add something like 

```
{{ if $params.page.signature.enable }}
    {{ $params.page.signature.content | safeHTML -}}
{{ end }}
```

to the end of `single.html` will do the trick, and you can probably do it yourself...

But to be honest, I think this solution is worse than simply adding them to each posts separately (Or use custom shortcode). It does not really make anything easier, and when you want to migrate to another theme or another framework someday, it will just add more pain...

**Comment by Ahmed-E-86** [comment]
Using a custom shortcode seems the best option for my use case. Thanks for your reply @HEIGE-PCloud
