### ISSUE TITLE
[BUG] 页面跳转滚动条位置不变

### ISSUE THREAD

**Issue by qingwave** [HEIGE-PCloud/DoIt#357]
### Describe the bug 描述你遇到的错误
每次页面跳转（首页->文章页，文章页->上一篇），跳转后滚动条不变，再滚动到最上面

### Expected behavior 期待的行为
跳转后直接从页面顶端显示
不清楚是不是有意为之，在LoveIt上没发现这个问题，有点影响体验

### Screenshots 屏幕截图
测试使用的是提供的demo https://hugodoit.pages.dev/zh-cn/
跳转前
![image](https://user-images.githubusercontent.com/15335634/142719001-237fcf09-2eae-4690-a327-3e4e700d5fa3.png)

跳转后，滚动条再滚动到顶端

### Preview Environment 预览环境

- DoIt: latest master
- OS: Windows 10
- Browser：Chrome

**Comment by HEIGE-PCloud** [comment]
与 LoveIt 不同， DoIt 添加了 Pjax 刷新支持 #78，每次点击新的链接时，页面中只有变化的部分会被重新加载。因此页面的滚动位置需要重新定位至顶部。又由于 DoIt 设置了 smooth-scroll 的 CSS 属性，所以会显示滚动动画。

**Comment by qingwave** [comment]
多谢解答
