### ISSUE TITLE
[FEATURE] image shortcode 可否提供水平对齐功能（居中）

### ISSUE THREAD

**Issue by iChunyu** [HEIGE-PCloud/DoIt#363]
### Describe the feature you want 描述你的功能需求

- I hope `image` shortcode could work with parameter like `align` to adjust horizontal location of the image (e.g. align to center).
  希望 `image` shortcode 能够提供形如 `align` 的参数以调整图片水平位置（比如居中）

### Useful reference 有价值的参考

HTML 居中示例：

```html
<div align=center>
    <img src=some-image.png width=50% />
</div>
```

**Comment by HEIGE-PCloud** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/52968553/143421215-20696191-045a-4830-9cb4-00ac5ccea849.png">

image shortcode 应该是默认就是水平居中的...

**Comment by iChunyu** [comment]
咦？我加了宽度设置之后就变成左对齐了：

```
{{< image src="lpsd01.jpg" width="70%">}}
```

需要配置文件进行其他设置吗？ 容我再试试。。。。

**Comment by sugarlesss** [comment]
> 咦？我加了宽度设置之后就变成左对齐了：
> 
> ```
> {{< image src="lpsd01.jpg" width="70%">}}
> ```
> 
> 需要配置文件进行其他设置吗？ 容我再试试。。。。

加上 caption 属性即可居中，value 可以为空字符串。
```
{{< image src="lpsd01.jpg" width="70%" caption="" >}}
```

**Comment by iChunyu** [comment]
> > 咦？我加了宽度设置之后就变成左对齐了：
> > ```
> > {{< image src="lpsd01.jpg" width="70%">}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 需要配置文件进行其他设置吗？ 容我再试试。。。。
> 
> 加上 caption 属性即可居中，value 可以为空字符串。
> 
> ```
> {{< image src="lpsd01.jpg" width="70%" caption="" >}}
> ```

唔...我这里空字符串不太起作用，但是加了其他字符就可以了。也挺不错，感谢大佬！

**Comment by sugarlesss** [comment]
> > > 咦？我加了宽度设置之后就变成左对齐了：
> > > ```
> > > {{< image src="lpsd01.jpg" width="70%">}}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 需要配置文件进行其他设置吗？ 容我再试试。。。。
> > 
> > 
> > 加上 caption 属性即可居中，value 可以为空字符串。
> > ```
> > {{< image src="lpsd01.jpg" width="70%" caption="" >}}
> > ```
> 
> 唔...我这里空字符串不太起作用，但是加了其他字符就可以了。也挺不错，感谢大佬！

我给记错了。。。我平时不需要居中的时候才用空字符串，需要居中是要加描述文字的。
