### ISSUE TITLE
[FEATURE] 希望页面切换统一成先跳转到顶部再进行加载

### ISSUE THREAD

**Issue by railzy** [HEIGE-PCloud/DoIt#370]
### Describe the feature you want 描述你的功能需求
已在demo页上测试
从主页点击进入文章页，会花费一些时间加载页面内容（且内容越多需要的时间越久），再跳转到顶部，让人感觉网页很缓慢，体验不好。
而在文章页相互切换时，会先跳转到顶部再加载内容，访问者可以立刻开始阅读内容，感觉上就快了很多。

因此希望各个页面跳转时能够统一成先跳转到顶部再进行加载。

### Useful reference 有价值的参考
暂无

**Comment by HEIGE-PCloud** [comment]
https://github.com/HEIGE-PCloud/DoIt/issues/357

已经有两个人提这个问题了，也许我应该做些什么，比如把那个滚动动画给删了，

或者加一个

```js
document.addEventListener('pjax:send', () => {
    window.scroll(0, 0)
})
```
之类的东西。

**Comment by railzy** [comment]
> #357
> 
> 已经有两个人提这个问题了，也许我应该做些什么，比如把那个滚动动画给删了，
> 
> 或者加一个
> 
> ```js
> document.addEventListener('pjax:send', () => {
>     window.scroll(0, 0)
> })
> ```
> 
> 之类的东西。

尝试了在theme.min.js中 `document.addEventListener("pjax:send",function(){window.removeEventListener("scroll",a)})` 这句前面加入了上面的代码，感觉体验好了很多，建议考虑加入

不过现在滚动动画开启后有几率使得页面切换时未滚动到顶部就停住，所以我个人在 `_custom.scss` 里覆盖去掉了
