### ISSUE TITLE
[FEATURE] Button that shares the link in various formats (not social share links)

### ISSUE THREAD

**Issue by eyllanesc** [HEIGE-PCloud/DoIt#372]
The theme accepts many [social share links](https://github.com/HEIGE-PCloud/DoIt/blob/5af8502f6338f9a3df7ae72ee28f8e464415b2ec/exampleSite/config.toml#L756-L784) but in some cases the reader does not want to share it through social networks but for example only the link or a markdown (perhaps also a .rst). For example in [this blog](https://hive.blog/archlinux/@rgomezgerardi/como-instale-arch-linux-junto-a-windows-10) there is a link button:

![Screenshot_20211204_014506](https://user-images.githubusercontent.com/4896200/144718037-956d3f92-3e60-47cc-b6f4-78c98bd965b2.png)

and if it is pressed then a popup will open showing the formats that can be copied:

![Screenshot_20211204_014333](https://user-images.githubusercontent.com/4896200/144718103-64d9cd3f-90b1-4816-ad46-b381a178fd86.png)

**Comment by HEIGE-PCloud** [comment]
To be honest, if I want to share a URL, instead of looking for some buttons to copy, I will directly copy it from the address bar...

**Comment by HEIGE-PCloud** [comment]
The markdown code may be a little bit more helpful, but comparing "copy title and url separately into `[<title>](<url>)`" with "scrolling to the end of the post to find a button that copies it", I doubt how many people will really use it...

**Comment by eyllanesc** [comment]
@HEIGE-PCloud  I also thought the same but I think that a popup where you can place new formats to make the links be shared in a simple way is more pleasant and elegant.

I have reviewed several blogs (I had thought about this feature several weeks ago) and I saw that it is better to place an extra share button, if it were the same, copy the link then the "share links buttons" since they could copy the link and the social network I would give it the format.

**Comment by eyllanesc** [comment]
@HEIGE-PCloud The objective of any share button is to make the work easy for readers, so social networks implement an api for developers to use to share information. In this case it would be something simpler but just as effective.

**Comment by eyllanesc** [comment]
> The markdown code may be a little bit more helpful, but comparing "copy title and url separately into `[<title>](<url>)`" with "scrolling to the end of the post to find a button that copies it", I doubt how many people will really use it...

The "scrolling to the end of the post to find a button that copies it" would also apply to the other share buttons, I don't think they go to the bottom of the post to look for the share button, but rather later to read post and since they are at the end of the post, see the share buttons and analyze if they want to share it.

**Comment by HEIGE-PCloud** [comment]
> > The markdown code may be a little bit more helpful, but comparing "copy title and url separately into `[<title>](<url>)`" with "scrolling to the end of the post to find a button that copies it", I doubt how many people will really use it...
> 
> The "scrolling to the end of the post to find a button that copies it" would also apply to the other share buttons, I don't think they go to the bottom of the post to look for the share button, but rather later to read post and since they are at the end of the post, see the share buttons and analyze if they want to share it.

When you want to copy a markdown code to a blog, it is less likely that you want to share the code with someone, but more likely that you are writing some new posts and want to reference this blog. So, you are more likely in the middle of the post, and I think it is easier to just copy the url from the address bar (which also takes advantage of your anchor tracking pr #366).

**Comment by HEIGE-PCloud** [comment]
So what exactly do you want in that popup? The url to the post, the url to the raw markdown file (maybe rst file as well)? Am I understanding this correctly?

**Comment by eyllanesc** [comment]
> So what exactly do you want in that popup? The url to the post, the url to the raw markdown file (maybe rst file as well)? Am I understanding this correctly?

Exactly, that's what I want, so in the second image I only show a part of the original popup emphasizing what I want.

**Comment by HEIGE-PCloud** [comment]
I still don't get it. Why do you need a flyout window to copy the url to the post......

https://gohugo.io/content-management/formats/

Also, it seems that it is not possible to generate rst format files from Markdown through Hugo. If you want to share in a "different" format, you have to write the source file in that "different" format, and use some `outputFormats` settings to generate such file. (Similar to the implementation of the Read Markdown link)

> The objective of any share button is to make the work easy for readers, so social networks implement an api for developers to use to share information. In this case it would be something simpler but just as effective.

The social networks make it easier by auto login and quick share, but a pop up really does not make anything easier. (I would say copy from address bar is easy enough, and more intuitive since most websites do not have that popup)

Closing this.
