### ISSUE TITLE
[BUG] failed to render pages: render

### ISSUE THREAD

**Issue by yanboyang713** [HEIGE-PCloud/DoIt#40]
render 报错
hugo version
hugo v0.82.0+extended linux/amd64 BuildDate=unknown

Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: posts/single.html:103:124: executing "content" at <partial "function/content.html">: error calling partial: "/home/yanboyang713/yanboyang713.github.io/themes/DoIt/layouts/partials/function/content.html:4:19": execute of template failed: template: partials/function/content.html:4:19: executing "partials/function/content.html" at <partial "function/ruby.html" $content>: error calling partial: partial that returns a value needs a non-zero argument.

解决方法：
https://blog.mrsheep.xyz/posts/loveit-error-fix/

**Comment by HEIGE-PCloud** [comment]
Weird, the exampleSite can run normally.

**Comment by sosiristseng** [comment]
This was the same issue as: https://github.com/sunt-programator/CodeIT/issues/68

For newer versions of Hugo, we need to check if the content is empty before inserting partials.

**Comment by HEIGE-PCloud** [comment]
faster than me awwwwwww
