### ISSUE TITLE
[FEATURE] 页面统计

### ISSUE THREAD

**Issue by ZhaoUncle** [HEIGE-PCloud/DoIt#413]
### Describe the feature you want 描述你的功能需求

我之前在LoveIt加了CMZZ和卜算子统计的页面UV/PV的功能，如有考虑，我可以提个pr？

### Useful reference 有价值的参考
![image](https://user-images.githubusercontent.com/31182637/147074473-ededff96-a144-48d0-b9fb-d7c357b92550.png)

**Comment by sugarlesss** [comment]
非常棒的功能，赞
