### ISSUE TITLE
[求助]系列权重设置不生效

### ISSUE THREAD

**Issue by maye-e** [HEIGE-PCloud/DoIt#416]
我有两篇文章，设置了 series_weight 值。

这个页面是按照我期望的顺序显示：
![1](https://user-images.githubusercontent.com/28441420/147108368-465648fe-44c8-4efc-9ed1-f34063c2c8b1.png)

这个页面没有按照期望显示：
![2](https://user-images.githubusercontent.com/28441420/147108487-39ecfd4b-83c3-432a-a93b-b4b660a564c6.png)

是哪里的设置漏掉了吗

**Comment by maye-e** [comment]
我发现在文章上面加 weight: 1 这样的设置后，可以让第二张图中显示为预期排序，但这也会使首页展示的文章顺序改变。
是否可以让首页文章按默认顺序展示(按时间倒序)的前提下，第二章图中按照 series_weight 指定的顺序排序显示

**Comment by maye-e** [comment]
我发现在文章上面加 weight: 1 这样的设置后，可以让第二张图中显示为预期排序，但这也会使首页展示的文章顺序改变。
是否可以让首页文章按默认顺序展示(按时间倒序)的前提下，第二章图中按照 series_weight 指定的顺序排序显示

**Comment by eyllanesc** [comment]
@HEIGE-PCloud What is the order criterion for the ordering of the posts in a series? Which has preference: weight or series_weight?

**Comment by HEIGE-PCloud** [comment]
Not sure why there is this inconsistent behaviour. On the [term page](https://hugodoit.pages.dev/series/getting-start/), the weight has a higher priority than the series_weight, but on the [list page](https://hugodoit.pages.dev/series/), the series_weight has a higher priority than the weight. The implementation on both pages are similar. They all rely and only rely on the default range look up order. The problem *may* cause by the pagination, but I am not really sure about what is going on here.

https://github.com/HEIGE-PCloud/DoIt/blob/188fdde2163ae851591a9d2d7b26ab3ab041c244/layouts/taxonomy/list.html#L53-L62
https://github.com/HEIGE-PCloud/DoIt/blob/188fdde2163ae851591a9d2d7b26ab3ab041c244/layouts/taxonomy/terms.html#L63-L69
Some references: https://gohugo.io/templates/taxonomy-templates/#order-content-within-taxonomies

**Comment by real-nicholas** [comment]
```
weight: 2
title: "Testing"
date: 2021-12-23T15:37:35+08:00
categories: ["testing"]
tags: ["testing"]
series: ["testing"]
series_weight: 2
```

我试了一下，我的 front matter 这么写，没有出现排序错乱的现象。

**Comment by WingsZeng** [comment]
@HEIGE-PCloud 

我做了一个实验, 不设置 weight, 仅设置 series_weight, 在 [list 页面 (layouts/taxonomy/list.html)](https://hugodoit.pages.dev/series/getting-start/) 里实际上文章并没有按照 series_weight 排序, 而是按照时间排序. 这一结果说明这里是按照默认的规则排序.

仔细阅读两份代码, 我发现了些许区别: 

https://github.com/HEIGE-PCloud/DoIt/blob/188fdde2163ae851591a9d2d7b26ab3ab041c244/layouts/taxonomy/terms.html#L50-L54

https://github.com/HEIGE-PCloud/DoIt/blob/188fdde2163ae851591a9d2d7b26ab3ab041c244/layouts/taxonomy/list.html#L46-L53

两份代码中的 `$pages` 变量是从不同的上下文获得的. terms.html 中, 来源于 `.Data.Terms` -> `.Term` -> `.Pages`, 而 list.html 中则直接来自于 `.Pages`. 查阅文档得知, 二者是不同的模板. terms.html 是 [Taxonomy Terms Template](https://gohugo.io/templates/taxonomy-templates/#taxonomy-terms-template), 而 list.html 的模板是 [Taxonomy List Templates](https://gohugo.io/templates/taxonomy-templates/#taxonomy-list-templates). 根据文档得知, 这就是 [List Templates](https://gohugo.io/templates/lists/). List Templates 中使用的 `.Pages` 获取到的 page 是按照默认规则排序的. 我认为他并不能按照 taxonomy weight 排序, 因为页面可以指定多个 taxonomy weight, 比如[官方文档](https://gohugo.io/templates/taxonomy-templates/#assign-weight)里同时指定了 tags weight 和 categories weight. 而无论 /tags/a 还是 categories/b, 都是用的同一个模板, 因此 `.Pages` 获取的页面顺序不会有差异(不清楚 hugo 的实现细节, 仅个人猜测).

所以解决问题的方法有两种, 一种是通过 `.Site.Taxonomy.series.something` 去获取 pages, 另一种是在 list.html 中直接指定按 series weight 排序. 我更倾向与使用第二种方法, 这是我的 PR #464 😛 

相关文档:
- [https://gohugo.io/templates/taxonomy-templates/](https://gohugo.io/templates/taxonomy-templates/)
- [https://gohugo.io/content-management/taxonomies/](https://gohugo.io/content-management/taxonomies/)
- [https://gohugo.io/templates/lists/](https://gohugo.io/templates/lists/)
- [https://gohugo.io/variables/page/#pages](https://gohugo.io/variables/page/#pages)
