### ISSUE TITLE
[BUG] “系列”页面添加PJAX函数后导致页面出现 “空引用” 问题

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#419]
### “系列”页面添加PJAX函数后导致页面出现 “空引用” 问题

我在文章中添加 PJAX 函数控制 Twikoo 评论的统一性。
但是在 “系列” 类型的文章中添加了PJAX函数后，页面上会出现一个空的引用： ```<blockquote></blockquote>```
而其他非 “系列” 类型的文章都不会这样。Hugo版本：0.88.1

如图：
<img width="818" alt="Screenshot 2021-12-23 at 18 38 36" src="https://user-images.githubusercontent.com/29486126/147228919-b54edab0-c35e-454d-abe4-96f5fa7bece9.png">

**Comment by HEIGE-PCloud** [comment]
能提供一个 demo 吗？

**Comment by ghost** [comment]
没有部署到线上。

你可以在你的demo系列文章md文件里添加那段pjax函数，看看能复现吗？

**Comment by HEIGE-PCloud** [comment]
那段函数和 blockquote 没有任何关系

你大概是在 Markdown 源文件里输了一个空的 `>`

**Comment by ghost** [comment]
我没有 在 Markdown 源文件里输了一个空的 `>`
把那段函数加上就有问题，去掉就没有问题

问题没有解决呀，怎么关闭了

**Comment by ghost** [comment]
[demo](https://real-nicholas.github.io)
已经部署demo，帮忙排查一下
