### ISSUE TITLE
[BUG] Unexpected change of position of the search menu in transitions.

### ISSUE THREAD

**Issue by eyllanesc** [HEIGE-PCloud/DoIt#421]
### Describe the bug 

When the page is changed (for example when clicking on the menu tabs) the search icon goes down and then it is placed in the appropriate position.

### Expected behavior

It shouldn't change position like the other menus.

### Screenshots

![Screenshot_20211223_113319](https://user-images.githubusercontent.com/4896200/147268590-54e18233-dea6-4bf1-92e7-035058ff1898.png)

### Build Environment:

The problem is observed in the official demo.

### Preview Environment

- OS: Arch Linux
- Browser: Firefox

**Comment by HEIGE-PCloud** [comment]
This is very funny, I managed to reproduce it constantly by disabling all the js. And it comes right back to the correct position when I open the devtools.

https://user-images.githubusercontent.com/52968553/147373974-ce11b0e2-b966-4eec-b94c-842c2dc05d93.mp4

**Comment by eyllanesc** [comment]
@HEIGE-PCloud  It seems that devtools resets the position of the search icon. If you notice when you directly open any link on the page (`https://hugodoit.pages.dev/categories/`, `https://hugodoit.pages.dev/tags/`, etc) in the browser this behavior is not observed but If after being in `https://hugodoit.pages.dev/categories/` you click on the menu `https://hugodoit.pages.dev/tags/` if this behavior is observed.

**Comment by HEIGE-PCloud** [comment]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/52968553/147374157-8cebe330-d566-46b3-a517-cc71fc84fce9.png">

It seems to be caused by an incorrect computed position-bottom value. And gets "updated" to the correct value later somehow.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/52968553/147374172-c4495be5-31a2-4e32-9f2e-1cb05af2d765.png">

**Comment by HEIGE-PCloud** [comment]
> It seems that devtools resets the position of the search icon. If you notice when you directly open any link on the page (`https://hugodoit.pages.dev/categories/`, `https://hugodoit.pages.dev/tags/`, etc) in the browser this behavior is not observed but If after being in `https://hugodoit.pages.dev/categories/` you click on the menu `https://hugodoit.pages.dev/tags/` if this behavior is observed.

Yes, and I noticed that simply refresh the page will trigger this issue as well. I originally suspect it might relate to the PJAX loading, but after testing it with JavaScript disabled, the problem still exists.

Didn't manage to reproduce that with either Chrome or Safari, maybe something Firefox specific? :D

**Comment by HEIGE-PCloud** [comment]
https://hugoloveit.com/

I observe the same issue with the Hugo LoveIt theme as well. (Refreshing the page to reproduce.)

**Comment by HEIGE-PCloud** [comment]
Might related to Font Awesome

https://stackoverflow.com/questions/41444873/font-awesome-icon-aligns-wrong-in-firefox

**Comment by eyllanesc** [comment]
> Didn't manage to reproduce that with either Chrome or Safari, maybe something Firefox specific? :D

I do not reproduce the error in Google Chrome
