### ISSUE TITLE
[FEATURE] 希望 “系列” 可以实现目录层级结构

### ISSUE THREAD

**Issue by ghost** [HEIGE-PCloud/DoIt#422]
### 希望 “系列” 可以实现目录层级结构
对于系列文章中的列表：`<div class="details series-nav open"></div>`，这里面希望可以实现目录层级结构。

比如：
<img width="209" alt="Screenshot 2021-12-24 at 16 22 43" src="https://user-images.githubusercontent.com/29486126/147334195-bc4c8486-f5b1-4765-a46a-be8533b588ee.png">

**Comment by HEIGE-PCloud** [comment]
这个框是用于在不同文章中快速跳转的，放入完整的 table of content 会让它过于冗长，没有必要。
