### ISSUE TITLE
[BUG] 你们都是把你们的blog部署在那里？github pages？

### ISSUE THREAD

**Issue by yanboyang713** [HEIGE-PCloud/DoIt#44]
你们都是把你们的blog部署在那里？github pages？

我在本地
hugo server -D
显示都比较正常。
本地hugo version
hugo v0.82.0+extended linux/amd64 BuildDate=unknown

用github action build 时会报错， 用的是hugo v0.83.1：

Run hugo --minify
Start building sites … 
WARN 2021/05/03 02:59:10 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2021/05/03 02:59:10 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2021/05/03 02:59:10 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2021/05/03 02:59:10 found no layout file for "JSON" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

                   | EN  
-------------------+-----
  Pages            |  1  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Total in 12 ms

Run peaceiris/actions-hugo@v2
Hugo version: 0.83.1
/bin/tar xz --warning=no-unknown-keyword -C /home/runner/actions_hugo/_temp -f /home/runner/work/_temp/1f5aa5ce-210c-405b-8079-8f5c15ffbef9
/home/runner/actions_hugo/bin/hugo version
hugo v0.83.1-5AFE0A57+extended linux/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio
====

![image](https://user-images.githubusercontent.com/7603628/116837950-d43a2780-ac0f-11eb-9bc1-0a46158b385e.png)

**Comment by sosiristseng** [comment]
我是部屬在 GitHub pages, 新版hugo運作正常

https://github.com/sosiristseng/template-hugo-doit

**Comment by HEIGE-PCloud** [comment]
你是将主题作为submodule导入的，但是你的Github Actions的workflow file并没有check out submodules，所以主题事实上都没有被下载，因此报错`no layout file`。

```
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
```

将checkout部分添加以上配置。

阅读这份[文档](https://gohugo.io/hosting-and-deployment/hosting-on-github/)查看更多关于部署GitHub Pages的帮助。

**Comment by yanboyang713** [comment]
@sosiristseng @HEIGE-PCloud 
感谢，感谢。我琢磨一下。这刚想把自己的blog从hexo转到hugo上

**Comment by HEIGE-PCloud** [comment]
Now I have the deep understanding of the true meaning of [Netorare](https://github.com/yanboyang713/yanboyang713.github.io/blob/e6d81d8275fc7c9c36bfd11dfbb8e420592202ee/config.toml#L9).  Sayonara.
