### ISSUE TITLE
Dates are not properly placed

### ISSUE THREAD

**Issue by gnohz** [HEIGE-PCloud/DoIt#441]
I use your theme to write journals, and use the date as the title for each post.
However, once we enter the new year (2022), it put my most recent posts to the end of all posts.
![Screen Shot 2022-01-03 at 11 28 10 AM](https://user-images.githubusercontent.com/21259404/147972238-1de7cb43-bdb3-4eef-ab61-0f3ba0065049.png)
![Screen Shot 2022-01-03 at 11 32 24 AM](https://user-images.githubusercontent.com/21259404/147972249-15a9129c-9eda-4202-984c-e002c2d017a6.png)

**Comment by HEIGE-PCloud** [comment]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/52968553/147973449-851c07fd-f89f-46f2-b16c-7d698bbad172.png">

I am not able to reproduce that on the exampleSite... Can you provide a minimal reproduceable demo?

**Comment by HEIGE-PCloud** [comment]
Reopen if more information is provided.
