### ISSUE TITLE
[BUG] Some problem...

### ISSUE THREAD

**Issue by shuaiqinchu** [HEIGE-PCloud/DoIt#444]
![image](https://user-images.githubusercontent.com/96340518/148642586-f44ccb4c-a8cc-4dec-aaa3-f4c9c48e0977.png)

how can i deal with this problem?

github actions

**Comment by HEIGE-PCloud** [comment]
Turn off the experimental option in the config.toml

```
  # [Experimental] Bundle js
  bundle = false
```
