### ISSUE TITLE
Add DoIt theme to hugoThemes

### ISSUE THREAD

**Issue by HEIGE-PCloud** [HEIGE-PCloud/DoIt#46]
As `v0.2.11` release will be the first release from DoIt theme, I plan to add the DoIt theme to hugo official theme site so more people can discover this theme. There are still some work to do to optimize the theme to meet the requirements.

Here are the requirements: https://github.com/gohugoio/hugoThemes/blob/master/README.md

**Comment by HEIGE-PCloud** [comment]
The original LoveIt theme's submission is a good negative example.

https://github.com/gohugoio/hugoThemes/issues/700

**Comment by HEIGE-PCloud** [comment]
Task list:
- [x] Configure `theme.toml` (Need to update the `min_version`)
- [x] Configure `README.md`
- [x] Configure `README.zh-cn.md`
- [x] Update `/images/screenshot.png` and `/images/tn.png`
- [x] Configure `.gitignore` file for resources folder
- [x] Test with the [build script](https://github.com/gohugoio/hugoThemes/blob/master/_script/generateThemeSite.sh)

**Comment by HEIGE-PCloud** [comment]
# Theme submission

**Please make sure that you have read the [theme submission guidelines](https://github.com/gohugoio/hugoThemes/blob/master/README.md#adding-a-theme-to-the-list) before submitting a theme**. The guidelines provide all relevant information and requirements that **have to be fulfilled** before the submission. We strongly suggest that you test your theme with the [Hugo Themes Build Script](https://github.com/gohugoio/hugoThemes/blob/master/README.md#testing-a-theme-with-the-hugo-themes-website-build-script) before submitting the theme for review. If a submission does not meet the criteria mentioned in the README it will be closed. You may re-submit once you fix the problems with your submission. However, please note that we have limited resources and can not provide help for general web development issues. For Hugo support questions please refer to the dedicated [support forum](https://discourse.gohugo.io/).

Please tick the relevant boxes for your theme in the checklist below:

**Link to my theme repository:** REPLACE-WITH-URL

### I made sure that...

- [x] the repository contains a good `README.md` describing my theme
- [x] an open source license has been added to `LICENSE.md`
- [x] all metadata have been added to `theme.toml`
- [x] screenshots have been added in the `images/` folder with the [required dimensions](https://github.com/gohugoio/hugoThemes/blob/master/README.md#media)
- [x] in case I'm using a customized demo via the exampleSite folder that
    - [x] `https://example.com` is set as base url in `exampleSite/config.{toml, yaml, json}` to [avoid the abuse of unused domains](https://github.com/gohugoio/hugo/issues/2575)
    - [x] I tested that my theme's demo works with the content directory of [gohugoio/HugoBasicExample](https://github.com/gohugoio/hugoBasicExample/tree/master/content)
- [x] I tested my theme against the [gohugoio/HugoBasicExample](https://github.com/gohugoio/HugoBasicExample)
    - [x] I've checked the developer tools' console in my browser for error messages
- [x] in case my theme is using Hugo Pipes features like `toCSS` and `PostCSS` that I have committed the `/resources` directory with all generated assets, for my theme to work in the basic version of Hugo

**N.B.** By submitting a theme to the Hugo Themes Showcase you understand that **you need to maintain your theme**. If a theme demo breaks and remains broken then at some point it will be removed from the list without prior warning. If you no longer wish to maintain a theme please let us know.

New themes will usually be promoted on Hugo's official Twitter account. If you would like to be mentioned in the tweet please add your Twitter username to this submission.

**Link to my Twitter account (optional):** REPLACE-WITH-URL

Feel free to ask questions. We're glad to help.

**Comment by HEIGE-PCloud** [comment]
The `series = ["Themes Guide"]` in the frontmatter of [hugoBasicExample](https://github.com/gohugoio/hugoBasicExample/blob/4a9e2433df3eeb7e78cc7f4ef2309e81af3e71dd/content/post/markdown-and-html-syntax.md) is causing problem.

**Comment by HEIGE-PCloud** [comment]
The theme has been submitted https://github.com/gohugoio/hugoThemes/issues/1011

**Comment by HEIGE-PCloud** [comment]
We probably should not expect the review to be done very quickly based on the recorded long average waiting time...🤔

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/118397338-63513180-b64b-11eb-8f7b-6b0e53e975e7.png)

https://github.com/gohugoio/hugoThemes/pulse/monthly

Apparently, no theme is accepted in the past one month. The issue will be closed, and I will keep an eye on it. UwU

**Comment by wey-gu** [comment]
It seems that repo was replaced by https://github.com/gohugoio/hugoThemesSiteBuilder today.
@HEIGE-PCloud
