### ISSUE TITLE
[BUG] Hugo v0.92.0以上版本，执行hugo server之后报错

### ISSUE THREAD

**Issue by wxzForest** [HEIGE-PCloud/DoIt#472]
![image](https://user-images.githubusercontent.com/18545797/154228942-a66c81eb-c536-4968-b9db-a378ed60fec0.png)

Current environment is "development". The "comment system", "PWA", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "PWA", "CDN" 和 "fingerprint" 不会启用.
Error: Error building site: TOCSS: failed to transform "css/style.scss" (text/x-scss). Check your Hugo installation; you need the extended version to build SCSS/SASS.: this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Built in 132 ms

**Comment by WingsZeng** [comment]
需要使用 Hugo extended. [相关文档](https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#1-%E5%87%86%E5%A4%87)

**Comment by eyllanesc** [comment]
@wxzForest I believe that you are not using the extended version, if I run: 

```console
$ hugo version
hugo v0.92.2+extended linux/amd64 BuildDate=unknown
```

it is observed that it does mention it.
