### ISSUE TITLE
[BUG] Search index is still on LoveIt

### ISSUE THREAD

**Issue by sosiristseng** [HEIGE-PCloud/DoIt#48]
### Describe the bug 描述你遇到的错误

The search index of https://hugodoit.pages.dev/ is still on LoveIt.

### Expected behavior 期待的行为

The Algolia search index should be updated to the contents of DoIt theme.

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/40054455/116963539-b0dcae80-acdb-11eb-921e-e968bec4e668.png)

### Build Environment 构建环境

https://github.com/HEIGE-PCloud/DoIt

### Preview Environment 预览环境

On the latest Chrome, Windows 10.

### Additional Information 补充信息

To update the search index, you might want to sign up and create an [Algolia](https://www.algolia.com) app to hold the entries.

FYI, I wrote a [CI pipeline](https://github.com/sosiristseng/sosiristseng.github.io/blob/main/.github/workflows/deploy.yml) to upload the search index upon pushing to the main branch. Also, here are the relevant npm [package](https://github.com/sosiristseng/sosiristseng.github.io/blob/main/package.json) and the [lock](https://github.com/sosiristseng/sosiristseng.github.io/blob/main/package-lock.json) files.

Some customizations might be needed, such as:
- API keys
- one search index for each language.

Reference:

- https://coldinfire.github.io/2018/Utils_hugo2/

**Comment by HEIGE-PCloud** [comment]
To make life easier, I just use the Lunr.js instead on the exampleSite.

More Reference: https://hugodoit.pages.dev/theme-documentation-basics/#52-search-configuration

**Comment by sosiristseng** [comment]
Closed by https://github.com/HEIGE-PCloud/DoIt/commit/ade7d33c19b1e99f298973c6e735cc30e0fab4a0

**Comment by HEIGE-PCloud** [comment]
The Algolia search is a significantly better option, it will be configured later.

**Comment by sosiristseng** [comment]
Sorry for hastily closing the issue.

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/117001416-3bbca980-acda-11eb-9acb-f7e3d57feae3.png)

Fixed! Woohoo~😁
