### ISSUE TITLE
[BUG] giscus评论的样式不能随着网站主题切换

### ISSUE THREAD

**Issue by yqchilde** [HEIGE-PCloud/DoIt#489]
### Describe the bug 描述你遇到的错误

不管我当页面主题切换为深色，浅色，黑色，giscus评论区都以浅色显示

### Expected behavior 期待的行为

giscus评论区可以随着网站主题色适应

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/36953759/155968231-40114fe2-1010-4123-b622-34e1eb770d9c.png)

### Build Environment 构建环境

- OS: macOS
- Theme version: 0.2.0
- Hugo version: hugo v0.92.2+extended

### Preview Environment 预览环境

- OS: macOS
- Browser: Chrome

**Comment by eyllanesc** [comment]
The problem is also pointed out in #461.
