### ISSUE TITLE
[BUG] vercel 部署报错

### ISSUE THREAD

**Issue by anyanf** [HEIGE-PCloud/DoIt#496]
### Describe the bug 描述你遇到的错误

Error: add site dependencies: load resources: loading templates: "/vercel/path0/themes/DoIt/layouts/partials/meta/author.html:8:1": parse failed: template: partials/meta/author.html:8: unclosed action

Error: ENOENT: no such file or directory, open '/vercel/path0/public/algolia.json'
--
16:14:04.116 | at Object.openSync (fs.js:462:3)
16:14:04.116 | at Object.readFileSync (fs.js:364:35)
16:14:04.116 | at getIndexFromFile (/vercel/path0/node_modules/atomic-algolia/lib/utils/getLocalIndex.js:17:25)
16:14:04.116 | at getLocalIndex (/vercel/path0/node_modules/atomic-algolia/lib/utils/getLocalIndex.js:9:12)
16:14:04.116 | at update (/vercel/path0/node_modules/atomic-algolia/lib/update.js:34:20)
16:14:04.117 | at Object.<anonymous> (/vercel/path0/node_modules/atomic-algolia/lib/index.js:13:3)
16:14:04.117 | at Module._compile (internal/modules/cjs/loader.js:999:30)
16:14:04.117 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
16:14:04.117 | at Module.load (internal/modules/cjs/loader.js:863:32)
16:14:04.117 | at Function.Module._load (internal/modules/cjs/loader.js:708:14) {

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/12234053/156526133-2b22fab8-aa78-4363-b161-1cae38cf23f5.png)

### Build Environment 构建环境

使用的是最新主干主题，vercel的hugo版本，node为12.x

**Comment by HEIGE-PCloud** [comment]
https://vercel.com/docs/concepts/deployments/build-step#framework-versioning

用 HUGO_VERSION 环境变量设置一个最近版本的 Hugo （如 0.93.1)
