### ISSUE TITLE
[Enhancement] Check the Hugo version before building and throw a more meaningful error message when the version is too low

### ISSUE THREAD

**Issue by HEIGE-PCloud** [HEIGE-PCloud/DoIt#497]
### Describe the feature you want 描述你的功能需求

Check `Hugo.IsExtended` and `Hugo.Version`

### Useful reference 有价值的参考

https://gohugo.io/functions/hugo/
https://github.com/HEIGE-PCloud/DoIt/blob/main/layouts/partials/init.html

**Comment by GreatestOfAllTimee** [comment]
I got an error when add `series` page. I also asked this issue on discussions side https://github.com/HEIGE-PCloud/DoIt/discussions/494

### Hugo Version:
`hugo v0.94.0-DEV+extended linux/amd64 BuildDate=unknown`
