### ISSUE TITLE
[BUG] 无论怎么修改config.toml，页面不变

### ISSUE THREAD

**Issue by Yangly0** [HEIGE-PCloud/DoIt#501]
### Describe the bug 描述你遇到的错误

当我修改config.toml后，页面并不发生变化。

### Expected behavior 期待的行为

解决该问题

### Screenshots 屏幕截图

页面一直出现的样子：
![image](https://user-images.githubusercontent.com/43691492/156787831-a52250b7-37c4-45f3-afbb-2183e2329e9a.png)

config.toml的配置：
![image](https://user-images.githubusercontent.com/43691492/156788136-692d6819-9229-4381-a859-e0100118bf1a.png)

### Build Environment 构建环境

- hugo v0.92.2-CDF6A0D6+extended windows/amd64

### Preview Environment 预览环境

- chrome

### Additional Information 补充信息

PS：我已经删除并重新安装2次，操作如下。然后，我发现打开依然会如上图一样。
```
$ rm -rf my-blog
$ hugo new site my-blog
$ git init  
$ git submodule add https://github.com/HEIGE-PCloud/DoIt.git themes/DoIt
$ hugo server
```

**Comment by WingsZeng** [comment]
看起来您并没有使用 DoIt 主题. 您的配置文件中并没有指定主题. 如果您在构建的时候加了 `-t` 选项指定 DoIt 主题的话, 这样的配置应该是会报错的.

请参考 [该文档](https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#2-%E5%AE%89%E8%A3%85) 进行配置.
