### ISSUE TITLE
[文档] 审核中文文档的标点符号使用

### ISSUE THREAD

**Issue by HEIGE-PCloud** [HEIGE-PCloud/DoIt#502]
由于历史遗留问题，中文文档的标点符号一直使用了英文标点。应参考 [中文排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines)，并借助 [MarkdownLint](https://github.com/DavidAnson/markdownlint) 工具全面审核中文文档。

- [ ] #505
- [ ] [Emoji 支持](https://hugodoit.pages.dev/zh-cn/emoji-support/)
- [ ] [Markdown 基本语法](https://hugodoit.pages.dev/zh-cn/basic-markdown-syntax/)
- [ ] [主题文档 - 基本概念](https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/)
- [ ] [主题文档 - 内容](https://hugodoit.pages.dev/zh-cn/theme-documentation-content/)
- [ ] [主题文档 - 内置 Shortcodes](https://hugodoit.pages.dev/zh-cn/theme-documentation-built-in-shortcodes/)
- [ ] [主题文档 - 扩展 Shortcodes](https://hugodoit.pages.dev/zh-cn/theme-documentation-extended-shortcodes/)
- [ ] [PWA 支持](https://hugodoit.pages.dev/zh-cn/pwa-support/)
- [ ] [如何在 DoIt 中创建图表](https://hugodoit.pages.dev/zh-cn/create-diagrams/)

**Comment by wu-yue-yu** [comment]
你好，我在GitHub上刷到了一个也是基于LoveIt开发的主题，上面有个还不错的中文排版方式，不知道对你有没有帮助。  
[主题仓库地址](https://github.com/Lruihao/FixIt)  
这个主题使用的方案是  
- 支持基于 [pangu.js](https://github.com/vinta/pangu.js) 的中文排版  
感谢您开发的这个主题
