### ISSUE TITLE
[FEATURE] Display full content of posts on homepage

### ISSUE THREAD

**Issue by dbrg77** [HEIGE-PCloud/DoIt#506]
### Describe the feature you want 描述你的功能需求

Hi,

Thanks for creating the awesome theme. I really like it. Currently, the default behaviour of `DoIt` is to display the summary of the post on homepage.

Is there a way of showing the full content for the post on homepage? I tried to modify a few things in `layouts` without success. I'm quite new to `Hugo`.

Thank you.

Regards,
Xi

**Comment by WingsZeng** [comment]
Maybe you can set `summaryLength` in the site configuration file to a large enough number?

Related documentation:
- https://gohugo.io/content-management/summaries/#automatic-summary-splitting

**Comment by dbrg77** [comment]
Thanks for the suggestion. I could do that, but the full content will be shown as plain text, not rendered in markdown.

The motivation here is to be able to immediately read the post in its full, rendered format, without having to click on the `Read more`. In other themes, I can locate the HTML file that control this behaviour and simply change the `.Summary` to `.Content`.

`DoIt` is just a bit too complicated for me to mess around 😂
