### ISSUE TITLE
[BUG] Katex折行渲染

### ISSUE THREAD

**Issue by anyanf** [HEIGE-PCloud/DoIt#524]
### Describe the bug 描述你遇到的错误

$$
\begin{aligned}
u \cdot n
& =u n^T \\
& = u(A A^{-1})n^T \\
& =(uA)(A^{-1}n^T) \\
& =(uA)((A^{-1}n^T)^T)^T \\
& =(uA)(n(A^{-1})^T)^T \\
& =uA \cdot n(A^{-1})^T \\
& =uA\cdot nB \\
& =0
\end{aligned}
$$

渲染成了一行

### Expected behavior 期待的行为

期望可以折行

**Comment by HEIGE-PCloud** [comment]
应该用 `\\`

```

\begin{aligned}
u \cdot n
& =u n^T \\
& = u(A A^{-1})n^T \\
& =(uA)(A^{-1}n^T) \\
& =(uA)((A^{-1}n^T)^T)^T \\
& =(uA)(n(A^{-1})^T)^T \\
& =uA \cdot n(A^{-1})^T \\
& =uA\cdot nB \\
& =0
\end{aligned}
```

**Comment by anyanf** [comment]
> 应该用 `\\`
> 
> ```
> 
> \begin{aligned}
> u \cdot n
> & =u n^T \\
> & = u(A A^{-1})n^T \\
> & =(uA)(A^{-1}n^T) \\
> & =(uA)((A^{-1}n^T)^T)^T \\
> & =(uA)(n(A^{-1})^T)^T \\
> & =uA \cdot n(A^{-1})^T \\
> & =uA\cdot nB \\
> & =0
> \end{aligned}
> ```

一样没有折行。。

**Comment by HEIGE-PCloud** [comment]
https://github.com/HEIGE-PCloud/DoIt/discussions/518

**Comment by anyanf** [comment]
> #518

可以了，非常感谢。。
