### ISSUE TITLE
[BUG] 代码块过长显示不全

### ISSUE THREAD

**Issue by nopdan** [HEIGE-PCloud/DoIt#543]
### Describe the bug 描述你遇到的错误

在看 [官网教程](https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#site-configuration) 的时候发现，网站配置处的代码块长达 690 行，实际只能显示 612 行。

### Expected behavior 期待的行为

显示完全部的代码行，或者达到一定长度后加一个滚动条

### Screenshots 屏幕截图

![问题](https://s2.loli.net/2022/03/28/OyCmr5BLUskWD6w.png)

### Preview Environment 预览环境

- OS: windows 10
- Browser: Edge

### Additional Information 补充信息

f12 控制台发现 .table-wrapper 高度被限制为 12000px ，改为 100% 可以显示完，不知道有没有别的影响
![图片](https://s2.loli.net/2022/03/28/IJdiMaH6zUbEKkq.png)

**Comment by HEIGE-PCloud** [comment]
@cxcn 代码块完全展开/部分展开+滚动条，你觉得哪一种更好一些？

https://do-it-git-fix-max-height-pcloud.vercel.app/zh-cn/theme-documentation-basics/#site-configuration

**Comment by nopdan** [comment]
> 

@HEIGE-PCloud  个人倾向于 部分展开+滚动条
