### ISSUE TITLE
添加阅读模式按钮

### ISSUE THREAD

**Issue by coderiy** [HEIGE-PCloud/DoIt#546]
### Describe the feature you want 描述你的功能需求

如下图所示，点击阅读模式按钮可以隐藏评论等无关内容，专注于阅读
![image](https://user-images.githubusercontent.com/44196120/160559585-48da7b79-6849-4783-9f03-5fb9981674b9.png)
![image](https://user-images.githubusercontent.com/44196120/160559713-51ae8b1c-ee52-47ba-b314-4b7df7a0ce3d.png)

### Useful reference 有价值的参考

参考这个博客:[https://bbing.com.cn/202201/glibc-exit/#comments](https://bbing.com.cn/202201/glibc-exit/#comments)

**Comment by HEIGE-PCloud** [comment]
1. 一个很宽的页面并不适合阅读：

中文排版时，每行文字最优的个数是多少？ - 钱争予的回答 - 知乎
https://www.zhihu.com/question/19621078/answer/21969751

2. 隐藏侧边目录反而会让浏览与跳转更困难。
3. 顶部跳转栏的高度只有 3.5rem，与其隐藏他不如点一下 F11 全屏看效果更显著。
