### ISSUE TITLE
[BUG] 首页摘要公式未被渲染

### ISSUE THREAD

**Issue by WingsZeng** [HEIGE-PCloud/DoIt#547]
### Describe the bug 描述你遇到的错误

首页文章摘要中的 katex 公式不会被渲染.

### Expected behavior 期待的行为

摘要中的 katex 数学公式能够渲染

### Screenshots 屏幕截图

![Screenshot from 2022-03-29 20-56-45](https://user-images.githubusercontent.com/50052878/160616206-d0bc09d5-c89e-42d5-a8b5-b4374954377f.png)

### Build Environment 构建环境

Theme version: https://github.com/HEIGE-PCloud/DoIt/commit/1c13f5a4e6fc2e8de4f900719a95ffbafe2897d4
Hugo version: v0.96.0+extended

**Comment by HEIGE-PCloud** [comment]
具体哪些区域中的内容需要被 KaTeX 渲染呢？

自从上次发现 KaTeX 与 Waline 评论区有冲突之后，我把 KaTeX 的渲染范围局限在了 #content 中。

https://github.com/HEIGE-PCloud/DoIt/commit/c57591bea16ce80279231ffb4df826132b944ccb

除去首页文章摘要之外，还有哪些区域需要 KaTeX 支持呢？标题？table of content？还是说我应该仅排除 #comment 元素，依旧渲染剩余的所有页面？

Reference:
https://katex.org/docs/autorender.html
ignoredClasses: This is a list of DOM node class names to ignore when recursing through. By default, this value is not set.

**Comment by WingsZeng** [comment]
抱歉没能及时回复.

我认为仅排除 comment 元素是一个很好的方法, Waline 本身支持渲染数学公式.

BTW, 7e4a164 存在一点点问题: 首页没有 id 为 `content` 的元素, 不会进入 if 分支.
