### ISSUE TITLE
[FEATURE] shortcode的image提供referrerPolicy类似的属性

### ISSUE THREAD

**Issue by SenLief** [HEIGE-PCloud/DoIt#551]
### Describe the feature you want 描述你的功能需求

目前在用yuque写一些东西，语雀是不支持外链也不支持url方式的引入，不过可以通过设置referrerPolicy属性来规避一下防盗链。

### Useful reference 有价值的参考

主要是想用语雀作为hugo的后端编辑器和管理，需要处理一下防盗链的问题，同时也想用shortcode的image来实现点击放大的功能，不知道能否提供类似于<img src="" referrerPolicy="no-referrer" />这类的效果。

**Comment by HEIGE-PCloud** [comment]
可以自行修改 meta.html

https://github.com/HEIGE-PCloud/DoIt/blob/main/layouts/partials/head/meta.html

或者 image.html

https://github.com/HEIGE-PCloud/DoIt/blob/main/layouts/partials/plugin/image.html

或者使用正经 CMS 如 [Netlify CMS](https://www.netlifycms.org/docs/hugo/) 和 [Forestry](https://forestry.io/)

Reference:
https://github.com/x-cold/yuque-hexo/issues/41
