### ISSUE TITLE
[BUG] 网站分析如 google analytics 无法追踪页面

### ISSUE THREAD

**Issue by WingsZeng** [HEIGE-PCloud/DoIt#562]
### Describe the bug 描述你遇到的错误

由于使用 pjax, 网站分析如 google analytics, 无法追踪浏览的页面. google analytics 具体表现为统计到的页面为第一次加载时的链接, 站内链接跳转无法追踪.

相关资料:
- https://github.com/MoOx/pjax/issues/56
- https://github.com/jerryc127/hexo-theme-butterfly/issues/516
- https://developers.google.com/tag-platform/gtagjs/reference#event
- https://developers.google.com/tag-platform/gtagjs/reference/events#page_view

### Build Environment 构建环境

- Theme version: f11363b
- Hugo version: hugo v0.96.0+extended

**Comment by HEIGE-PCloud** [comment]
有趣的是，其他的 analytics 大多都对 pjax 有直接的支持。。。

https://developers.cloudflare.com/analytics/web-analytics/getting-started/web-analytics-spa/
https://umami.is/docs/faq
https://plausible.io/docs/spa-support
