### ISSUE TITLE
[FEATURE] Code-Block-Fullscreen

### ISSUE THREAD

**Issue by kkbt0** [HEIGE-PCloud/DoIt#568]
### Describe the feature you want 描述你的功能需求

I noticed that a scroll bar was added to the code block in the update. This does provide convenience for quick browsing, but reading the code is a little cumbersome. I have seen such a solution, that is, full screen code blocks. It should be able to solve the problem of reading code.

WordPress Theme Sakura does this, and the theme has a hexo version.

[https://github.com/honjun/hexo-theme-sakura](https://github.com/honjun/hexo-theme-sakura)

In [https://cndrew.cn/2020/06/01/UCF2014/](https://cndrew.cn/2020/06/01/UCF2014/) You can see the effect in this page.

Therefore, it should be possible to add a full screen next to the copy button to read the code.

---
我注意到更新中为代码块添加了滚动条。这确实为快速浏览提供了方便，但是阅读代码稍微繁琐了些。我曾经见到过这样一种解决方法，即全屏代码块。应该能很好地解决阅读代码的问题。

WordPress Theme Sakura 就是这样做的，并且这个主题有 Hexo 版本。

https://github.com/honjun/hexo-theme-sakura

在 [https://cndrew.cn/2020/06/01/UCF2014/](https://cndrew.cn/2020/06/01/UCF2014/) 这个网页中可以看到效果。

因此，应该可以在复制按钮旁边添加一个全屏来阅读代码。

### Useful reference 有价值的参考

Example:
[https://cndrew.cn/2020/06/01/UCF2014/](https://cndrew.cn/2020/06/01/UCF2014/)

ThemeCode:
[https://github.com/honjun/hexo-theme-sakura](https://github.com/honjun/hexo-theme-sakura)
[https://github.com/honjun/hexo-theme-sakura/blob/master/themes/Sakura/source/js/sakura-app.js](https://github.com/honjun/hexo-theme-sakura/blob/master/themes/Sakura/source/js/sakura-app.js)

**Comment by kkbt0** [comment]
我尝试了下,在 themes\DoIt\assets\js\theme.js 的 `$title.addEventListener('click', () => { })` 下增加使用 requestFullscreen() 这样的 API 实现全屏，虽然和预期不同，但是手机上显示效果还不错。

**Comment by ryan4yin** [comment]
我也觉得当前代码块的处理方式有点不合适，max_height 比较小，而且无法自定义。

我观察到 CodeIT 的做法是在 `assets/css/_partial/_single/_code.scss` 里设置了一个非常大的 max_height

```
      .table-wrapper {
        max-height: 12000vh;
        overflow-y: auto;
        @include details-transition-close;
      }
```

感觉 CodeIT 这种做法挺合理的，代码块太长的话默认会被收起，我如果点击展开，当然是希望直接查看代码的所有内容。

**Comment by ryan4yin** [comment]
比如我有些文章中会用代码块来展示 ascii 字符画，当前 DoIt 设置的 max_height 就有点不够用，画的下面几行会被折叠，需要往下滑动才能看到。效果就有些差：

但是同样的 ascii 字符画在 github 里是能正常展示的，并且也可以左右拖动：
```
+-----------------------------------------------+-----------------------------------+-----------------------------------+
|                      Host                     |           Container A             |           Container B             |
|                                               |                                   |                                   |
|   +---------------------------------------+   |    +-------------------------+    |    +-------------------------+    |
|   |       Network Protocol Stack          |   |    |  Network Protocol Stack |    |    |  Network Protocol Stack |    |
|   +----+-------------+--------------------+   |    +-----------+-------------+    |    +------------+------------+    |
|        ^             ^                        |                ^                  |                 ^                 |
|........|.............|........................|................|..................|.................|.................|
|        v             v  ↓                     |                v                  |                 v                 |
|   +----+----+  +-----+------+                 |          +-----+-------+          |           +-----+-------+         |
|   | .31.101 |  | 172.17.0.1 |      +------+   |          | 172.17.0.2  |          |           |  172.17.0.3 |         |
|   +---------+  +-------------<---->+ veth |   |          +-------------+          |           +-------------+         |
|   |  eth0   |  |   docker0  |      +--+---+   |          | eth0(veth)  |          |           | eth0(veth)  |         |
|   +----+----+  +-----+------+         ^       |          +-----+-------+          |           +-----+-------+         |
|        ^             ^                |       |                ^                  |                 ^                 |
|        |             |                +------------------------+                  |                 |                 |
|        |             v                        |                                   |                 |                 |
|        |          +--+---+                    |                                   |                 |                 |
|        |          | veth |                    |                                   |                 |                 |
|        |          +--+---+                    |                                   |                 |                 |
|        |             ^                        |                                   |                 |                 |
|        |             +------------------------------------------------------------------------------+                 |
|        |                                      |                                   |                                   |
|        |                                      |                                   |                                   |
+-----------------------------------------------+-----------------------------------+-----------------------------------+
         v
    Physical Network  (192.168.31.0/24)
```

**Comment by ryan4yin** [comment]
> 我尝试了下,在 themes\DoIt\assets\js\theme.js 的 `$title.addEventListener('click', () => { })` 下增加使用 requestFullscreen() 这样的 API 实现全屏，虽然和预期不同，但是手机上显示效果还不错。

顺便我觉得这个 idea 的效果也很棒~

**Comment by HEIGE-PCloud** [comment]
我不打算实现这个全屏的功能。我用了另一种方式修复了过长代码会被隐藏的问题。如果需要全屏阅读，那么按 F11 使用浏览器的原生全屏功能就完全足够了。

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/52968553/168389609-7fcbdddb-3e27-4388-b64e-ae61e155e097.png">
