### ISSUE TITLE
[BUG] partials/meta/author.html:8: unclosed action.

### ISSUE THREAD

**Issue by HuangPingyang1** [HEIGE-PCloud/DoIt#577]
使用Github Action编译时出错了。

Error: add site dependencies: load resources: loading templates: ./themes/DoIt/layouts/partials/meta/author.html:8:1": parse failed: template: partials/meta/author.html:8: unclosed action.

**Comment by HEIGE-PCloud** [comment]
https://github.com/HuangPingyang1/HuangPingyang1.github.io/blob/8a81bd79e2b57b5adecdfb4ee2797dbf93c4b5b0/.github/workflows/gh-pages.yml#L22

你的 Hugo 版本太老了。请使用至少 0.83 以上的版本，且建议开启 extend。
