### ISSUE TITLE
[BUG] Shortcode加载不出来

### ISSUE THREAD

**Issue by natsuboy** [HEIGE-PCloud/DoIt#627]
### Describe the bug 描述你遇到的错误

1. gist shortcode 刷新一次才能加载出来，与 https://github.com/HEIGE-PCloud/DoIt/issues/575 类似；
2. tweet、vimeo、youtube shortcode加载不出来。

页面链接：https://www.alphabeta.top/theme-documentation-built-in-shortcodes/

### Expected behavior 期待的行为

正常加载

### Screenshots 屏幕截图

<img width="806" alt="image" src="https://user-images.githubusercontent.com/64178062/170158591-bb11b2c6-f736-4bed-a59a-17409e86b91d.png">

<img width="805" alt="image" src="https://user-images.githubusercontent.com/64178062/170158652-60360058-330c-4868-8d59-c8bb71c77f67.png">

### Build Environment 构建环境

- OS：mac 12.2.1
- Theme Version：0.2.13
- Hugo Version：0.99.1

### Additional Information 补充信息

console log:
Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
(anonymous) @ [7896402.js:1](https://gist.github.com/spf13/7896402.js)

**Comment by HEIGE-PCloud** [comment]
GitHub gist 使用 `document.write` 向 DOM 写入内容，这种方式在 pjax 加载的情况下会[产生问题](https://stackoverflow.com/questions/24297829/execute-write-on-doc-it-isnt-possible-to-write-into-a-document-from-an-asynchr)。

可以通过[重载 `document.write`](https://gist.github.com/danshearmur/1993718) 的方法来绕过这一限制，但是相比于选择这种 dirty hack，我更倾向与通过 [`resources.GetRemote`](https://gohugo.io/hugo-pipes/introduction/) 重写一个在 `hugo build` 阶段渲染 gist 的 shortcode。

tweet shortcode 在旧版的 Hugo 中存在一些问题，所以从文档中移除了。如果你使用的是较新版本的 Hugo，它可以[正常工作](https://gohugo.io/content-management/shortcodes/#example-tweet-input)。

vimeo 和 youtube shortcode 在我的环境中均可以正常工作。
