### ISSUE TITLE
[BUG] 首页底部文章跳转详情后定位不对

### ISSUE THREAD

**Issue by natsuboy** [HEIGE-PCloud/DoIt#630]
### Describe the bug 描述你遇到的错误

首页滑到底，点击最下面的文章进入详情后会直接定位在文章的末尾，但是如果在首页滑到底后再往上滑一点，再点进去就不会直接到底。

### Expected behavior 期待的行为

进入文章详情后不会直接到底。

### Screenshots 屏幕截图

https://user-images.githubusercontent.com/64178062/170813596-9be9106b-ce8f-48d7-8517-7cc104eb0809.mov

**Comment by HEIGE-PCloud** [comment]
我在 Firefox 上复现成功了，在 Chrome 上没有。在 Firefox 上有些时候 `window.scrollTo()` 没有生效，也不知道为什么。。。

**Comment by coderiy** [comment]
> 我在 Firefox 上复现成功了，在 Chrome 上没有。在 Firefox 上有些时候 `window.scrollTo()` 没有生效，也不知道为什么。。。

我有时候点击下一篇的时候也会出现不能回到顶部的情况,比如[这篇文章](https://hugo.bnblogs.cc/ubuntu20.04%E4%BD%BF%E7%94%A8%E8%AE%B0%E5%BD%95/#5%E6%9F%A5%E7%9C%8B%E5%AE%9D%E5%A1%94%E9%9D%A2%E6%9D%BF%E7%94%A8%E6%88%B7%E5%92%8C%E5%AF%86%E7%A0%81)，点击下一篇文章[java-异常、断言和日志](https://hugo.bnblogs.cc/java-6/)怎么都是到一个中间位置
