### ISSUE TITLE
Article home page image hover image URL instead of   Title

### ISSUE THREAD

**Issue by wyxogo** [HEIGE-PCloud/DoIt#631]
### Describe the bug 描述你遇到的错误

Article home page image hover image URL instead of   Title
![image](https://user-images.githubusercontent.com/61509470/170825111-86be38e9-c55b-4085-b345-2eced8d3c563.png)

### Expected behavior 期待的行为

display  article “title”

**Comment by HEIGE-PCloud** [comment]
你需要正确配置文章摘要。文章的摘要会被显示为 img title。
![image](https://user-images.githubusercontent.com/52968553/170828441-1633490e-2373-4c41-9a17-a30da3aac245.png)

https://github.com/HEIGE-PCloud/DoIt/blob/fce285751f7ae1b2b4b9dc848fe32a1d10bac786/exampleSite/content/posts/theme-documentation-basics/index.zh-cn.md?plain=1#L20-L23
