### ISSUE TITLE
[FEATURE] 二级菜单

### ISSUE THREAD

**Issue by bwcxyk** [HEIGE-PCloud/DoIt#649]
### Describe the feature you want 描述你的功能需求

我不清楚现在有没有二级菜单的功能，如果没有希望可以增加。有这个功能的话告知一下如何配置。

**Comment by HEIGE-PCloud** [comment]
Duplicate #451

**Comment by bwcxyk** [comment]
应该和这个是一样的[https://github.com/HEIGE-PCloud/DoIt/issues/451](https://github.com/HEIGE-PCloud/DoIt/issues/451)
