### ISSUE TITLE
[BUG] Fresh new site - 'You have an incompatible update'

### ISSUE THREAD

**Issue by mlazzarotto** [HEIGE-PCloud/DoIt#660]
### Describe the bug 描述你遇到的错误

Hi, I'm following the documentation here https://hugodoit.pages.dev/theme-documentation-basics/#basic-configuration= and I'm having a problem, as hugo doesn't start following error
```
Start building sites … 
hugo v0.101.0-9f74196ce611cdf6d355bfb99fd8eba5c68ef7f8+extended linux/amd64 BuildDate=2022-06-28T10:02:18Z VendorInfo=snap
ERROR 2022/07/22 22:36:10 Compatibility Error 兼容性错误

0.2.13 -> 0.2.X:
You have an incompatible update. See https://github.com/HEIGE-PCloud/DoIt/releases
你进行了一次不兼容的更新. 参考 https://github.com/HEIGE-PCloud/DoIt/releases

WARN 2022/07/22 22:36:10 

Current environment is "development". The "comment system", "PWA", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "PWA", "CDN" 和 "fingerprint" 不会启用.

Error: Error building site: logged 1 error(s)
Built in 71 ms
```

Steps taken 

1. `hugo new site mlazzarotto.it`
2. `cd mlazzarotto.it`
3. `git init`
4. `git submodule add https://github.com/HEIGE-PCloud/DoIt.git themes/DoIt`
5. pasted **Basic Configuration** from hugodoit.pages.dev paying attention to set _version_ to _0.2.13_ **before** starting hugo server

### Expected behavior 期待的行为

Site build

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/8932945/180563683-91520d2a-a49b-432d-9f10-4d3ccf900e51.png)

### Build Environment 构建环境

- OS: Pop!_OS 22.04 LTS
- Hugo: v0.101.0-9f74196ce611cdf6d355bfb99fd8eba5c68ef7f8+extended
- Theme: DoIt 0.2.13

### Additional Information 补充信息

Trying to delete the site _rm -rf mlazzarotto.it_ and starting from scratch changed nothing.
Yesterday at some point it was starting but giving error with missing layouts, so I decided to delete and start from scratch

**Comment by HEIGE-PCloud** [comment]
Follow the documentation here to set up the config.toml
https://hugodoit.pages.dev/theme-documentation-basics/
