### ISSUE TITLE
[BUG] Some features are not available on safari i.e RSS and Share links

### ISSUE THREAD

**Issue by kevinrobayna** [HEIGE-PCloud/DoIt#672]
### Describe the bug 描述你遇到的错误

I can't share a blog on twitter or linkedin when browsing on safari. Nor I can subscribe to RSS (or see the logo or anything)

see config here https://github.com/kevinrobayna/kevinrobayna.github.io/blob/master/config.toml#L176

### Expected behavior 期待的行为

I should be able to share a post or subscribe to RSS

### Screenshots 屏幕截图

Safari
![image](https://user-images.githubusercontent.com/5471469/183471778-bc87860d-5930-4e1b-a87b-7bc083ab14a9.png)
![image](https://user-images.githubusercontent.com/5471469/183471919-a7a809eb-14ce-4e63-a912-f5961d10cca2.png)

Chrome
![image](https://user-images.githubusercontent.com/5471469/183471860-73206a5c-dc73-45d4-b9fe-17436af1e93e.png)
![image](https://user-images.githubusercontent.com/5471469/183471954-1e295846-d3c8-47a6-8496-26a1ab57e2e0.png)

### Build Environment 构建环境

0.101.0

### Preview Environment 预览环境

MacOs/Linux

**Comment by HEIGE-PCloud** [comment]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/52968553/183617153-9c0cbe09-154d-47ce-baf8-062f71da811f.png">

Not sure what is going on, but the RSS icon shows up in my Safari environment...

**Comment by kevinrobayna** [comment]
Hello @HEIGE-PCloud any explanation?

**Comment by kevinrobayna** [comment]
Oh that’s odd! Sorry about that!

**Comment by kevinrobayna** [comment]
I found the reason! If you have an adblocker it might remove the links! It's weird it usually just removed cookies but i guess it doesn't like the way the share  and rss links are
