### ISSUE TITLE
[FEATURE] Using Mathjax instead of Katex （使用Mathjax而不是Katex）

### ISSUE THREAD

**Issue by forrestk3** [HEIGE-PCloud/DoIt#691]
### Describe the feature you want 描述你的功能需求

我想使用Mathjax来解析我的数学公式，因为Katex有的公式解析不出来，我应该怎么作?
I want to use Mathjax to parse my math formulas instead of Katex, what should I do?

**Comment by HEIGE-PCloud** [comment]
hi，我在 mathjax 分支上添加了对 mathjax 的基本支持 https://github.com/HEIGE-PCloud/DoIt/tree/mathjax

在我为所有 mathjax 的可配置项添加支持之后即可将其合并进入主分支。

需要注意的是，hugo 对于数学公式的支持非常欠佳，你可能需要考虑 [math shortcode](https://hugodoit.pages.dev/theme-documentation-content/#math) 来避免奇怪的 escape 问题。

https://github.com/HEIGE-PCloud/DoIt/issues/126
