### ISSUE TITLE
[FEATURE] 画廊兼容markdown image写法

### ISSUE THREAD

**Issue by Y4er** [HEIGE-PCloud/DoIt#693]
### Describe the feature you want 描述你的功能需求

我从别的主题迁移过来，原来的文章都是用的

```
![image.png](http://baidu.com/1.png)
```

这种方式引入的图片，但是都不会被画廊加载，我应该如何修改主题设置来兼容这种图片画廊写法？

**Comment by HEIGE-PCloud** [comment]
https://github.com/HEIGE-PCloud/DoIt/commit/ae358def94db2246fbe51349bdf2f58f0f62c27b

修改了默认的行为，现在所有图片，无论是通过 Markdown 语法还是 image shortcode 插入的图片都会默认开启画廊。你只需要在每篇文章的 front matter 开启 `lightgallery: true`，或者直接在 config.toml 中为全站开启 light gallery 即可。

https://github.com/HEIGE-PCloud/DoIt/blob/ae358def94db2246fbe51349bdf2f58f0f62c27b/exampleSite/content/posts/basic-markdown-syntax/index.en.md?plain=1#L14

https://github.com/HEIGE-PCloud/DoIt/blob/ae358def94db2246fbe51349bdf2f58f0f62c27b/exampleSite/config.toml#L660-L662
