### ISSUE TITLE
[FEATURE] telegram、twitter等分享文章链接的时候，显示文章配图

### ISSUE THREAD

**Issue by yeahwong** [HEIGE-PCloud/DoIt#699]
### Describe the feature you want 描述你的功能需求

如果可以在telegram、twitter等分享链接的时候，显示文章插图，会美观很多啊。

### Useful reference 有价值的参考

<img width="378" alt="image" src="https://user-images.githubusercontent.com/5824590/186554020-7816ef8c-b7db-444c-af97-9827455e74c9.png">

https://www.politico.com/news/2022/07/21/us-telecom-companies-huawei-00047045

<img width="411" alt="image" src="https://user-images.githubusercontent.com/5824590/186554077-914d6e62-54dc-4160-a444-ec5825924d89.png">

https://www.wsj.com/articles/elon-musk-affair-sergey-brin-wife-divorce-11658674840

<img width="386" alt="image" src="https://user-images.githubusercontent.com/5824590/186554157-b3888d19-d918-4890-94ee-3120cb35d514.png">

https://podcasts.apple.com/ca/podcast/%E7%81%AB%E9%94%85%E4%BA%89%E9%9B%84-%E6%9C%8D%E5%8A%A1%E8%87%B3%E4%B8%8A-vs-%E4%BA%A7%E5%93%81%E4%B8%BB%E4%B9%89/id1088178402?i=1000571649649

<img width="364" alt="image" src="https://user-images.githubusercontent.com/5824590/186554314-06d0a4c4-a539-47a2-849e-0e66cf80a267.png">

https://twitter.com/fangshimin/status/1562584668825796608

**Comment by HEIGE-PCloud** [comment]
我记得是支持的，设置 featured-image 就行了。 telegram 预览好像不支持 webp 格式，所以得用 png 或者 jpg 格式的图片。

![ED14A912-CF1E-4ED8-A05B-FC60E9CA01C9](https://user-images.githubusercontent.com/52968553/186641817-48aee465-dde6-46ba-b4f2-c1b0e696a66a.jpeg)
![A46B5A4F-50B5-49B3-B0A0-E28ECBCE3AC8](https://user-images.githubusercontent.com/52968553/186641848-e5dd2534-9fc1-48ba-bcc4-09fe40b65da9.png)

**Comment by yeahwong** [comment]
好奇怪，我设置了featured-image，格式也是png，但telegram\twitter都抓不到图片。

这是个什么情况啊？

featuredImage: "/images/read-blockchain-in-action/1.png"

https://sogola.com/posts/read-blockchain-in-action/

<img width="466" alt="image" src="https://user-images.githubusercontent.com/5824590/186644017-6f7e4e7a-e3c3-41c2-8a58-ae837cfe86af.png">

**Comment by yeahwong** [comment]
在项目方 @HEIGE-PCloud 的教导下，我已经成功解决这个问题，感谢。

需要在

featuredImage: "/images/read-blockchain-in-action/1.png"

后面添加

images: ["/images/read-blockchain-in-action/1.png"]

再次感谢。
