### ISSUE TITLE
[FEATURE] 文章加密全局加密和部分加密

### ISSUE THREAD

**Issue by coderiy** [HEIGE-PCloud/DoIt#710]
### Describe the feature you want 描述你的功能需求

hugo加密，希望提供前端解决方案，不依赖 python 或者 golang,类似hugo-Fixit主题的效果

### Useful reference 有价值的参考

参考链接:[https://github.com/hugo-fixit/FixIt/issues/123](https://github.com/hugo-fixit/FixIt/issues/123)

**Comment by HEIGE-PCloud** [comment]
@JokerZhang66  Hugo 并不提供 crypto 相关的函数，所以没有办法实现任何安全的加密。
你[主页](https://github.bnblogs.cc/%E5%8D%9A%E5%AE%A2%E5%8A%9F%E8%83%BD%E5%B1%95%E7%A4%BA/
)上的密码是 `demo`，[这篇](https://github.bnblogs.cc/paper01/) 是 `paper`。 FixIt 的那个实现也非常容易 hack。所以我还是建议你使用专门的加密工具。
