### ISSUE TITLE
[BUG] 菜单按钮a标签跳转referer问题

### ISSUE THREAD

**Issue by penginman** [HEIGE-PCloud/DoIt#711]
### Describe the bug 描述你遇到的错误

在菜单中添加了一个跳转链接，但是跳转的网站规定任何有Referer的连接都被拦截，发现`layouts/partials/header.html`中35行和157行代码
https://github.com/HEIGE-PCloud/DoIt/blob/df89e4f43fc64a35d559b9299bdb40cab5b7f6b7/layouts/partials/header.html#L35
https://github.com/HEIGE-PCloud/DoIt/blob/df89e4f43fc64a35d559b9299bdb40cab5b7f6b7/layouts/partials/header.html#L157

rel属性为`noopener noreffer`，自己查了文档确实没有`noreffer`属性，只有`noreferrer`，自己本地修改以后跳转正常访问，请求头中也没有携带referer了

### Expected behavior 期待的行为

将属性中的`noreffer`修改为`noreferrer`

### Build Environment 构建环境

- OS：Windows 11
- Theme Version：0.2.13
- Hugo Version：v0.92.0-B3549403+extended

### Additional Information 补充信息

菜单的配置文件
 [[menu.main]]
    identifier = ""
    pre = "🚇"
    post = ""
    name = "开往"
    url = "https://travellings.link"
    title = "开往"
    weight = 6

**Comment by HEIGE-PCloud** [comment]
修了 https://github.com/HEIGE-PCloud/DoIt/commit/38ff0f81d7c7a073979123c97343d2a570189b3e
看了下 git blame 原来不是我写的（松了口气（
