### ISSUE TITLE
网站图标本地预览时正常，部署到GitHub消失了

### ISSUE THREAD

**Issue by zyyaria** [HEIGE-PCloud/DoIt#729]
### Describe the bug 描述你遇到的错误

![图片](https://user-images.githubusercontent.com/101989311/190854399-0bdf42a6-78d3-4d80-b0ac-05eb074155d4.png)
如图所示，第一个是本地预览的图标显示状态，第二个是部署到GitHub pages生成的图标显示状态，为什么它不见了？

**Comment by HEIGE-PCloud** [comment]
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/52968553/190876993-55dd04c5-c626-4861-9817-349731fe98c4.png">

我这边看没有问题，favicon 的配置也没问题。刷新下试试。

**Comment by zyyaria** [comment]
谢谢，查了一下是浏览器问题，清除了网页cookie和数据就显示了。
