### ISSUE TITLE
简单的静态页面文档，比如: content/about.md 没有生成目录，这个能支持吗 ?

### ISSUE THREAD

**Issue by xiaobinqt** [HEIGE-PCloud/DoIt#762]
有的静态页面，非文章类型的，比如 about.md ，比如放在 content/about/index.md ，这种不能支持目录，即使写了 toc 也不会生效，请问这个可以解决吗 ?

**Comment by HEIGE-PCloud** [comment]
需要目录的页面应该被放在 `content/posts/` 目录下。所以如果你需要为 about.md 生成目录，则应该使用 `content/posts/about/index.md`。
