### ISSUE TITLE
[BUG] Authors not being displayed

### ISSUE THREAD

**Issue by ferranpons** [HEIGE-PCloud/DoIt#766]
### Describe the bug 描述你遇到的错误

After adding authors files on the "/data/authors" folder they cannot being accessed and not listed on the "authors" page.
Even with changing the "/content/authors" index files to underscore like the exampleSite did not work.

Example: 

Code: 
- [https://github.com/HabitsWay/blog/tree/main/data/authors](https://github.com/HabitsWay/blog/tree/main/data/authors)

Website: 
- [https://blog.habitsway.com/authors/angie](https://blog.habitsway.com/authors/angie)
- [https://blog.habitsway.com/authors/](https://blog.habitsway.com/authors/)

Please could you check it out? I'm not sure if is a problem with my project or a bug.

Many thanks in advance.

### Expected behavior 期待的行为

The expected behavior is to display all the authors on the authors section and the individual author pages.

### Preview Environment 预览环境

- OS: MacOS
- Browser: Chrome

**Comment by HEIGE-PCloud** [comment]
Add

```toml
[taxonomies]
author = "authors"
```
to your config.toml
Reference: https://gohugo.io/content-management/taxonomies/

**Comment by ferranpons** [comment]
@HEIGE-PCloud many thanks for your quick response!
