### ISSUE TITLE
[FEATURE] ForkAwesome Fonts

### ISSUE THREAD

**Issue by stevolucidity** [HEIGE-PCloud/DoIt#769]
### Describe the feature you want 描述你的功能需求

Please would you consider adding forkawesome library so we can have more modern social media icons like Friendica, Pixelfed and Peertube?

### Useful reference 有价值的参考

https://forkaweso.me/Fork-Awesome/icon/friendica/

**Comment by HEIGE-PCloud** [comment]
Fontawesome and SimpleIcons should cover most cases, adding forkawesome will introduce too much duplication. Individual icons can be directly imported by source.

https://github.com/HEIGE-PCloud/DoIt/blob/bc2dc96d4ea7d0dc1e7238dd89e978c8f2b8653a/assets/data/social.yml#L450-L455
