### ISSUE TITLE
[FEATURE] General Video Support

### ISSUE THREAD

**Issue by ericsun95** [HEIGE-PCloud/DoIt#796]
### Describe the feature you want 描述你的功能需求

How could we add local video to dolt page? Currently it seems that it only support bilibili video.

### Useful reference 有价值的参考

- https://dev.to/hi_artem/add-a-video-to-your-hugo-website-104
- https://discourse.gohugo.io/t/embedding-local-video-in-static-img-or-page-folder-to-website/20220

**Comment by ericsun95** [comment]
By checking the example,

we need a file `video.html` in the folder `layouts/shortcodes` with some adaptions

```
<div class="container">
    <div id="player-wrapper" class="{{ .Get 1 }}"></div>
</div>

<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@clappr/player@latest/dist/clappr.min.js"></script>
<script>
  var playerElement = document.getElementById("player-wrapper");

  var player = new Clappr.Player({
    source: {{ .Get 0 }},
    mute: true,
    height: 360,
    width: 640
  });
  
  player.attachTo(playerElement);  
</script>

```

**Comment by HEIGE-PCloud** [comment]
Put something like this directly into the Markdown file should be sufficient

```
<video width="100%" controls>
  <source src="{link-to-your-video-file}" type="video/mp4">
</video>
```

**Comment by ericsun95** [comment]
Thanks! I found I can view it from the website while I can't see that from the phone?
