### ISSUE TITLE
Related Content Suggestions

### ISSUE THREAD

**Issue by sbkv1** [HEIGE-PCloud/DoIt#798]
### Describe the bug 描述你遇到的错误

Related Content Suggestions at the bottom of a post not working properly

### Screenshots 屏幕截图

<img width="549" alt="image" src="https://user-images.githubusercontent.com/93185814/205586201-476f254c-8ec3-4317-a12c-fa0a0759359f.png">

**Comment by HEIGE-PCloud** [comment]
The behaviour is expected, the post "Related tests" does not have a featured image so no image will show up.

**Comment by sbkv1** [comment]
I got this in that case I need to use a default image for every blog post and later change that.
