### ISSUE TITLE
In mobile blog post layout shifts 

### ISSUE THREAD

**Issue by SamirPaulb** [HEIGE-PCloud/DoIt#799]
While loading the blog post page the layout shifts. 
Please check the video attached.

https://user-images.githubusercontent.com/93185814/205631038-5fd31030-7afe-47e0-9e31-59a3f942a03c.mp4

**Comment by sbkv1** [comment]
@HEIGE-PCloud Can you please fix this bug. I have also checked; my blog also has the same problem.

**Comment by HEIGE-PCloud** [comment]
Things should get a lot better with #840

https://user-images.githubusercontent.com/52968553/213470595-cf97ce84-8ca4-4c28-9d29-7d869aadd445.mov
