### ISSUE TITLE
[BUG] typeit打印代码时不换行

### ISSUE THREAD

**Issue by coderiy** [HEIGE-PCloud/DoIt#804]
### Describe the bug 描述你遇到的错误

使用typeit的shortcode出错, **打印代码时不换行**，我看演示网站也有同样问题，原来的Loveit主题就没问题
```
{{< typeit code=java >}}
public class HelloWorld {
    public static void main(String []args) {
        System.out.println("Hello World");
    }
}
{{< /typeit >}}
```
![image](https://user-images.githubusercontent.com/44196120/206131036-2d3bc5b9-7d85-44be-ae8f-0ef02f390835.png)

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
#515 说明过了
目前想要正常打印的话可以参照[这个group的方法](https://hugodoit.pages.dev/theme-documentation-extended-shortcodes/#group-content)
> 如果打开没跳到位置就到目录下`typeit` -> `group-content`的部分

就是一行行写，然后归成一个group
比较蠢但是work

**Comment by coderiy** [comment]
> 
这样啊，感觉这样还不如之前的

**Comment by coderiy** [comment]
希望后面有更好的方式吧
