### ISSUE TITLE
[BUG] code block 命令行溢出

### ISSUE THREAD

**Issue by starsareintherose** [HEIGE-PCloud/DoIt#81]
### Describe the bug 描述你遇到的错误
code block 命令行溢出

### Expected behavior 期待的行为

code block 可以滑动

### Screenshots 屏幕截图

![2021-05-29 03-40-09 的屏幕截图](https://user-images.githubusercontent.com/37733075/120034673-fe74de80-c02f-11eb-9d4c-4d12ceac6f67.png)

### Build Environment 构建环境

- OS: ArchLinux
- Theme version/commit [latest]
- Hugo version [latest]

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

### Preview Environment 预览环境

- OS: ArchLinux
- Theme version/commit [latest]
- Hugo version [latest]

**Comment by HEIGE-PCloud** [comment]
![image](https://user-images.githubusercontent.com/52968553/120041694-a07cd280-c000-11eb-97d4-64b430d96994.png)

[修复完成](https://hugodoit.pages.dev/markdown-tests/#code)，请更新主题至最新的commit。
