### ISSUE TITLE
[FEATURE] Douban Movie and Book Showpage / 豆瓣观影

### ISSUE THREAD

**Issue by eallion** [HEIGE-PCloud/DoIt#812]
### Describe the feature you want 描述你的功能需求

我自己糊了一个豆瓣观影记录的页面，因为这是一个小众需求，而且兼容性可能有问题，就没有提交 PR。
如果觉得这个有需要，可以更新一下。

### Useful reference 有价值的参考

我的豆瓣观影页面：
- https://eallion.com/movie/

参考：
- https://imnerd.org/doumark.html
- https://github.com/lizheming/doumark-action
- https://github.com/lmm214/immmmm/blob/master/themes/hello-friend/layouts/_default/movies.html

我的源文件：
- https://github.com/eallion/eallion.com/blob/main/layouts/_default/movie.html

**Comment by HEIGE-PCloud** [comment]
谢谢你的分享！这个需求确实比较小众且复杂，所以我暂时不打算将它合并或实现。我将会把这个 issue 关闭，但有相似需求的小伙伴还是可以搜索到它。你也可以写一篇博客来分享它的实现过程。

再次感谢你的分享 :)
