### ISSUE TITLE
[FEATURE] 友情链接卡片

### ISSUE THREAD

**Issue by starsareintherose** [HEIGE-PCloud/DoIt#82]
### Describe the feature you want 描述你的功能需求

- Feature  功能需求 友情链接卡片

### Useful reference 有价值的参考

https://9lewl.com/Friends.html

https://bore.vip/archives/hugo-theme-LoveIt/
（根据这个链接，本主题不显示图片）

**Comment by HEIGE-PCloud** [comment]
友链已经支持了，这是相关[文档](https://hugodoit.pages.dev/zh-cn/theme-documentation-extended-shortcodes/#12-friend)，这是[测试页面](https://hugodoit.pages.dev/friend-link-tests/)。

**Comment by yeahwong** [comment]
在手机上测试友情链接卡页面，如果网站标题过长，手机页面上会出现友情链接卡错落的现象，网站名称与头像会挤在一起。
