### ISSUE TITLE
能支持 markdown 的思维导图吗？

### ISSUE THREAD

**Issue by xiaobinqt** [HEIGE-PCloud/DoIt#824]
比如 markmap 

[https://github.com/markmap/markmap](https://github.com/markmap/markmap)

[try it markmap](https://markmap.js.org/repl)

![image](https://user-images.githubusercontent.com/23259661/210160797-27b17d42-3d33-4b77-be02-fcc607e26970.png)

**Comment by HEIGE-PCloud** [comment]
请问你的使用场景是什么呢？
