### ISSUE TITLE
[FEATURE] Twitter Card

### ISSUE THREAD

**Issue by TheDoubleH** [HEIGE-PCloud/DoIt#826]
### Describe the feature you want 描述你的功能需求

When sharing posts via twitter, the preview is very generic.

I would be preferable to enable "twitter cards"

I would suggest that: 
 - the twitter id is inherited from Setup
 - Image is derived from `featuredimage` in post toml
 - Description and title from the post as well

### Useful reference 有价值的参考

partials and guide example: https://gohugohq.com/partials/twitter-cards-partials-for-hugo/
Official Twitter documentation: https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

**Comment by HEIGE-PCloud** [comment]
DoIt uses Hugo's internal twitter card template, you can follow the guide [here](https://gohugo.io/templates/internal/#twitter-cards) to set it up!
