### ISSUE TITLE
[BUG] 系列series输入特定名词会报错

### ISSUE THREAD

**Issue by Ignareo** [HEIGE-PCloud/DoIt#830]
### Describe the bug 描述你遇到的错误

在md文档的yaml栏配置`series: []`，输入”摘录“出现如下报错（”/摘录“、”\摘录“也同样报错）
”摘 录“、”-摘录“、等其他词都正常

报错命令行：
```text
ERROR Rebuild failed: failed to render pages: render of "page" failed: "D:\Hugo-Blog\site_3\themes\DoIt\layouts\posts\single.html:165:42": execute of template failed at <$.Site.GetPage>: error calling GetPage: page reference "/摘录" is ambiguous
```

### Build Environment 构建环境

- hugo version: hugo v0.109.0-47b12b83e636224e5e601813ff3e6790c191e371+extended windows/amd64 BuildDate=2022-12-23T10:38:11Z VendorInfo=gohugoio
- DoIt version: https://github.com/HEIGE-PCloud/DoIt/commit/3df8684442924897ec740b34a8a251bea4106afb

**Comment by HEIGE-PCloud** [comment]
这个问题可能和你的配置有关，也可能是 Hugo 的 bug https://github.com/gohugoio/hugo/issues/7016

由于缺乏足够的信息，我暂时关闭了该 Issue。请提供 [最小重现](https://antfu.me/posts/why-reproductions-are-required-zh) 以重新开启 Issue。谢谢。
