### ISSUE TITLE
[BUG] pjax 强制刷新

### ISSUE THREAD

**Issue by Cnily03** [HEIGE-PCloud/DoIt#839]
### Describe the bug 描述你遇到的错误

页面跳转时，当前页面或目的页面为 markdown 渲染出的 page 或 article 时在加载完后会强制刷新（有几次会正常，然后多试几次又不正常了），阻止页面刷新并添加输出代码后定位到 pjax 报错：
```plain
DOM doesn’t look the same on new loaded page: ’link[rel="next"]’ - new 1, old 0
```
删除 `assets/js/theme.js` 中 new Pjax 中的以下部分后恢复正常
https://github.com/HEIGE-PCloud/DoIt/blob/b583b0c6a672601ba4b0ab2e0ebcfa2f6f4391e0/assets/js/theme.js#L887-L889

### Expected behavior 期待的行为

希望解决这一问题（或许修复？删掉 New Pjax 中的三个 link[rel] 或许会起作用？但这三条的用途是什么）

### Build Environment 构建环境

- **OS:** Windows 10, Debian 11
- **Theme:** branch `master` (up to 2023/1/17)
- **Hugo version:** 0.105.0

**Comment by HEIGE-PCloud** [comment]
https://github.com/HEIGE-PCloud/DoIt/pull/709

**Comment by HEIGE-PCloud** [comment]
我现在真的觉得 pjax 的意义不大。pjax 本质上就是把 HTML fetch 下来，然后找对应的元素做替换。相较于直接点击链接跳转，所有的 CSS/JS 文件都是会被浏览器缓存的，该下载的 HTML 还是要全部下载，本质上对于加载速度也没啥提升。作为一个博客主题，本身也不提供多少的交互功能，这种 Single Page App 的设计似乎也并不一定是必须的...

**Comment by Cnily03** [comment]
Pjax 在博客上的应用确实并不大，但是现在的情况是**加载 Pjax -> 刷新**，于是就造成了下面这样的结果：在 Pjax 正常加载完一个页面后再触发错误进行刷新（这样刷新就显得多此一举了。部署上服务器后，在 Pjax 触发刷新后，网络不稳定的情况下浏览器会有1s-5s左右的时间处于刷新状态而不能操作网页——此时页面已经被 Pjax 加载过一次），相当于刷新了两次

下面是在本地调试的情况截图

![abnormal_1](https://user-images.githubusercontent.com/56472849/213419434-b3e920ea-9d67-47ec-a258-c5558aa4087b.gif)
![abnormal_2](https://user-images.githubusercontent.com/56472849/213419443-a04ced09-2444-4895-9045-9bd9ecd3e983.gif)

这两种情况交织在一起的情况有些恼人，修改 `new Pjax()` 中的 constructor 参数则需要对整个 `theme.js` 进行操作，不利于后期更新等维护操作。如果能加一个开关或者对 Pjax selector 的配置将显得不错（不知道是否是冗余功能）。

**Comment by Cnily03** [comment]
这种刷新两次的情况仅存在于涉及 single page 的情况，从**所有文章** 跳转到 **标签** 就不会有这个问题。如上述添加 link[rel] 的issue所提到的，去掉 link[rel] 又会回到原来的 bug...

但触发 pjax 错误而强制刷新实际上是由于这两条而并不是 `link[rel="canonical"]`
https://github.com/HEIGE-PCloud/DoIt/blob/b583b0c6a672601ba4b0ab2e0ebcfa2f6f4391e0/assets/js/theme.js#L888-L889

期待一个解决方案……
