### ISSUE TITLE
[FEATURE] 更换Researchgate图标

### ISSUE THREAD

**Issue by starsareintherose** [HEIGE-PCloud/DoIt#84]
### Describe the feature you want 描述你的功能需求

- Feature 更换Researchgate图标，别的社交媒体都是圆角，RG是直角
- ...

### Useful reference 有价值的参考

If available, provide useful links to fulfill the feature.
如果可以的话, 提供实现这个功能的相关参考链接.

**Comment by HEIGE-PCloud** [comment]
图标均来自于 [Font Awesome](https://fontawesome.com/v5.15/icons/researchgate)
