### ISSUE TITLE
Performance Improvement Plan

### ISSUE THREAD

**Issue by HEIGE-PCloud** [HEIGE-PCloud/DoIt#843]
- [ ] Move all js/css assets to the `head` and load by `defer` and `async` appropriately.
- [x] Load search component on click.
- [ ] Add an option to allow inline icons as SVGs inside HTML. (#619) 
- [ ] Split `style.scss` into appropriate chunks and only load necessary parts.
- [ ] Refactor `theme.js`

**Comment by wu0407** [comment]
- [ ] Using [hugo-pipes](https://gohugo.io/hugo-pipes)  (Gulp or grunt or webpack or browserify) to hash URLs and compress CSS and JavaScript files
