### ISSUE TITLE
[BUG] html 格式后缀与 md 冲突，导致不能正常显示页面或者文章

### ISSUE THREAD

**Issue by Mejituu** [HEIGE-PCloud/DoIt#848]
### Describe the bug 描述你遇到的错误

在每个页面或者文章设置字段 url 为 xxx.html 时，同时配置文件 outputs 也开启了页面 md 输出

实际上
访问 xxx.html 显示的是一个 html 格式的 md 代码
访问 xxx.md 显示的是 md 格式的正常原文件

### Expected behavior 期待的行为

正常通过 xxx.html 访问文章或页面
正常通过 xxx.md 访问文章或页面 原文件

### Build Environment 构建环境

109

### Preview Environment 预览环境

Debian testing

### Additional Information 补充信息

page = ["HTML", "MarkDown"]

url = "about.html"

**Comment by HEIGE-PCloud** [comment]
我没有太明白你的问题是什么。。。以文档站点为例

HTML 输出 https://hugodoit.pages.dev/theme-documentation-basics/index.html

Markdown 输出 https://hugodoit.pages.dev/theme-documentation-basics/index.md

**Comment by HEIGE-PCloud** [comment]
你可能可以通过查阅 [URL Management](https://gohugo.io/content-management/urls/) 和 [Content Organization](https://gohugo.io/content-management/organization/) 相关文档来理解相关配置。
