### ISSUE TITLE
[BUG] Contents被转移到头部而不是侧边栏

### ISSUE THREAD

**Issue by starsareintherose** [HEIGE-PCloud/DoIt#85]
### Describe the bug 描述你遇到的错误

Contents被转移到头部而不是侧边连

### Expected behavior 期待的行为

Contents转移到侧边栏

### Screenshots 屏幕截图

![2021-05-29 09-51-06 的屏幕截图](https://user-images.githubusercontent.com/37733075/120054595-67c21500-c063-11eb-805c-0ee99b6bf220.png)

### Build Environment 构建环境

- OS: [ArchLinux]
- Theme version/commit [latest]
- Hugo version [latest]

Please try to use Hugo **extended** version before opening the issue.
请在创建 issue 之前尝试使用 Hugo **extended** 版本.

### Preview Environment 预览环境

- OS: [ArchLinux]
- Theme version/commit [latest]
- Hugo version [latest]

### Additional Information 补充信息

Configuration files or front matter code...
配置文件或者前置参数的代码...

**Comment by HEIGE-PCloud** [comment]
你好好读一下文档吧，别啥都发issue

https://hugodoit.pages.dev/zh-cn/theme-documentation-basics/#site-configuration
