### ISSUE TITLE
[Improvement] Remove table-wrapper

### ISSUE THREAD

**Issue by HEIGE-PCloud** [HEIGE-PCloud/DoIt#861]
There is no point keep using a table-wrapper, the overflow scroll problem has been solved.

**Comment by wey-gu** [comment]
Is it the table wrapper that truncates tables, please?

<img width="824" alt="Screenshot 2023-03-01 at 12 06 47" src="https://user-images.githubusercontent.com/1651790/222042457-65f49dac-d67c-46bb-8804-c92b6af8fe2e.png">

Chapter: https://www.siwei.io/ngql-execution-plan/#%E8%AE%A4%E8%AF%86%E7%AE%97%E5%AD%90

**Comment by HEIGE-PCloud** [comment]
@wey-gu Should be fixed with https://github.com/HEIGE-PCloud/DoIt/commit/01c4bdd22ea228e82aa03cb3926ba33bc2c8af27

I guess the table-wrappe has to stay then... And maybe I should really introduce some integration tests to prevent regressions like this... (If I eventually find some spare time

**Comment by wey-gu** [comment]
> @wey-gu Should be fixed with https://github.com/HEIGE-PCloud/DoIt/commit/01c4bdd22ea228e82aa03cb3926ba33bc2c8af27
> 
> 
> 
> I guess the table-wrappe has to stay then... And maybe I should really introduce some integration tests to prevent regressions like this... (If I eventually find some spare time

Wow thanks!

Please take good rests and don't be anxiety about it. Open source shouldn't be burning you out.

Those who is using it will test it♥️, if anything is broken and they care about them(like me), they could debug themselves instead of just drop a comment in an issue like I did.🤣
