### ISSUE TITLE
[FEATURE] 文章置顶功能

### ISSUE THREAD

**Issue by starsareintherose** [HEIGE-PCloud/DoIt#87]
### Describe the feature you want 描述你的功能需求

- Feature 1 文章置顶功能

### Useful reference 有价值的参考

不知是否存在，但是没有搜索到

**Comment by HEIGE-PCloud** [comment]
在 front matter 里用 `weight` 参数来设置置顶。

Ref: https://gohugo.io/content-management/front-matter/
