### ISSUE TITLE
[BUG] Search result content persists even when the cursor is not focusing on the search bar/搜索结果展示页会一直显示, 即使鼠标已经点到别处

### ISSUE THREAD

**Issue by CXwudi** [HEIGE-PCloud/DoIt#873]
### Describe the bug 描述你遇到的错误

If you typed something in the search bar and then click on other things, then this happens  
在搜索栏里输入点东西, 然后鼠标点其他地方, 就会变成这样
![image](https://user-images.githubusercontent.com/17377423/221323932-d50d022b-ec9b-491d-a42b-1d68b8c4ef63.png)

This happens on the demo site  
Demo网站也有这个问题

### Expected behavior 期待的行为

When the cursor no longer focus on the search bar, so does the search result content  
当鼠标点击页面其他位置的时候, 搜索结果应该消失

### Screenshots 屏幕截图

See above

**Comment by CXwudi** [comment]
~~Actually, never mind, it is my browser's issue. Probably some plugins or Tampermonkey script screw up the webpage~~

NVM it is not the browser's issue

**Comment by HEIGE-PCloud** [comment]
This is definitely a bug and I can reproduce it in my browser as well. I suspect it was introduced when I removed pjax loading and added lazy load for search. I will look into it once I am less busy :)
