### ISSUE TITLE
[FEATURE] Add an optional newsletter subscription form at the bottom of each blog post

### ISSUE THREAD

**Issue by reachsumit** [HEIGE-PCloud/DoIt#880]
### Describe the feature you want 描述你的功能需求

Thank you for supporting this excellent theme. May I request adding a newsletter signup section at the end of each blog post page?

**Comment by HEIGE-PCloud** [comment]
I am sorry I don't quite understand what you mean, what is a "newsletter signup section"? It will be very helpful if you can provide some examples and some example use cases.

**Comment by reachsumit** [comment]
Sorry, I missed adding an example.

If you see this theme: https://github.com/radity/raditian-free-hugo-theme

It adds a Newsletter subscription box at the bottom of the page, see screenshot below.
![image](https://user-images.githubusercontent.com/31574648/223813500-f5176603-e6a5-442e-99eb-64c7cd43016f.png)

A few other themes add integration with MailChimp etc to allow readers to signup with their emails.
for example: https://github.com/felicianotech/hugo-theme-lean-launch-page
![](https://d33wubrfki0l68.cloudfront.net/458185c2ac349f98061035bea692324e32b06bb6/0646a/themes/hugo-theme-lean-launch-page/screenshot_hudc2f42fa5bc069d369c7042abb891d36_178758_750x500_fill_catmullrom_top_3.png)

It would be great to have such a signup section show up at the end of each blog post in DoIt theme.

Please let me know if you require any more clarification on this request. Thank you!

**Comment by cs-mshah** [comment]
Yes. This is very useful. There can be an option to have a separate signup page just like `posts/`, and options can be given to 
- add newsletter signup section in home page
- add newsletter signup section or link at the end of a blogpost

**Comment by HEIGE-PCloud** [comment]
Different newsletter platforms have different APIs for the signup flow and there might be legal requirements for the end users to agree to their privacy policies.

It’s best for the site author to integrate the template provided by the newsletter platform directly. It should be quite straightforward to modify the layout files for pages that need to display the sign up form.

Closing this as not planned.
