### ISSUE TITLE
[FEATURE] add support of webmention

### ISSUE THREAD

**Issue by wey-gu** [HEIGE-PCloud/DoIt#889]
### Describe the feature you want 描述你的功能需求

ref:
- https://webmention.io/
- https://geekplux.com/posts/new-to-us

### Useful reference 有价值的参考

Thus we could collect discussions on Twitter per post.

But it's better to be allowed with existing comment systems.

**Comment by HEIGE-PCloud** [comment]
The example website has switched away from web mention, and [Twitter support has been dropped](https://brid.gy/about#rip-twitter) by Birdgy. I originally thought this would be a good exercise to build a web component for it, but it seems after a month, a lot of things have changed, is this still useful to you?

**Comment by wey-gu** [comment]
haha, got it @HEIGE-PCloud :D, and now I know we should always wait for sometimes on fancy tech hypes in the future, too!

Let's see what happens(if there will be a twist on Twitter API/Reddit API pricing policy~~~) in the future, I am closing this :-P.
