### ISSUE TITLE
[FEATURE] pageStyle = "wide" 页面间距问题

### ISSUE THREAD

**Issue by xiaobinqt** [HEIGE-PCloud/DoIt#907]
### Describe the feature you want 描述你的功能需求

![image](https://user-images.githubusercontent.com/23259661/231416749-1eca46fb-75d1-4e45-9572-9b52d293e3a8.png)

![image](https://user-images.githubusercontent.com/23259661/231415186-f433e40c-b732-4284-93df-7b97308dbac6.png)

我设置的 pageStyle = "wide" 这里的间距怎么空出来这么大 ?

样式是不是有点问题，还是我的配置有问题

![image](https://user-images.githubusercontent.com/23259661/231656082-6d8461dc-d734-44b9-875b-754e13125b0d.png)

我记的之前的样式是这样的

![image](https://user-images.githubusercontent.com/23259661/231415474-449c2edb-6f7e-41ea-b1de-38305106a796.png)

**Comment by HEIGE-PCloud** [comment]
事实上 pageStyle = "wide" 的样式会使每行文字过多，从而降低可读性。每行文字的数量保持在 65 个字符为最佳。我决定在下一个版本中彻底删除这个选项。

参考
https://www.smashingmagazine.com/2014/09/balancing-line-length-font-size-responsive-web-design/#:~:text=65%20characters%20(2.5%20times%20the,punctuation)%20per%20line%20for%20print.

**Comment by xiaobinqt** [comment]
> 事实上 pageStyle = "wide" 的样式会使每行文字过多，从而降低可读性。每行文字的数量保持在 65 个字符为最佳。我决定在下一个版本中彻底删除这个选项。
> 
> 参考 https://www.smashingmagazine.com/2014/09/balancing-line-length-font-size-responsive-web-design/#:~:text=65%20characters%20(2.5%20times%20the,punctuation)%20per%20line%20for%20print.

其实我个人觉得 normal 有点太窄了，之前有一版 .page 的宽度是 60%，感觉这个宽度和每行文字还挺好的，希望可以保留。

![image](https://user-images.githubusercontent.com/23259661/231922729-1a16894d-e0a0-47f3-bec4-906d6d82a4d3.png)
