### ISSUE TITLE
[BUG] Installation and hugo server

### ISSUE THREAD

**Issue by keybasegit** [HEIGE-PCloud/DoIt#908]
### Describe the bug 描述你遇到的错误

I followed the steps
hugo new site my_website
cd my_website
git init
git submodule add https://github.com/HEIGE-PCloud/DoIt.git themes/DoIt
copy and paste basic config TOML
hugo new posts/first_post.md Created new post and use yaml from exampleSite content/post
hugo server
![image](https://user-images.githubusercontent.com/83376558/231847678-ef2f689f-b941-4dd1-8908-cfad5238dee3.png)
It display incompatible system and error in comments
Till now I am using papermod. I seach in documentation without finding a clue. 

### Expected behavior 期待的行为

I expect the theme show my first post

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/83376558/231848499-d704bafb-d1e9-41ec-a5d2-18c842167fa9.png)

### Build Environment 构建环境

Arch linux, theme from https://github.com/HEIGE-PCloud/DoIt.git, hugo extended

### Preview Environment 预览环境

firefox, brave,

**Comment by eallion** [comment]
提示你了，版本不对
config 里改为 `version = "0.3.X"`

**Comment by degreeofcertainty** [comment]
Thanks. I downloaded zip and it's working

**Comment by degreeofcertainty** [comment]
Issue closed.

**Comment by degreeofcertainty** [comment]
Issue closed. Thanks. @Faust
