### ISSUE TITLE
[BUG] SVG 矢量图构建失败

### ISSUE THREAD

**Issue by WingsZeng** [HEIGE-PCloud/DoIt#909]
### Describe the bug 描述你遇到的错误

image shortcode 使用 svg 格式的图片会报错, 信息如下:

> failed to render shortcode "image": failed to process shortcode: "./themes/DoIt/layouts/shortcodes/image.html:22:12": execute of template failed: template: shortcodes/image.html:22:12: executing "shortcodes/image.html" at <partial "plugin/image.html" $options>: error calling partial: "./themes/DoIt/layouts/partials/plugin/image.html:8:22": execute of template failed: template: partials/plugin/image.html:8:22: executing "partials/plugin/image.html" at <.Height>: error calling Height: this method is only available for raster images. To determine if an image is SVG, you can do {{ if eq .MediaType.SubType "svg" }}{{ end }}

Hugo SVG 格式没有 Height 和 Width 属性, 而 @Sped0n 在 #860 中没有考虑到这一问题

### Build Environment 构建环境

- Theme version: after #860
- Hugo version: v0.111.3 extended

### Additional Information 补充信息

翻到一个应对 SVG 格式 lazyload 偏移的方法: https://github.com/gohugoio/hugo/issues/3700#issuecomment-705857100

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
我目前的想法是不为svg文件自动获取宽高，矢量文件的大小/缩放程度应该由用户自行选择。
btw能提供一下svg文件吗，我这里试了好几个hugo都没有报错。

**Comment by WingsZeng** [comment]
https://blog.wingszeng.top/v8-pwn-basics-1-jsobject/img/transition-tree.svg

我的写法是这样的:
```
{{< image src="img/transition-tree.svg" caption="Transition Tree" title="Transition Tree" >}}
```
