### ISSUE TITLE
[FEATURE] Add more options to code block

### ISSUE THREAD

**Issue by Cnily03** [HEIGE-PCloud/DoIt#912]
### Describe the feature you want 描述你的功能需求

能否为代码块添加多种选择，类似 [hackmd.io](https://hackmd.io) 的做法。如：
~~~markdown
```javascript=
something
```
~~~
表示添加行号（means showing line number）。

~~~markdown
```javascript!
something
```
~~~
表示换行（means break-line）。旨在解决列举大段base64时单行显示造成阅读不便的问题。

因为有些情况的代码块只有单行，标头在反而不便于阅读，所以也希望考虑
~~~markdown
```#javascript
something
```
~~~
表示显示标头（xxx语言）（means displaying the title of current code block）

### Useful reference 有价值的参考

https://hackmd.io

**Comment by tignioj** [comment]
怎么解决代码换行问题？我希望代码换行

**Comment by HEIGE-PCloud** [comment]
Implemented! See https://hugodoit.pages.dev/zh-cn/basic-markdown-syntax/#%E8%AF%AD%E6%B3%95%E9%AB%98%E4%BA%AE
