### ISSUE TITLE
文章上方的作者头像是否支持修改？

### ISSUE THREAD

**Issue by today-calm** [HEIGE-PCloud/DoIt#920]
### Describe the bug 描述你遇到的错误

求问文章上方的作者头像是否支持修改？我尝试修改了 avatar，没有生效。

```
# 作者配置
[author]
  name = " "
  avatar = "/images/avatar.webp"
```

### Screenshots 屏幕截图

<img width="369" alt="截屏2023-04-19 00 24 07" src="https://user-images.githubusercontent.com/128990484/232842238-c15dede8-0274-431a-86d7-d1492bc694aa.png">

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
不支持修改

**Comment by today-calm** [comment]
> 不支持修改

好的，谢谢
