### ISSUE TITLE
[Question] Google Analytics not being triggered

### ISSUE THREAD

**Issue by wey-gu** [HEIGE-PCloud/DoIt#924]
### Describe the feature you want 描述你的功能需求

Do we need to do something from the theme level to support google analytics 4, please? The existing google analytics will be phased out in July.

Thanks!

### Useful reference 有价值的参考

https://discourse.gohugo.io/t/how-to-make-site-updates-to-support-google-analytics-4/38271/5

```html
<!-- Google tag (gtag.js), where G-xxxxxxxxxxxx is the measure id from GA-4 -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-xxxxxxxxxxxx"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-xxxxxxxxxxxx');
</script>
```

**Comment by HEIGE-PCloud** [comment]
https://github.com/HEIGE-PCloud/DoIt/blob/c4e9d530d4d18c7a7504234cb9396e0c4bce71ff/layouts/partials/plugin/analytics.html#L4-L11

I think we have GA4 supported long ago. Did you encounter any issues when setting it up?

**Comment by wey-gu** [comment]
Wow, thanks @HEIGE-PCloud ,

I found my google analytics stopped collecting data after I started to break a single config file to `config/_default/*.toml` a month ago, so I was considering taking this chance to migrate to GA-4 when looking into this.

It's weird that now GA is not working with either v4 or old id.

```bash
~/dev/siwei.io/siwei.io main*
❯ grep analytics.google config -r -A2
config/_default/params.toml:  [analytics.google]
config/_default/params.toml-    id = "G-DYT*******"
config/_default/params.toml-    # whether to anonymize IP

~/dev/siwei.io/siwei.io main*
❯ hugo --gc 
Start building sites … 
hugo v0.111.3+extended darwin/arm64 BuildDate=unknown

                   | EN  | ZH-CN  
-------------------+-----+--------
  Pages            | 209 |   210  
  Paginator pages  |   4 |     7  
  Non-page files   | 214 |   331  
  Static files     | 106 |   106  
  Processed images |   0 |     0  
  Aliases          |  71 |   105  
  Sitemaps         |   2 |     1  
  Cleaned          |   0 |     0  

Total in 3020 ms

~/dev/siwei.io/siwei.io main*
❯ grep googletagmanager public/ -r       

# nothing around ga in public
```

I must be silly about something but I have no idea where it could go wrong for now 😭.

**Comment by HEIGE-PCloud** [comment]
@wey-gu have you set `analytics.enable` to true?

Under params.toml

```toml
[analytics]
  enable = true
  # Google Analytics
  [analytics.google]
    id = "G-DYT*******"
    # whether to anonymize IP
    # 是否匿名化用户 IP
    anonymizeIP = true
```

**Comment by wey-gu** [comment]
> @wey-gu have you set `analytics.enable` to true?
> 
> Under params.toml
> 
> ```toml
> [analytics]
>   enable = true
> ```

I punched myself in the face, that's the reason, how silly I am!!!

Thanks again! And sorry/embarrassed for this!
