### ISSUE TITLE
[Bug] 竖屏显示标题栏网站标题位置需要调整一下

### ISSUE THREAD

**Issue by techkoala** [HEIGE-PCloud/DoIt#93]
### Expected behavior 期待的行为

竖屏的时候网站标题位置有点奇怪，希望可以更靠左一些

### Screenshots 屏幕截图

![屏幕截图 2021-06-04 125957](https://user-images.githubusercontent.com/67769327/120748099-cc361600-c534-11eb-9842-aceebdf66bd2.jpg)

**Comment by techkoala** [comment]
补充一下，发现标题位置是根据浏览器窗口大小自适应的，上面截图的情况是最大化窗口时的情形（16：9屏幕竖向放置）

**Comment by HEIGE-PCloud** [comment]
https://b0e69a56.hugodoit.pages.dev/

更改了相关的CSS样式，能否在这个网站上进行一下测试，查看是否生效？

**Comment by techkoala** [comment]
> 
> 
> https://b0e69a56.hugodoit.pages.dev/
> 
> 更改了相关的CSS样式，能否在这个网站上进行一下测试，查看是否生效？

辛苦了~

现在是固定了？
![屏幕截图 2021-06-04 214549](https://user-images.githubusercontent.com/67769327/120811232-56569c80-c57e-11eb-9105-d9bc694ea553.jpg)
是这样的效果，无论窗口大小
