### ISSUE TITLE
[BUG] view count is showing as "[object Object] views" when using Waline

### ISSUE THREAD

**Issue by CXwudi** [HEIGE-PCloud/DoIt#940]
### Describe the bug 描述你遇到的错误

When using Waline, the view count is showing as "[object Object] views"

### Expected behavior 期待的行为

The view count should show the actual number of views

### Screenshots 屏幕截图

![image](https://user-images.githubusercontent.com/17377423/236909002-7f54f990-1ce8-41d9-b40d-1d5bc43c991b.png)

You can check it in https://blog.mikufancx.cyou/posts/202207/hello-world/

### Build Environment 构建环境

- OS: Win10 Pro, WSL2 Ubuntu 22.04
- Theme version: https://github.com/HEIGE-PCloud/DoIt/commit/0e844049c6a15fbc377031f1f3b7c67ac2abd1de
- Hugo version: hugo v0.110.0+extended

### Additional Information 补充信息

I guess there is a recent update of Waline that changes some structure and break the DoIt code?

**Comment by HEIGE-PCloud** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/52968553/236945843-1d9f73b1-9e6a-40fb-b962-fa65224efe11.png">

I've seen some suspicious network failures, probably related.

**Comment by CXwudi** [comment]
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/52968553/236945843-1d9f73b1-9e6a-40fb-b962-fa65224efe11.png">
> 
> I've seen some suspicious network failures, probably related.

Hi, this is what I saw, as the user who is not in China mainland
![image](https://user-images.githubusercontent.com/17377423/236997320-5dc2d9d9-da7b-4374-8a2e-546467bbdbbc.png)

The `cdn.bilicdn.tk` is someone else's jsdelivr proxy, the proxy is used for loading custom emojis for Waline. So your error message probably just indicate that the emojis would not show up properly (because it is blocked in China?), but I personally don't think this proxy have anything to do with the view count issue

**Comment by CXwudi** [comment]
I think these are related:

https://github.com/walinejs/waline/issues/1915
https://github.com/walinejs/waline/issues/1916

**Comment by CXwudi** [comment]
Issue fixed, avoid `@waline/vercel` at version `1.27.x` and use the newest version

**Comment by HEIGE-PCloud** [comment]
> > <img alt="image" width="960" src="https://user-images.githubusercontent.com/52968553/236945843-1d9f73b1-9e6a-40fb-b962-fa65224efe11.png">
> > I've seen some suspicious network failures, probably related.
> 
> Hi, this is what I saw, as the user who is not in China mainland ![image](https://user-images.githubusercontent.com/17377423/236997320-5dc2d9d9-da7b-4374-8a2e-546467bbdbbc.png)
> 
> The `cdn.bilicdn.tk` is someone else's jsdelivr proxy, the proxy is used for loading custom emojis for Waline. So your error message probably just indicate that the emojis would not show up properly (because it is blocked in China?), but I personally don't think this proxy have anything to do with the view count issue

Turns out JANET has this domain blocked for some reason :-( Glad it's fixed now.
