### ISSUE TITLE
[BUG] Clicking top menu items will scroll the page to the top

### ISSUE THREAD

**Issue by CXwudi** [HEIGE-PCloud/DoIt#942]
### Describe the bug 描述你遇到的错误

I am not sure is it the intended behaviour or not, but if I click something on the menu while I am borrowing a page. It automatically scrolls the page to the top

This happens in anywhere in the demo site

### Expected behavior 期待的行为

If this is not the intended behaviour, the page should not scroll up when clicking anything on the top menu

### Screenshots 屏幕截图

![2023-05-12 20-47-59](https://github.com/HEIGE-PCloud/DoIt/assets/17377423/a0cba8dd-70ab-4e77-acb4-33e92c7b1cc2)

### Build Environment 构建环境

The demo site

### Preview Environment 预览环境

The demo site

### Additional Information 补充信息

I am not too sure should I report it as an issue or a discussion, because I am not sure if it is an intended behaviour

If it is an intended behaviour, is there a way to disable the scrolling?

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
I think it's not an intended behavior, the original LoveIt theme won't scroll when clicking the menu items.

Although on Safari only the search button will trigger this weird behavior, I don't know whether my fix works on other platforms.

I have already made a [PR](https://github.com/HEIGE-PCloud/DoIt/pull/943) about this, can you help with the test?

**Comment by CXwudi** [comment]
Thanks for the fix @Sped0n, I gonna give a try now

**Comment by CXwudi** [comment]
@Sped0n I tested your fix locally. It works for me on Chrome and Edge, I am using Win10

**Comment by CXwudi** [comment]
I also saw your PR and realized that the fix is quite simple. I guess I have to learn how Hugo theme works now so that hopefully one day I can fix these kinds of small issues myself and make a PR back

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
> I also saw your PR and realized that the fix is quite simple. I guess I have to learn how Hugo theme works now so that hopefully one day I can fix these kinds of small issues myself and make a PR back

💪💪💪
