### ISSUE TITLE
[FEATURE] Add a link preview

### ISSUE THREAD

**Issue by reachsumit** [HEIGE-PCloud/DoIt#948]
### Describe the feature you want 描述你的功能需求

Request to add support for link previews like this:

![image](https://github.com/HEIGE-PCloud/DoIt/assets/31574648/4d76fa32-309a-484b-a682-edc635a84c88)

This preview can be generated using the image and title from another post from the same website. 

### Useful reference 有价值的参考

> https://blog.jeremylikness.com/blog/create-article-preview-in-hugo/

The above link recommends adding a shortcode like this:

```
{{$page := .Site.GetPage (.Get 0)}}
<div class="container alert alert-secondary">
    <div><a href="{{$page.RelPermalink}}" alt="{{$page.Title}}">
        <strong>{{ $page.Title }}</strong>
    </a></div>
    <div class="float-left m-2">
    {{ if $page.Params.image }}
        {{ $original := print "images/" (path.Base $page.Params.image) }}
        {{ $originalImg := $page.Resources.GetMatch $original }}
        {{ if $originalImg }}
            {{ $thumbnailImg := $originalImg.Fit "200x100" }}
            {{ printf `<img src="%s" alt="%s">` 
                $thumbnailImg.RelPermalink $page.Title | safeHTML }}
        {{end}}
    {{end}}
    </div>
    <p><small>{{$page.Description}}</small></p>
    <div class="clearfix"></div>
</div>
```

and using it like this:

```
{{<relativelink "/blog/migrate-from-medium-to-hugo" >}}
```

**Comment by CXwudi** [comment]
Does [`showcase`](https://hugodoit.pages.dev/theme-documentation-extended-shortcodes/#showcase) work for you (uhhh, you need to scroll all the way down to see one example)

**Comment by reachsumit** [comment]
Perfect. Yes, this will do. Thank you!
