### ISSUE TITLE
[FEATURE] 广告配置功能

### ISSUE THREAD

**Issue by tonyho** [HEIGE-PCloud/DoIt#965]
### Describe the feature you want 描述你的功能需求

可以添加配置广告banner, Google AD的快捷配置吗?

**Comment by HEIGE-PCloud** [comment]
亲爱的 @tonyho，

感谢您对 DoIt 主题的关注，并抽出时间提出请求以获得 Google 广告支持。我理解您希望通过博客赚钱，并认识到广告有利于为内容创作者提供财务支持。然而，由于个人对广告及其对用户体验的影响的信仰，我决定不在本主题中包括 Google 广告支持。广告具有侵入性，影响读者的阅读体验，破坏博客的设计风格，这与本主题的设计理念相悖。我承认许多用户都希望利用广告作为其博客的收入来源，并尊重这个想法。但是作为本主题的维护者，我选择将美观和用户体验放在首位，且我坚信不支持广告符合这些目标。市场上有其他搭载 Google 广告支持的主题，您可以选择那些选项，以更好地满足您的需求。如果通过博客赚钱是您项目的重要组成部分，请务必探索这些选项。

祝您在博客事业中一切顺利。

顺祝商祺。
