### ISSUE TITLE
[BUG] Artalk darkmode and black theme switch

### ISSUE THREAD

**Issue by eallion** [HEIGE-PCloud/DoIt#966]
### Describe the bug 描述你遇到的错误

Sorry for my fault. I tested a lot of Artalk, but I just forgot to test darkmode.
Theme DoIt seems to have a complex logical structure, and I can only do some simple CRUD. I am unable to submit a PR for this.

**Comment by HEIGE-PCloud** [comment]
https://github.com/HEIGE-PCloud/DoIt/assets/52968553/a1cd7681-ceb4-48c3-b26f-948da7d5d00b

It seems to work?

**Comment by eallion** [comment]
I don't know why, sometimes it works fine.
