### ISSUE TITLE
[FEATURE] Handle tailwind css build more gracefully

### ISSUE THREAD

**Issue by 713b76b7-2247-4bd5-98a7-014226363f9b** [HEIGE-PCloud/DoIt#967]
### Describe the feature you want 描述你的功能需求

https://github.com/gohugoio/hugo/releases/tag/v0.112.0

Hugo now adds a new `build.cachebusters` config option for the resource cache that allows more fine grained control over when to trigger a new Tailwind build, no need to use additional npm build script.

Although it's a nice feature to have, I think the hugo minimum version is a little bit aggresive.

### Useful reference 有价值的参考

https://github.com/bep/hugo-starter-tailwind-basic

**Comment by HEIGE-PCloud** [comment]
What I did there is to directly commit the generated [`main.css`](https://github.com/HEIGE-PCloud/DoIt/blob/main/assets/css/main.css) into the repo, and add a [`npm run dev`](https://github.com/HEIGE-PCloud/DoIt/blob/5512824c19f69fe110062dade9880f8bd8841f85/package.json#L7) script to run Tailwind CSS watch and Hugo at the same time. This way no explicit build step is needed for neither the developer nor end users.

**Comment by HEIGE-PCloud** [comment]
Upon a closer inspection, the new update is not particular useful for DoIt's current architecture. Closing this for now.
