### ISSUE TITLE
[FEATURE] Toggle lists, headings

### ISSUE THREAD

**Issue by cs-mshah** [HEIGE-PCloud/DoIt#969]
### Describe the feature you want 描述你的功能需求

It would be amazing to have a toggle available for things like headings, lists, nested lists so that relevant sections can be toggled while reading long blogs.

### Useful reference 有价值的参考

You can check out obsidian to get an idea of what I want.

**Comment by HEIGE-PCloud** [comment]
Here are some reasons that I think this might not be a good idea (and why most website, including obsidian publish, does not support this).

- The implementation of toggle buttons for headings, lists, and nested lists may require significant development time and resources.
- Implementation may also add additional complexity to the blog design and may confuse readers.
- Adding toggle buttons may detract from the overall aesthetic of the blog.
- Adding the ability to toggle sections may decrease readability and the flow of the blog, as readers may skip sections that are deemed "less relevant."
- The toggle buttons may not be necessary for certain types of blogs or articles that are not extremely long or complex.
The implementation of toggle buttons may add to the overall load time of the blog.
- Toggles may negatively affect the site's SEO as search engines may not be able to index the content accurately.
- There may be additional technical challenges involved in implementing such a feature, such as compatibility with various browsers and devices.

I am closing this for now, but feel free to reopen the issue for further discussions.
