### ISSUE TITLE
[BUG] Disqus theme not switching with DoIt

### ISSUE THREAD

**Issue by jmflaherty** [HEIGE-PCloud/DoIt#990]
### Describe the bug 描述你遇到的错误

When using Disqus, upon switching themes, the Disqus theme does not change with the website. There is an 'auto' config in Disqus, but it does not work as one would expect.

### Expected behavior 期待的行为

I expect Disqus to switch themes in the same way as our DoIt sites do.
In the case of the Dark and Black DoIt themes, I would expect Disqus to use its Dark theme. Even if it does not match the Black from DoIt, it would be an improvement.

### Screenshots 屏幕截图

![image](https://github.com/HEIGE-PCloud/DoIt/assets/12985011/1186f2a8-10bd-43b7-9491-2364c4a448ba)

### Build Environment 构建环境

- OS: Linux Mint 21.1
- Hugo: 0.113.0 extended
- Doit commit: https://github.com/HEIGE-PCloud/DoIt/commit/8465ab2ab46e340236c63d7168b8dcad6de53751

### Preview Environment 预览环境

- OS: Linux Mint 21.1, Android 12
- Chrome, Firefox

### Additional Information 补充信息

I have found several people solving this issue with what is described in this post:
https://thisdevbrain.com/disqus-auto-theme-switching/

It would depend on what is described here, so Disqus can determine what color scheme to use when reset:
https://help.disqus.com/en/articles/1717201-disqus-appearance-customizations#:~:text=Appearance%20Tweaks%20for%20all%20sites

**Comment by HEIGE-PCloud** [comment]
https://stackoverflow.com/questions/64960793/toggling-dark-light-mode-in-disqus

This appears to be a limitation on Disqus' side. The only way around it is to recreate the comment widget everytime the color theme is switched, which I think it's not worth it as most readers do not toggle color theme in the middle of reading an article. Closing this for now.
