### ISSUE TITLE
[FEATURE] socials to add

### ISSUE THREAD

**Issue by JoshuaACasey** [HEIGE-PCloud/DoIt#992]
### Describe the feature you want 描述你的功能需求

Love to see that Mastodon is included (not surprised, since it was already included in LoveIt). But I would love to see Pixelfed added, and with the growth of Lemmy/Kbin due to the whole Reddit fiasco happening I'd love to see Lemmyh/Kbin added.

Example Pixelfed profile link: https://pixelfed.social/USERNAME

Example Lemmy profile link: https://lemmy.world/u/USERNAME
Example Lemmy community link:  https://lemmynsfw.com/c/CommunityName

Example Kbin profile link: Sorry. I don't have a kbin account

In embracing the fediverse, it's probably not a bad idea to add support for Peertube profile links (youtube alternative), but I do not personally use peertube so I don't have an example profile link to give

**Comment by 713b76b7-2247-4bd5-98a7-014226363f9b** [comment]
If you want to apply it immediately, you can try to modify the `social.yml` under `assets/data`.

Just like this:

```yaml
blabla:
  Weight: 123
  Prefix: https://blabla/USERNAME
  Title: blabla
  Icon:
    Class: FONTAWESOME_LOGO_HERE
```

imo although supporting all these new social medias is technically feasible and simple, it is a littlie bit unnecessary. The main problem is that these new social media may not necessarily have the corresponding fontawesome icon, being forced to self-implant or achieved with some hack might cause a certain deviation on the web page, I would rather not push the implantation if it is the case.

@HEIGE-PCloud what's your opinion?
